-- GENERATED by apps/api/scripts/gen-legal-seed.ts from docs/legal/*.md — DO NOT EDIT BY HAND.
-- 10 legal templates, version 0.1-template, locale id, published (visible via GET /v1/legal/documents).
-- TEMPLATE text: must be reviewed by legal counsel before production launch (banner kept in every body).
-- Idempotent: published rows are immutable, re-running never changes them.
BEGIN;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('COMMUNITY_GUIDELINES', '0.1-template', 'id', $jk_legal$Pedoman Komunitas$jk_legal$, $jk_legal$Cara bersikap di JastipKita — jujur, aman, dan saling menghormati — serta konsekuensi pelanggaran.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Pedoman ini melengkapi [Syarat & Ketentuan](terms-of-service.md) dan [Perjanjian Traveler](traveler-agreement.md). Tingkat sanksi adalah rancangan dan perlu diselaraskan dengan prosedur Trust & Safety.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU]

JastipKita mempertemukan orang yang belum saling kenal untuk urusan uang dan barang. Pedoman ini ada supaya setiap transaksi terasa aman bagi semua pihak.

## 1. Jujur

- Deskripsikan barang, harga, dan kondisi apa adanya. Unggah struk dan foto asli.
- Traveler: beli hanya setelah **PURCHASE APPROVED**, dan deklarasikan barang titipan dengan jujur kepada Bea Cukai.
- Ulasan dan rating harus mencerminkan pengalaman nyata. Jangan menawarkan imbalan untuk ulasan, dan jangan membuat akun lain untuk menilai diri sendiri.

## 2. Tetap di dalam Platform

- Semua pembayaran melalui SafePay. **Jangan** meminta atau mengirim transfer ke rekening pribadi, dan jangan membagikan nomor rekening di chat.
- Komunikasi transaksi melalui chat aplikasi agar tercatat bila terjadi sengketa.

## 3. Aman

- Jangan membagikan PIN serah terima sebelum barang diperiksa, kode OTP, atau kata sandi kepada siapa pun — termasuk yang mengaku sebagai CS JastipKita.
- Bertemulah di tempat umum yang ramai untuk serah terima langsung.
- Jangan menitipkan atau membawa barang terlarang, palsu, atau milik orang lain di luar transaksi Platform.

## 4. Saling menghormati

- Tidak ada pelecehan, ancaman, ujaran kebencian, atau diskriminasi berdasarkan suku, agama, ras, antargolongan, gender, disabilitas, atau latar belakang lainnya.
- Hormati privasi: jangan menyebarkan data pribadi pengguna lain di luar keperluan transaksi.
- Selesaikan perbedaan dengan sopan; bila buntu, gunakan Dispute Center.

## 5. Penegakan

| Tingkat | Contoh | Konsekuensi yang mungkin |
|---|---|---|
| Ringan | bahasa kasar, keterlambatan tanpa kabar | peringatan, pengurangan Trust Score |
| Sedang | ajakan bayar di luar SafePay, ulasan palsu, pembatalan berulang | pembatasan fitur, penahanan payout sementara, penurunan level |
| Berat | penipuan, barang palsu, bukti dipalsukan, barang terlarang, penyamaran deklarasi | penangguhan/penutupan akun, penahanan dana untuk penyelesaian, pelaporan kepada pihak berwenang |

Keputusan penegakan dicatat. Anda dapat mengajukan banding satu kali melalui kanal bantuan dalam [JUMLAH] hari sejak pemberitahuan.

## 6. Melapor

Gunakan menu **Laporkan** di profil, chat, atau transaksi, atau hubungi [E-MAIL CS]. Laporan ditangani secara rahasia.
$jk_legal$,
        'Versi template awal dari docs/legal/community-guidelines.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('COOKIES', '0.1-template', 'id', $jk_legal$Kebijakan Cookie & Penyimpanan Lokal$jk_legal$, $jk_legal$Penyimpanan yang dipakai situs JastipKita, mengapa diperlukan, dan bagaimana analitik hanya berjalan setelah persetujuan.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Daftar di bawah mencerminkan kode situs saat ini (`apps/web`). Setiap penambahan cookie, SDK, atau analitik **wajib** memperbarui dokumen ini dan banner persetujuan sebelum dirilis.

**Versi:** 0.2 (draf) — memperbarui nama kunci penyimpanan & kebijakan token (keamanan origin bersama) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Pengendali data:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian]

## 1. Ringkasnya

- Situs `antarkitaindonesia.com/jastipkita` **tidak memasang cookie pihak ketiga, pixel iklan, atau analitik** saat ini.
- Kami hanya memakai penyimpanan lokal peramban (*localStorage/sessionStorage*) yang **benar-benar diperlukan** agar fitur yang Anda minta berfungsi.
- Bila kelak analitik diaktifkan, analitik hanya berjalan **setelah Anda menyetujuinya** melalui banner privasi, dan dokumen ini diperbarui terlebih dahulu.

## 2. Penyimpanan yang dipakai

| Nama | Jenis | Tujuan | Kapan dibuat | Masa simpan |
|---|---|---|---|---|
| `jk:consent` | localStorage | Mengingat pilihan Anda pada banner privasi | setelah Anda memilih | sampai dihapus dari peramban atau Anda keluar (logout) |
| `jk:theme` | localStorage | Mengingat tema terang/gelap yang Anda pilih | hanya setelah Anda menekan tombol tema | sampai dihapus dari peramban atau Anda keluar (logout) |
| `jk:refresh` | sessionStorage | Token penyegar (*refresh token*) agar Anda tetap masuk selama tab terbuka (halaman Akun) | setelah login | berakhir saat tab ditutup, saat logout, atau saat token dirotasi |
| `jk:device` | sessionStorage | ID perangkat acak untuk keamanan sesi (hanya HMAC-nya yang disimpan server) | saat login | berakhir saat tab ditutup atau logout |

Token akses (*access token*) **hanya disimpan di memori** halaman dan hilang saat halaman ditutup; tidak pernah ditulis ke penyimpanan peramban. Semua kunci memakai awalan `jk:` dan dihapus seluruhnya saat Anda keluar (logout). Karena situs ini berbagi domain `antarkitaindonesia.com` dengan layanan AntarKita lain, kami menerapkan Content-Security-Policy ketat di setiap halaman.

## 3. Pihak ketiga

- **Hosting situs**: [PENYEDIA HOSTING, mis. GitHub Pages] dapat mencatat alamat IP pengunjung dalam log server untuk keamanan dan operasional, sesuai kebijakan privasinya.
- **API JastipKita**: saat Anda memakai kalkulator, pemeriksa barang, pencarian trip, atau akun, peramban mengirim permintaan ke API kami ([DOMAIN API]); permintaan ini tidak memakai cookie.
- **Google Sign-In** (bila diaktifkan): skrip Google hanya dimuat setelah Anda menekan tombol "Masuk dengan Google".
- Tautan ke situs lain (mis. WhatsApp, toko aplikasi) tunduk pada kebijakan masing-masing.

## 4. Mengelola pilihan Anda

Buka **Pengaturan cookie** di bagian bawah setiap halaman untuk mengubah pilihan, atau hapus data situs melalui pengaturan peramban. Menghapus `jk-session` akan mengeluarkan Anda dari akun di web.

## 5. Kontak

[E-MAIL DPO] · Lihat juga [Kebijakan Privasi](privacy-policy.md).
$jk_legal$,
        'Versi template awal dari docs/legal/cookie-policy.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('KYC', '0.1-template', 'id', $jk_legal$Persetujuan Pemrosesan Data Verifikasi (KYC)$jk_legal$, $jk_legal$Persetujuan eksplisit terpisah untuk pemrosesan data identitas dan biometrik (selfie & liveness) dalam verifikasi akun JastipKita.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Data biometrik dan data keuangan pribadi adalah **data pribadi yang bersifat spesifik** (Pasal 4 ayat (2) UU 27/2022). Persetujuan ini diminta **terpisah** dari Syarat & Ketentuan, dicatat per versi, dan dapat ditarik. Wajib didahului DPIA (PP 33/2026) sebelum produksi. Lengkapi **[KURUNG SIKU]**.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Pengendali data:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian] · **DPO:** [E-MAIL DPO]

## 1. Untuk apa verifikasi dilakukan

Verifikasi identitas (Know Your Customer) diperlukan untuk menaikkan akun ke **Level 3 — Identitas terverifikasi** dan **Level 4 — Traveler terverifikasi**, agar Anda dapat menerima titipan, bertransaksi dengan nilai lebih tinggi, dan menerima payout. Tujuannya: mencegah penipuan dan penyalahgunaan identitas, melindungi pengguna lain, serta memenuhi kewajiban hukum yang berlaku.

## 2. Data yang diproses

| Data | Keterangan |
|---|---|
| Jenis & nomor dokumen identitas (KTP atau paspor) | dipakai untuk pencocokan; ditampilkan hanya tersamar |
| Nama lengkap sesuai dokumen | dicocokkan dengan profil dan rekening payout |
| Foto dokumen identitas | disimpan terenkripsi |
| **Selfie dan data liveness (biometrik)** | memastikan Anda adalah pemilik dokumen dan orang sungguhan |
| Rekening payout (Traveler) | validasi nama pemilik rekening; ditampilkan tersamar |
| Hasil pemeriksaan | skor kecocokan wajah, hasil liveness, deteksi duplikasi, catatan peninjau |

## 3. Cara pemrosesan

1. Pemeriksaan otomatis oleh sistem kami dan/atau penyedia verifikasi **[NAMA VENDOR KYC, LOKASI PEMROSESAN]**, dilanjutkan peninjauan manusia bila diperlukan. Anda dapat meminta peninjauan manusia atas penolakan otomatis.
2. File disimpan terenkripsi (envelope AES-256-GCM) di penyimpanan objek terpisah; basis data hanya menyimpan referensi dan hash. Akses dibatasi pada peran yang berwenang dan dicatat.
3. Data KYC **tidak** dibagikan kepada pengguna lain. Pengguna lain hanya melihat level verifikasi Anda.
4. Data biometrik **tidak** dipakai untuk pemasaran, pelatihan model pihak ketiga, atau tujuan lain di luar verifikasi dan pencegahan penipuan.

## 4. Retensi

Data identitas dan dokumen KYC disimpan selama akun aktif dan **5 tahun setelah akun ditutup** (asumsi berdasarkan praktik APU-PPT; **[LEGAL REVIEW]**), kemudian dihapus. Pengajuan yang ditinggalkan dihapus sesuai kebijakan retensi.

## 5. Transfer ke luar negeri

Bila penyedia verifikasi memproses data di luar Indonesia, transfer dilakukan dengan pelindungan sesuai Pasal 56 UU PDP. **[Sebutkan negara & dasar transfer.]**

## 6. Hak Anda

Anda dapat mengakses, memperbaiki, meminta penghapusan (dengan memperhatikan kewajiban retensi), dan **menarik persetujuan ini** kapan saja melalui **Profil → Keamanan & privasi** atau [E-MAIL DPO]. Penarikan persetujuan akan menurunkan level verifikasi dan membatasi fitur yang mensyaratkannya; transaksi yang sedang berjalan tetap diselesaikan.

## 7. Pernyataan persetujuan

> Dengan mencentang **"Saya setuju"**, saya memberikan persetujuan eksplisit kepada [NAMA BADAN USAHA] untuk memproses data identitas dan data biometrik saya (foto dokumen, selfie, dan data liveness) serta data rekening payout sebagaimana dijelaskan di atas, untuk tujuan verifikasi identitas dan pencegahan penipuan. Saya memahami bahwa saya dapat menarik persetujuan ini kapan saja.

Versi persetujuan dan waktu pemberiannya dicatat pada akun Anda.
$jk_legal$,
        'Versi template awal dari docs/legal/kyc-consent.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('MARKETING', '0.1-template', 'id', $jk_legal$Persetujuan Komunikasi Pemasaran$jk_legal$, $jk_legal$Persetujuan opsional untuk menerima promo dan kabar produk JastipKita, dan cara menariknya.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Persetujuan ini **opsional**, tidak dicentang secara default, dan terpisah dari Syarat & Ketentuan (PP 33/2026). Menolak atau menariknya tidak memengaruhi penggunaan layanan.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Pengendali data:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian]

## 1. Apa yang Anda setujui

Bila Anda memberikan persetujuan, kami dapat mengirimkan:

- promo, kode diskon, dan program referral;
- kabar rute/negara baru, fitur baru, dan tips titip belanja;
- survei singkat untuk memperbaiki layanan.

Pesan layanan (OTP, status transaksi, keamanan, perubahan ketentuan) **bukan** pemasaran dan tetap dikirim tanpa persetujuan ini.

## 2. Kanal dan frekuensi

Kanal: e-mail, notifikasi aplikasi (push), dan — bila Anda memilihnya — WhatsApp/SMS. Kami berupaya membatasi frekuensi pada [MAKS. PESAN PER MINGGU]. Anda dapat memilih kanal per jenis di **Profil → Notifikasi**.

## 3. Data yang dipakai

Nama, kontak, bahasa, negara/kategori minat, serta ringkasan aktivitas (mis. rute yang pernah dititip) untuk menyesuaikan penawaran. Kami **tidak menjual** data Anda dan tidak membagikannya kepada pengiklan pihak ketiga untuk tujuan mereka sendiri.

## 4. Menarik persetujuan

Kapan saja melalui **Profil → Notifikasi**, tautan berhenti berlangganan di setiap e-mail, membalas "STOP" pada WhatsApp/SMS, atau [E-MAIL DPO]. Penarikan diproses paling lambat **3 × 24 jam** dan tidak memengaruhi pemrosesan sebelumnya.

## 5. Pernyataan persetujuan

> Saya bersedia menerima informasi promo dan produk JastipKita melalui kanal yang saya pilih. Saya dapat menarik persetujuan ini kapan saja.
$jk_legal$,
        'Versi template awal dari docs/legal/marketing-consent.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('PAYMENT_TERMS', '0.1-template', 'id', $jk_legal$Ketentuan Pembayaran (SafePay)$jk_legal$, $jk_legal$Cara kerja SafePay, peran mitra payment gateway berizin, biaya, penguncian kurs, penggantian bea & pajak, chargeback, dan payout Traveler.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Mengacu pada `docs/04-payments-ledger.md`, `docs/research/02-xendit-integration.md`, dan konfigurasi `pricing.*` / `fx.lock` / `money.policy`. **Status integrasi pembayaran: SANDBOX** — belum ada transaksi uang sungguhan. Biaya metode pembayaran adalah **asumsi** sampai kontrak mitra ditandatangani. Kelayakan pola "dana ditahan sampai barang diterima" wajib dikonfirmasi tertulis oleh mitra pembayaran dan ditinjau konsultan hukum (PBI 23/6/PBI/2021) sebelum peluncuran.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Penyelenggara:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian]

## 1. Apa itu SafePay

1. **SafePay** adalah nama alur pembayaran di JastipKita: pembayaran Penitip **diproses dan ditahan oleh mitra payment gateway yang berizin Bank Indonesia** — [NAMA MITRA PAYMENT GATEWAY & NOMOR IZIN] — dan baru dilepaskan kepada Traveler setelah syarat pelepasan terpenuhi.
2. **JastipKita bukan bank, bukan penyedia jasa pembayaran, dan bukan penerbit uang elektronik/dompet digital.** Dana tidak melewati rekening bank JastipKita maupun rekening pribadi siapa pun. JastipKita mencatat hak masing-masing pihak atas dana tersebut dalam buku besar per transaksi (double-entry, append-only).
3. JastipKita Credit adalah potongan harga tertutup (closed-loop) yang tidak dapat diisi ulang, dicairkan, atau dipindahkan.

## 2. Alur dana

1. **Pembayaran** — Penitip membayar Total Landed Cost melalui metode yang tersedia. Status menjadi **PAYMENT SECURED** setelah pemberitahuan pembayaran diverifikasi (tanda tangan, nominal, dan mata uang cocok).
2. **Penahanan** — dana dicatat terpisah per komponen: dana barang, cadangan bea & pajak, dan biaya layanan.
3. **Pembelian** — Traveler hanya boleh membeli setelah **PURCHASE APPROVED**.
4. **Pelepasan** — setelah Penitip mengonfirmasi penerimaan (atau otomatis 48 jam setelah DELIVERED tanpa dispute), sistem menjadwalkan payout kepada Traveler (penggantian harga barang + fee + penggantian bea & pajak yang dibayar) dan membukukan pendapatan JastipKita.
5. **Refund** — bila transaksi dibatalkan atau dispute diputuskan, dana dikembalikan sesuai [Kebijakan Refund](refund-policy.md).

## 3. Biaya

Semua biaya tampil pada Rincian Biaya sebelum membayar.

| Biaya | Besaran saat ini | Catatan |
|---|---|---|
| Traveler Fee | ditentukan Traveler; min. Rp25.000, maks. 30% harga barang | hak Traveler |
| JastipKita Protection | 1,5% harga barang (min. Rp5.000, maks. Rp300.000) | [LEGAL REVIEW: cakupan perlindungan & apakah produk asuransi terlibat] |
| Platform Fee | 5% harga barang (min. Rp10.000, maks. Rp750.000) | pendapatan JastipKita |
| PPN atas layanan | 12% × DPP 11/12 atas Protection + Platform Fee | hanya bila JastipKita telah menjadi PKP [TAX REVIEW] |
| Biaya pembayaran | Virtual Account Rp4.500; QRIS 0,7%; e-wallet 1,5%; kartu 2,9% + Rp2.000 | **asumsi** sampai kontrak mitra; dapat dibulatkan agar menutup biaya gateway |
| Bea masuk & pajak impor | estimasi sesuai PMK 34/2025 | dibayarkan Traveler kepada negara |
| Nilai barang minimum | Rp100.000 per titipan | — |

Diskon promo tidak pernah mengurangi pajak atau bea.

## 4. Kurs

1. Harga dalam mata uang asing dikonversi dengan kurs acuan penyedia data kurs ditambah markup kurs yang diungkapkan (umumnya 1,5%; KRW 2%).
2. Kurs **dikunci 30 menit** saat checkout. Bila waktu habis sebelum pembayaran, kurs diperbarui dan Rincian Biaya dihitung ulang.
3. Estimasi bea & pajak memakai kurs acuan; Bea Cukai memakai kurs pajak (KMK) pada minggu kedatangan, sehingga tagihan resmi dapat berbeda.

## 5. Bea & pajak impor

1. Estimasi bea masuk dan pajak impor disimpan sebagai **cadangan bea & pajak** dan digunakan untuk mengganti pembayaran resmi Traveler kepada Bea Cukai berdasarkan bukti pembayaran yang diunggah.
2. JastipKita **bukan pemungut** bea masuk atau pajak impor. Penyelesaian selisih antara estimasi dan tagihan resmi: **[LEGAL/FINANCE REVIEW]**.

## 6. Perubahan harga dan pembayaran tambahan

Bila Penitip menyetujui kenaikan harga yang melebihi dana yang diamankan, Penitip membayar tambahan melalui SafePay sebelum pembelian disetujui. Selisih kecil dalam toleransi dapat ditanggung JastipKita dan dicatat sebagai promosi.

## 7. Chargeback dan pembayaran yang bermasalah

1. Bila Penitip mengajukan sanggahan/chargeback kepada penerbit kartu atas transaksi yang sedang berjalan atau sudah selesai, JastipKita dapat menahan payout terkait, menyampaikan bukti transaksi kepada mitra pembayaran, dan menangguhkan akun sampai sanggahan selesai.
2. Kami menganjurkan Penitip memakai **Dispute Center** terlebih dahulu — lebih cepat dan tidak dikenai biaya chargeback.
3. Chargeback yang terbukti tidak beritikad baik dapat dibebankan biaya yang dikenakan mitra pembayaran kepada kami (saat ini sekitar USD 25 per kasus **[asumsi, sesuai daftar harga mitra]**).
4. Dana yang masuk setelah invoice kedaluwarsa atau setelah transaksi dibatalkan dikembalikan otomatis.

## 8. Payout Traveler

1. Payout dikirim ke rekening/e-wallet atas nama Traveler yang tervalidasi; nomor rekening hanya ditampilkan tersamar.
2. Payout dapat ditahan bila ada dispute terbuka, indikasi risiko, atau permintaan otoritas; alasan penahanan dicatat.
3. Biaya transfer payout saat ini ditanggung JastipKita; nilai payout minimum Rp10.000.
4. Payout yang gagal dicoba ulang otomatis hingga 3 kali sebelum ditangani tim.

## 9. Keamanan pembayaran

Jangan pernah membayar di luar SafePay atau mentransfer ke rekening pribadi Traveler. Transaksi di luar Platform tidak dilindungi dan tidak dapat diajukan dispute.

## 10. Kontak

[E-MAIL CS] · [NOMOR WHATSAPP CS]
$jk_legal$,
        'Versi template awal dari docs/legal/payment-terms.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('PRIVACY', '0.1-template', 'id', $jk_legal$Kebijakan Privasi$jk_legal$, $jk_legal$Bagaimana JastipKita mengumpulkan, memakai, membagikan, menyimpan, dan melindungi data pribadi sesuai UU 27/2022 tentang Pelindungan Data Pribadi.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Disusun berdasarkan UU Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi (UU PDP) dan ringkasan PP 33/2026 dalam `docs/research/05-legal-regulatory.md`, serta arsitektur data aktual (`docs/03-database.md`, `docs/api/identity.md`). Durasi retensi berasal dari tabel `data_retention_policies` yang **seluruhnya masih asumsi**. Lengkapi semua **[KURUNG SIKU]**, lakukan DPIA untuk pemrosesan KYC/biometrik, dan verifikasi daftar prosesor sebelum publikasi.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Terakhir diperbarui:** 27 September 2026

## 1. Siapa kami

Pengendali Data Pribadi: **[NAMA BADAN USAHA — PT/CV, menunggu pendirian]** ("JastipKita", "kami"), [ALAMAT TERDAFTAR], NIB [NIB]. JastipKita adalah merek layanan yang merupakan bagian dari AntarKita Indonesia.

Pejabat Pelindungan Data Pribadi (DPO): **[NAMA/JABATAN DPO]** — [E-MAIL DPO] · [ALAMAT SURAT].

Kebijakan ini berlaku untuk aplikasi JastipKita, situs `antarkitaindonesia.com/jastipkita`, dan API kami.

## 2. Data yang kami proses

| Kategori | Contoh | Sumber |
|---|---|---|
| Identitas & kontak | nama, e-mail, nomor HP, foto profil, bahasa | Anda |
| Akun & autentikasi | ID akun, riwayat login, sesi, perangkat terdaftar, status verifikasi | Anda, sistem |
| **Data KYC — data pribadi spesifik** | jenis & nomor KTP/paspor, nama sesuai dokumen, foto dokumen, **selfie dan data liveness (data biometrik)** | Anda, penyedia verifikasi |
| **Data keuangan pribadi — data spesifik** | rekening payout Traveler (ditampilkan hanya dalam bentuk tersamar, mis. `****0961`), status pembayaran, refund, payout | Anda, mitra payment gateway |
| Transaksi | titipan, barang, harga, rincian biaya, bukti pembelian (struk, foto, nomor seri/video), konfirmasi harga, bukti bea cukai | Anda, pihak lawan transaksi |
| Perjalanan (Traveler) | rute, tanggal, kapasitas, dokumen perjalanan (tiket/boarding pass, data sensitif disamarkan) | Traveler |
| Serah terima | kota, alamat pengiriman, nomor resi, bukti serah terima | Anda, kurir |
| Komunikasi | chat antar pengguna, tiket bantuan, bukti dispute | Anda |
| Reputasi & risiko | Trust Score, rating, sinyal penipuan, keputusan risiko | sistem |
| Perangkat & log | alamat IP, jenis perangkat & sistem operasi, versi aplikasi, token notifikasi, log keamanan | sistem |
| Preferensi | persetujuan (versi & waktu), preferensi pemasaran, tema, bahasa | Anda |

Kami **tidak** menyimpan nomor kartu pembayaran; data kartu diproses langsung oleh mitra payment gateway berizin.

## 3. Tujuan dan dasar pemrosesan

Dasar pemrosesan mengacu pada Pasal 20 ayat (2) UU PDP.

| Tujuan | Dasar pemrosesan |
|---|---|
| Membuat dan mengelola akun, autentikasi OTP | pemenuhan perjanjian |
| Mempertemukan Penitip dan Traveler, menjalankan transaksi, SafePay, serah terima | pemenuhan perjanjian |
| Verifikasi identitas (KYC) termasuk pencocokan wajah & liveness | **persetujuan eksplisit terpisah** ([Persetujuan KYC](kyc-consent.md)) dan kewajiban hukum [LEGAL REVIEW: APU-PPT bila berlaku] |
| Menghitung estimasi bea & pajak, memeriksa barang terlarang | pemenuhan perjanjian; kepentingan yang sah |
| Pencegahan penipuan, keamanan akun, Trust Score, batas transaksi | kepentingan yang sah; kewajiban hukum |
| Penyelesaian dispute, refund, dan payout | pemenuhan perjanjian; kewajiban hukum |
| Pembukuan dan perpajakan | kewajiban hukum |
| Layanan pelanggan dan pengaduan | pemenuhan perjanjian; kewajiban hukum (perlindungan konsumen) |
| Pemberitahuan layanan (status transaksi, keamanan) | pemenuhan perjanjian |
| Pemasaran dan promosi | **persetujuan terpisah** ([Persetujuan Pemasaran](marketing-consent.md)), dapat ditarik kapan saja |
| Analitik produk (bila kelak diaktifkan) | persetujuan (lihat [Kebijakan Cookie](cookie-policy.md)) |

### 3.1 Keputusan otomatis

Trust Score, penilaian risiko transaksi (izinkan/tinjau/tahan/blokir), dan pemeriksaan liveness dijalankan secara otomatis. Anda berhak **mengajukan keberatan** dan meminta peninjauan oleh manusia atas keputusan yang semata-mata otomatis dan berdampak signifikan bagi Anda, melalui kanal pada Bagian 9.

## 4. Kepada siapa data dibagikan

Kami hanya membagikan data seperlunya:

| Penerima | Data | Tujuan |
|---|---|---|
| Pengguna lawan transaksi | nama depan + inisial, level verifikasi, Trust Score, rating; data serah terima yang diperlukan | menjalankan transaksi (data identitas KYC **tidak** dibagikan) |
| Mitra payment gateway berizin Bank Indonesia — [NAMA MITRA] | data pembayaran, jumlah, rekening payout | memproses pembayaran, refund, payout |
| Penyedia verifikasi identitas — [NAMA VENDOR KYC] | foto dokumen, selfie, data liveness | verifikasi KYC |
| Penyedia infrastruktur — [PENYEDIA CLOUD/HOSTING, DATABASE, OBJECT STORAGE] | data yang disimpan di sistem | hosting & penyimpanan terenkripsi |
| Penyedia komunikasi — [E-MAIL, SMS/WHATSAPP, PUSH NOTIFICATION] | kontak & isi pesan layanan | mengirim OTP & notifikasi |
| Penyedia ekstraksi produk berbasis AI (bila dipakai) — [NAMA] | tautan/foto produk | membaca detail produk (ditandai sebagai hasil AI) |
| Instansi berwenang | data sesuai permintaan sah | kewajiban hukum |

Semua prosesor terikat perjanjian pemrosesan data. **Kami tidak menjual data pribadi Anda.**

## 5. Transfer data ke luar negeri

Sebagian penyedia layanan dapat menyimpan atau memproses data di luar wilayah Indonesia ([LOKASI SERVER UTAMA & NEGARA PROSESOR]). Transfer dilakukan sesuai Pasal 56 UU PDP: ke negara dengan tingkat pelindungan setara atau lebih tinggi; atau dengan pelindungan yang memadai dan mengikat (mis. klausul kontrak standar); atau dengan persetujuan Anda. **[LEGAL REVIEW: pilih region Indonesia bila memungkinkan; dokumentasikan penilaian transfer sesuai PP 33/2026.]**

## 6. Berapa lama data disimpan

Data disimpan selama akun aktif dan setelahnya hanya selama diperlukan untuk tujuan atau kewajiban hukum. Durasi di bawah adalah **asumsi internal** yang sedang ditinjau:

| Data | Retensi | Setelahnya |
|---|---|---|
| Catatan keuangan (transaksi, pembayaran, refund, payout, buku besar) | 10 tahun sejak dibuat (kewajiban pembukuan) | dihapus |
| Identitas & dokumen KYC | 5 tahun setelah akun ditutup (praktik APU-PPT) | dihapus |
| Log audit | 10 tahun | dihapus setelah checkpoint integritas |
| Bukti rekonsiliasi pembayaran (webhook) | 5 tahun | dihapus |
| Pesan chat | 2 tahun setelah transaksi selesai (pesan yang menjadi bukti dispute ditahan) | dianonimkan |
| Alamat pengiriman | 90 hari setelah transaksi selesai | dianonimkan |
| Dokumen perjalanan Traveler | 180 hari setelah trip selesai | dihapus |
| Log keamanan | 12 bulan | dihapus |
| Notifikasi | 180 hari | dihapus |
| Data analitik (bila diaktifkan) | 13 bulan | dihapus |
| Kode OTP & sesi kedaluwarsa | 30 hari | dihapus |

Saat akun dihapus, profil dianonimkan setelah masa tenggang 14 hari; e-mail disimpan hanya dalam bentuk hash untuk mencegah penyalahgunaan pendaftaran ulang.

## 7. Keamanan

Kami menerapkan langkah teknis dan organisasi yang wajar, antara lain: enkripsi saat transit (TLS); file KYC disimpan terenkripsi (envelope AES-256-GCM) di object storage dengan basis data hanya menyimpan referensi dan hash; rekening payout ditampilkan tersamar; kontrol akses berbasis peran dengan persetujuan berlapis (maker-checker) untuk tindakan keuangan; log audit append-only berantai hash; dan pembatasan percobaan OTP/PIN. Tidak ada sistem yang sepenuhnya bebas risiko.

## 8. Hak Anda

Sesuai Pasal 5–13 UU PDP, Anda berhak:

1. memperoleh informasi tentang pemrosesan data Anda;
2. **mengakses** dan memperoleh salinan data Anda;
3. **memperbaiki** data yang tidak akurat;
4. **menghapus** data dan mengakhiri pemrosesan (lihat [Hapus akun](/jastipkita/hapus-akun/));
5. **menarik persetujuan** yang pernah diberikan (penarikan tidak memengaruhi pemrosesan sebelumnya dan dapat membatasi fitur, mis. transaksi yang memerlukan KYC);
6. **mengajukan keberatan** atas keputusan yang semata-mata otomatis;
7. **menunda atau membatasi** pemrosesan secara proporsional;
8. memperoleh dan/atau memindahkan data dalam format yang umum dipakai;
9. menggugat dan menerima ganti rugi atas pelanggaran pemrosesan data sesuai peraturan.

## 9. Cara menggunakan hak Anda

- Di aplikasi: **Profil → Keamanan & privasi** (unduh data, hapus akun, kelola persetujuan).
- Di web: [halaman Akun](/jastipkita/akun/) setelah masuk.
- E-mail DPO: [E-MAIL DPO] — dari e-mail/nomor HP terdaftar; kami dapat meminta verifikasi identitas.

Kami menanggapi permintaan akses dan perbaikan paling lambat **3 × 24 jam** sejak permintaan lengkap diterima (Pasal 30 & 32 UU PDP), dan permintaan lain dalam tenggat yang diatur peraturan. Permintaan dapat ditolak bila bertentangan dengan kewajiban hukum (mis. retensi catatan keuangan), dengan alasan tertulis.

## 10. Pemberitahuan kegagalan pelindungan data

Bila terjadi kegagalan pelindungan data pribadi, kami memberi tahu Anda dan lembaga penyelenggara pelindungan data pribadi secara tertulis paling lambat **3 × 24 jam** (Pasal 46 UU PDP), memuat data yang terdampak, waktu dan cara terjadinya, serta upaya penanganan dan pemulihan.

## 11. Anak

Layanan ditujukan bagi pengguna berusia 18 tahun ke atas atau yang cakap hukum. Kami tidak dengan sengaja memproses data anak; bila kami mengetahuinya, akun akan ditangguhkan dan data dihapus sesuai ketentuan. **[LEGAL REVIEW]**

## 12. Cookie dan penyimpanan lokal

Situs hanya memakai penyimpanan yang benar-benar diperlukan; tidak ada pelacak pihak ketiga yang terpasang. Detail di [Kebijakan Cookie](cookie-policy.md).

## 13. Perubahan kebijakan

Perubahan material diberitahukan melalui aplikasi/e-mail sebelum berlaku. Bila perubahan memerlukan persetujuan baru, kami akan memintanya secara terpisah.

## 14. Kontak

DPO: [E-MAIL DPO] · Layanan pelanggan: [NOMOR WHATSAPP CS] · Alamat: [ALAMAT TERDAFTAR]
$jk_legal$,
        'Versi template awal dari docs/legal/privacy-policy.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('PROHIBITED_ITEMS', '0.1-template', 'id', $jk_legal$Kebijakan Barang Terlarang & Terbatas$jk_legal$, $jk_legal$Barang yang tidak boleh dititipkan, barang yang dibatasi, dan barang yang wajib dideklarasikan atau memerlukan izin, beserta dasar aturannya.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Tabel pada Bagian 3 dihasilkan dari `db/seeds/0101_restricted_items.sql` (aturan diverifikasi 2026-09-27 oleh tim riset; **belum ditinjau ahli kepabeanan/konsultan hukum**). Aturan berstatus DRAFT belum diterapkan otomatis di checkout. Daftar ini dapat berubah; versi aturan yang dipakai pada setiap titipan dicatat di transaksi.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Penyelenggara:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian]

## 1. Prinsip

1. **Barang titipan bukan barang pribadi Traveler.** Menurut Direktorat Jenderal Bea dan Cukai (pernyataan 2 Mei 2024) dan PMK 34 Tahun 2025, barang jastip tidak dikecualikan dari ketentuan larangan dan/atau pembatasan impor (lartas) dan dikenai bea & pajak atas nilai penuh.
2. JastipKita memeriksa setiap titipan terhadap daftar di bawah **sebelum** estimasi harga dan pembayaran. Klasifikasi paling berat yang berlaku: **PROHIBITED › PERMIT_REQUIRED › RESTRICTED › DECLARATION_REQUIRED › ALLOWED**.
3. Melampaui batas jumlah atau nilai pada suatu aturan membuat barang diperlakukan sebagai **PROHIBITED**.
4. Pemeriksaan otomatis adalah alat bantu. **Keputusan akhir ada pada Bea dan Cukai, Badan Karantina Indonesia, BPOM, dan instansi terkait.** Pengguna tetap wajib memastikan barangnya sesuai aturan.
5. JastipKita tidak akan pernah memberi "tips lolos bea cukai", menyarankan barang dipecah (*splitting*), atau menyamarkan titipan sebagai barang pribadi.

## 2. Arti klasifikasi

| Klasifikasi | Arti | Tindakan di aplikasi |
|---|---|---|
| **PROHIBITED** | Dilarang dititipkan melalui JastipKita (dilarang hukum, kebijakan platform, atau aturan penerbangan) | Checkout diblokir |
| **PERMIT_REQUIRED** | Membutuhkan izin/rekomendasi instansi (mis. BPOM, Polri, Karantina, Komdigi) | Persetujuan risiko wajib; bukti izin dapat diminta |
| **RESTRICTED** | Boleh dengan batas jumlah/kondisi tertentu (mis. BPOM, bagasi) | Persetujuan risiko wajib sebelum membayar |
| **DECLARATION_REQUIRED** | Wajib dideklarasikan/didaftarkan (mis. registrasi IMEI) | Persetujuan wajib; Traveler wajib deklarasi |
| **ALLOWED** | Tidak ada aturan khusus yang cocok | Tetap wajib deklarasi sebagai barang bukan pribadi |

## 3. Daftar aturan

### 3.1 Dilarang (PROHIBITED) — checkout diblokir

| Kode | Cakupan | Ketentuan | Batas | Dasar |
|---|---|---|---|---|
| `RI_ID_NARCOTICS_PSYCHOTROPICS` | kata kunci: narkotika, narkoba, ganja, marijuana, marihuana, cannabis, cbd, cbd oil … | Narkotika, psikotropika, produk ganja/CBD/THC, dan obat yang mengandung kodein/amfetamin dilarang dibawa masuk ke Indonesia. Sanksi pidana berat. | — | UU 35/2009 tentang Narkotika; UU 5/1997 tentang Psikotropika; Per BPOM 28/2023 (narkotika tidak diizinkan; psikotropika hanya WNA dengan resep maks. 90 hari). |
| `RI_ID_ALCOHOL_CATEGORY` | kategori Minuman Beralkohol | Minuman beralkohol tidak dapat dititipkan. Pembebasan cukai 1 liter hanya untuk konsumsi pribadi orang dewasa; kelebihan dimusnahkan Bea Cukai. Maskapai: >24% ABV maks. 5 L, >70% ABV dilarang. | DG penerbangan | PMK 82/2024 (pembebasan cukai penumpang: MMEA 1 liter/orang dewasa); PMK 34/2025 Pasal 13 (kelebihan dimusnahkan); kebijakan platform (barang kena cukai non-pribadi). |
| `RI_ID_TOBACCO_VAPE_CATEGORY` | kategori Rokok, Cerutu & Vape | Rokok, cerutu, tembakau, dan rokok elektrik/liquid tidak dapat dititipkan. Pembebasan cukai (mis. 200 batang sigaret, 30 ml liquid sistem terbuka) hanya untuk konsumsi pribadi. Vape wajib di kabin, tidak boleh di bagasi. | DG penerbangan | PMK 82/2024 (batas BKC penumpang); PMK 34/2025 Pasal 13; IATA DGR 67 Tabel 2.3.A (e-cigarettes). |
| `RI_ID_WEAPONS_CATEGORY` | kategori Senjata & Replika | Senjata api, airsoft/air gun, replika senjata, dan amunisi tidak dapat dititipkan. Impor memerlukan izin Polri. | DG penerbangan | UU Darurat 12/1951; Perpol 1/2022 (perizinan senjata api & peralatan yang digolongkan senjata api); IATA DGR (amunisi = barang berbahaya). |
| `RI_ID_FIREARMS_KEYWORD` | kata kunci: senjata api, firearm, handgun, senapan angin, airsoft, airsoft gun, airgun, gas blowback … | Senjata api, airsoft/air gun, replika senjata, dan amunisi tidak dapat dititipkan. | DG penerbangan | UU Darurat 12/1951; Perpol 1/2022; IATA DGR. |
| `RI_ID_SELF_DEFENSE_DEVICES` | kata kunci: pepper spray, semprotan merica, bear spray, stun gun, taser, setrum kejut, alat kejut listrik, tongkat listrik | Semprotan merica, stun gun/taser, dan alat pelumpuh lain dilarang di kabin maupun bagasi pesawat. | DG penerbangan | IATA passenger guidance (disabling devices forbidden in carry-on and checked baggage); kebijakan platform. |
| `RI_ID_PORNOGRAPHY` | kata kunci: pornografi, pornography, porn, hentai, film dewasa, adult video, majalah dewasa, adult magazine … | Barang bermuatan pornografi dilarang diimpor ke Indonesia. | — | UU 44/2008 tentang Pornografi Pasal 4 ayat (1) (dikutip akun resmi Bravo Bea Cukai; diverifikasi via hasil pencarian). |
| `RI_ID_SEX_TOYS` | kata kunci: sex toy, sex toys, alat bantu seks, dildo, fleshlight, onahole, masturbator | Alat bantu seks termasuk barang yang lazim ditegah Bea Cukai (UU Pornografi) dan tidak dapat dititipkan. | — | UU 44/2008 Pasal 4 ayat (1); penindakan BC Kualanamu 2020 (sex toys paling dominan) — diverifikasi via hasil pencarian. |
| `RI_ID_CASH_CATEGORY` | kategori Uang Tunai & Surat Berharga | JastipKita tidak melayani titipan uang tunai, valas, cek, atau surat berharga (bukan layanan transfer dana). Traveler wajib melapor ke Bea Cukai bila membawa uang/instrumen pembayaran senilai >= Rp100 juta; uang kertas asing >= Rp1 miliar hanya boleh dibawa badan berizin BI. | — | PMK 157/PMK.04/2017 jo PMK 100/2018 (deklarasi >= Rp100 juta; sanksi 10% maks. Rp300 juta); PBI 20/2/PBI/2018 (UKA >= Rp1 miliar); kebijakan platform. |
| `RI_ID_LIVE_ANIMALS` | kata kunci: hewan hidup, live animal, kitten, puppy, anak kucing, anak anjing, ikan hias hidup, live fish … | Hewan hidup tidak dapat dititipkan (wajib karantina, sertifikat kesehatan, dan izin maskapai). | — | UU 21/2019 tentang Karantina Hewan, Ikan, dan Tumbuhan; kebijakan platform. |
| `RI_ID_USED_CLOTHING_HS` | seluruh rute | Pakaian bekas dan barang bekas sejenis dilarang diimpor ke Indonesia. | — | Permendag 47/2025 tentang Barang yang Dilarang untuk Diimpor Pasal 2 (kantong bekas, karung bekas, pakaian bekas); mencabut Permendag 18/2021 jo 40/2022; berlaku 01-01-2026. |
| `RI_ID_USED_CLOTHING_KEYWORD` | kata kunci: pakaian bekas, baju bekas, used clothing, second hand clothing, secondhand clothing, karung bekas, kantong bekas, bal pakaian bekas | Pakaian bekas, kantong bekas, dan karung bekas dilarang diimpor ke Indonesia. | — | Permendag 47/2025 Pasal 2. |
| `RI_ID_USED_APPAREL` | kategori Pakaian; kata kunci: preloved, bekas, second hand, secondhand, used, thrift, thrifting, worn | Pakaian bekas/preloved dilarang diimpor ke Indonesia. Hanya pakaian baru yang dapat dititipkan. | — | Permendag 47/2025 Pasal 2 (pakaian bekas). |
| `RI_ID_COUNTERFEIT` | kata kunci: barang palsu, counterfeit, kw super, barang kw, tas kw, sepatu kw, jam kw, super copy … | Barang palsu/tiruan merek tidak dapat dititipkan dan dapat disita. | — | UU 20/2016 tentang Merek dan Indikasi Geografis; kebijakan platform (URL sumber belum diverifikasi). |
| `RI_ID_SIGNAL_JAMMER` | kata kunci: jammer, signal jammer, gps jammer, pengacak sinyal | Pengacak sinyal (jammer) tidak dapat dititipkan. | — | Kebijakan platform; dasar hukum spesifik (UU 36/1999 tentang Telekomunikasi — larangan gangguan) NEEDS_VERIFICATION. |
| `RI_ID_LARGE_LITHIUM` | kata kunci: power station, portable power station, hoverboard, electric scooter, skuter listrik, otopet listrik, sepeda listrik, e bike … | Power station portabel, hoverboard, skuter/sepeda listrik umumnya memakai baterai >160 Wh yang dilarang di pesawat penumpang. | DG penerbangan | IATA DGR 67th ed. Tabel 2.3.A (>160 Wh terlarang); FAA PackSafe. |
| `RI_ID_FLAMMABLES_EXPLOSIVES` | kata kunci: spray paint, cat semprot, pilox, pilok, lighter fluid, gas butana, butane, gas korek … | Bahan mudah terbakar, gas, bahan bakar, dan kembang api/bahan peledak dilarang di pesawat penumpang. | DG penerbangan | IATA DGR 67th ed. Tabel 2.3.A (lighter fuel & refills forbidden); IATA passenger guidance. |

### 3.2 Butuh izin (PERMIT_REQUIRED)

| Kode | Cakupan | Ketentuan | Batas | Dasar |
|---|---|---|---|---|
| `RI_ID_MEDICINE_PRESCRIPTION` | kata kunci: obat resep, prescription drug, prescription medicine, ozempic, wegovy, semaglutide, mounjaro, zepbound … | Obat keras/resep (termasuk injeksi GLP-1 seperti Ozempic/Mounjaro, antibiotik, isotretinoin, tretinoin, botox/filler) memerlukan resep dokter dan izin BPOM. Titip beli untuk orang lain berisiko disita. | — | Per BPOM 28/2023 (obat sesuai resep maks. 90 hari pengobatan; penggunaan pribadi); kebijakan platform. |
| `RI_ID_BLADES_SWORDS` | kata kunci: katana, samurai sword, wakizashi, tanto, pedang, belati, dagger, bayonet … | Senjata tajam (pedang/katana/belati) tidak boleh dimasukkan tanpa hak. Hanya replika tumpul/mainan atau barang yang jelas untuk keperluan sah yang dapat diproses setelah review admin. | — | UU Darurat 12/1951 Pasal 2 (senjata penikam/penusuk; pengecualian untuk pertanian, rumah tangga, pekerjaan sah, pusaka/barang kuno). |
| `RI_ID_WILDLIFE_CITES` | kata kunci: gading, ivory, kulit ular, python leather, snakeskin, kulit buaya, crocodile leather, alligator leather … | Produk dari satwa/tumbuhan dilindungi atau CITES (gading, kulit buaya/ular/biawak, penyu, karang) wajib dokumen CITES dari negara asal dan izin Indonesia. Tanpa dokumen, barang disita. | — | UU 5/1990 jo UU 32/2024 tentang Konservasi Sumber Daya Alam Hayati dan Ekosistemnya; CITES. |
| `RI_ID_ANIMAL_PRODUCTS_CATEGORY` | kategori Hewan & Produk Hewan | Hewan dan produk hewan wajib dilaporkan ke karantina (All Indonesia) dan disertai sertifikat kesehatan dari negara asal; tanpa dokumen dapat ditolak atau dimusnahkan. | — | UU 21/2019; Badan Karantina Indonesia (berita 06-04-2026). |
| `RI_ID_ANIMAL_PRODUCTS_KEYWORD` | kata kunci: daging, meat, wagyu, beef jerky, dendeng, sosis, sausage, ham … | Daging, olahan daging, telur mentah, susu segar, dan sarang burung walet adalah media pembawa karantina; wajib dokumen karantina negara asal. | — | UU 21/2019; Badan Karantina Indonesia (berita 06-04-2026). |
| `RI_ID_PLANTS_SEEDS_CATEGORY` | kategori Tanaman & Benih | Tanaman, benih, bibit, buah & sayur segar wajib sertifikat fitosanitari negara asal dan dilaporkan ke karantina; tanpa dokumen dapat dimusnahkan. | — | UU 21/2019 tentang Karantina Hewan, Ikan, dan Tumbuhan; Badan Karantina Indonesia. |
| `RI_ID_PLANTS_KEYWORD` | kata kunci: benih, bibit, seeds, biji tanaman, umbi, tanaman hidup, live plant, bonsai … | Nama barang mengindikasikan tanaman/benih/buah segar yang diawasi karantina. | — | UU 21/2019; Badan Karantina Indonesia. |
| `RI_ID_DRONES` | kata kunci: drone, dji mini, dji mavic, dji air, dji avata, dji neo, dji flip, quadcopter … | Drone wajib dideklarasikan, memerlukan sertifikasi perangkat (SDPPI) dan registrasi/izin operasi Kemenhub. Baterai cadangan hanya di kabin. | DG penerbangan | Permenkominfo 16/2018 (sertifikasi alat/perangkat telekomunikasi); PM Perhubungan 37/2020 (pengoperasian pesawat udara tanpa awak); IATA DGR (baterai). Sumber sekunder: drone.co.id (2022). |
| `RI_ID_RADIO_DEVICES` | kata kunci: walkie talkie, handy talky, radio ht, transceiver, ham radio, baofeng, starlink, radio pemancar | Perangkat pemancar radio (HT/walkie talkie, transceiver, terminal satelit) wajib bersertifikat SDPPI sebelum digunakan/diedarkan di Indonesia. | — | Permenkominfo 16/2018 tentang Ketentuan Operasional Sertifikasi Alat dan/atau Perangkat Telekomunikasi. |

### 3.3 Terbatas (RESTRICTED)

| Kode | Cakupan | Ketentuan | Batas | Dasar |
|---|---|---|---|---|
| `RI_ID_MEDICINE_CATEGORY` | kategori Obat | Obat hanya untuk penggunaan pribadi: maks. 30 pcs per jenis (tablet/kapsul) atau 3 pcs per jenis (cair/aerosol) tanpa resep. Barang titipan dianggap bukan barang pribadi traveler dan dapat ditahan Bea Cukai/BPOM. | maks. 30 | Per BPOM 28/2023 (mengubah Per BPOM 27/2022) — batas barang bawaan pribadi; DJBC 02-05-2024: barang jastip tidak dikecualikan dari lartas. |
| `RI_ID_SUPPLEMENTS_CATEGORY` | kategori Suplemen & Vitamin | Suplemen & obat tradisional: maks. 5 pcs per jenis per penumpang untuk penggunaan pribadi. Jumlah komersial memerlukan izin edar BPOM. | maks. 5 | Per BPOM 28/2023 — batas barang bawaan pribadi (5 pcs/jenis). |
| `RI_ID_COSMETICS_CATEGORY` | kategori Kosmetik & Skincare | Kosmetik & skincare: maks. 20 pcs per penumpang untuk penggunaan pribadi (total semua jenis per traveler per kedatangan). Jumlah komersial memerlukan notifikasi BPOM. | maks. 20 | Per BPOM 28/2023 — batas barang bawaan pribadi (20 pcs); DJBC 02-05-2024 (jastip tidak dikecualikan dari lartas). |
| `RI_ID_PERFUME_CATEGORY` | kategori Parfum | Parfum termasuk kosmetik (maks. 20 pcs per penumpang). Aturan maskapai: toiletries maks. 0,5 L per wadah dan total 2 L/2 kg per orang; di kabin maks. 100 ml per wadah. | maks. 20, DG penerbangan | Per BPOM 28/2023; IATA DGR 67 Tabel 2.3.A (medicinal/toilet articles). |
| `RI_ID_FOOD_CATEGORY` | kategori Makanan & Camilan | Pangan olahan untuk penggunaan pribadi maks. 5 kg per penumpang. Produk berbahan daging/susu/tumbuhan segar dapat memerlukan dokumen karantina. | — | Per BPOM 28/2023 (pangan olahan 5 kg/penumpang); UU 21/2019 tentang Karantina Hewan, Ikan, dan Tumbuhan. |
| `RI_ID_BEVERAGES_CATEGORY` | kategori Minuman Non-Alkohol | Minuman (pangan olahan) untuk penggunaan pribadi dalam jumlah wajar (bagian dari batas 5 kg). Cairan di kabin maks. 100 ml per wadah — bawa di bagasi tercatat. | — | Per BPOM 28/2023 (pangan olahan); aturan keamanan kabin maskapai. |
| `RI_ID_INFANT_FORMULA` | kata kunci: susu formula, infant formula, formula milk, susu bayi, baby formula | Susu formula bayi termasuk pangan olahan yang diawasi BPOM; hanya jumlah wajar untuk penggunaan pribadi. | — | Per BPOM 28/2023 (pangan olahan). |
| `RI_ID_ALCOHOL_KEYWORD` | kata kunci: minuman beralkohol, alcoholic beverage, sake, soju, makgeolli, umeshu, shochu, whisky … | Nama barang mengindikasikan minuman beralkohol. Jika benar beralkohol, pilih kategori Minuman Beralkohol (tidak dapat diproses). Jika bukan, lanjutkan dengan konfirmasi. | DG penerbangan | PMK 82/2024; kebijakan platform (jaring pengaman kategori). |
| `RI_ID_TOBACCO_VAPE_KEYWORD` | kata kunci: rokok, cigarette, cigarettes, cerutu, cigar, tembakau, tobacco, vape … | Nama barang mengindikasikan produk tembakau/vape. Jika benar, pilih kategori Rokok, Cerutu & Vape (tidak dapat diproses). | DG penerbangan | PMK 82/2024; kebijakan platform (jaring pengaman kategori). |
| `RI_ID_KNIVES` | kata kunci: pisau, knife, kitchen knife, pisau dapur, santoku, gyuto, pisau lipat, pocket knife | Pisau dapur/rumah tangga boleh, hanya di bagasi tercatat (dilarang di kabin). Pisau lipat/taktis dapat dianggap senjata tajam. | — | UU Darurat 12/1951 Pasal 2 (pengecualian pekerjaan rumah tangga); aturan keamanan kabin maskapai. |
| `RI_ID_CASH_KEYWORD` | kata kunci: uang tunai, uang kertas asing, valas, foreign currency, banknote, banknotes, traveler cheque, travellers cheque … | Nama barang mengindikasikan uang/valas. Titipan uang tidak dilayani; uang koleksi (numismatik) hanya setelah review admin. | — | PMK 157/PMK.04/2017 jo PMK 100/2018; PBI 20/2/PBI/2018; kebijakan platform. |
| `RI_ID_POWERBANK_CATEGORY` | kategori Baterai & Power Bank | Power bank & baterai cadangan hanya di kabin (dilarang di bagasi). <=100 Wh: maks. 20 unit per orang (IATA; maskapai sering lebih ketat, mis. 2 unit). 100-160 Wh: izin maskapai, maks. 2. >160 Wh: dilarang. | maks. 20, DG penerbangan | IATA DGR 67th ed. Tabel 2.3.A; FAA PackSafe (diperbarui 10-08-2026). |
| `RI_ID_POWERBANK_KEYWORD` | kata kunci: power bank, powerbank, portable charger, battery pack, baterai cadangan, spare battery, baterai lithium, lithium battery … | Baterai lithium cadangan/power bank hanya di kabin; batas Wh dan jumlah mengikuti IATA & maskapai. | maks. 20, DG penerbangan | IATA DGR 67th ed. Tabel 2.3.A; FAA PackSafe. |
| `RI_ID_AEROSOLS_CATEGORY` | kategori Aerosol & Bahan Mudah Terbakar | Aerosol toiletries (non-mudah terbakar): maks. 0,5 kg/0,5 L per wadah dan total 2 kg/2 L per orang. Aerosol non-toiletries yang mudah terbakar (cat semprot, gas) dilarang. | DG penerbangan | IATA DGR 67th ed. Tabel 2.3.A (medicinal/toilet articles & Division 2.2 aerosols). |

### 3.4 Wajib deklarasi (DECLARATION_REQUIRED)

| Kode | Cakupan | Ketentuan | Batas | Dasar |
|---|---|---|---|---|
| `RI_ID_MOBILE_PHONES_CATEGORY` | kategori Ponsel | Ponsel wajib dideklarasikan dan IMEI didaftarkan atas paspor traveler (maks. 2 unit per penumpang per kedatangan, termasuk ponsel pribadi traveler), di bandara atau maks. 60 hari setelah tiba. Bea & pajak impor dibayar saat registrasi. | maks. 2 | PER-13/BC/2021 jo PER-7/BC/2023; Permenkominfo 1/2020 (IMEI); deklarasi HKT via All Indonesia. |
| `RI_ID_HKT_KEYWORD` | kata kunci: smartphone, handphone, ponsel, telepon seluler, mobile phone, ipad cellular, tablet lte, tablet 5g … | Perangkat seluler (ponsel, tablet seluler, modem/MiFi) wajib registrasi IMEI atas paspor traveler, maks. 2 unit per penumpang per kedatangan. | — | PER-13/BC/2021 jo PER-7/BC/2023; Permenkominfo 1/2020. |

### 3.5 Dalam kajian (DRAFT — belum berlaku otomatis)

| Kode | Cakupan | Klasifikasi kandidat | Ketentuan | Catatan verifikasi |
|---|---|---|---|---|
| `RI_ID_HONEY_DAIRY` | kata kunci: madu, honey, manuka, keju, cheese, butter, mentega, yogurt | PERMIT_REQUIRED | Madu dan produk susu dapat termasuk produk hewan yang diawasi karantina. | NEEDS_VERIFICATION: apakah madu/keju/mentega kemasan ritel untuk jastip wajib sertifikat karantina (UU 21/2019) atau cukup pemeriksaan; risiko false-positive tinggi (mis. snack rasa keju/madu). |
| `RI_ID_USED_FOOTWEAR` | kategori Sepatu; kata kunci: preloved, bekas, second hand, secondhand, used, worn | PROHIBITED | Sepatu bekas kemungkinan termasuk barang bekas yang dilarang impor. | NEEDS_VERIFICATION: cakupan HS larangan Permendag 47/2025 (apakah HS 6309 "worn clothing and other worn articles" termasuk alas kaki bekas yang diklasifikasikan di bab 64). |
| `RI_ID_RICE_SUGAR` | kata kunci: beras, beras jepang, japanese rice, koshihikari, gula pasir, granulated sugar | PROHIBITED | Beras dan gula tertentu termasuk barang yang dilarang diimpor. | NEEDS_VERIFICATION: Permendag 47/2025 Pasal 2 mencantumkan gula dan beras — pos tarif (HS) yang dilarang dan penerapannya pada barang bawaan penumpang non-pribadi belum dikonfirmasi. |
| `RI_ID_GAMBLING_DEVICES` | kata kunci: mesin judi, slot machine, mesin slot, pachislot, pachislo, pachinko machine, mesin pachinko | PROHIBITED | Mesin/alat perjudian tidak dapat dititipkan. | NEEDS_VERIFICATION: perjudian dilarang KUHP; status larangan/pembatasan impor mesin judi untuk barang penumpang belum dikonfirmasi dari sumber primer. |
| `RI_JP_TAXFREE_NOT_FOR_RESALE` | rute JP | RESTRICTED | Fasilitas tax-free/refund pajak konsumsi Jepang hanya untuk barang pribadi wisatawan, bukan untuk dijual kembali. Barang titipan harus dibeli dengan harga termasuk pajak konsumsi; mulai 1 Nov 2026 sistem berubah menjadi refund saat keberangkatan. | NEEDS_VERIFICATION: sumber sekunder (japan-guide.com); perlu konfirmasi dari National Tax Agency/Japan Tourism Agency. Rule tingkat rute (berlaku untuk semua item JP) — pertimbangkan sebagai catatan harga, bukan acknowledgement. |

## 4. Ketentuan penerbangan

Selain aturan impor, Traveler wajib mematuhi aturan barang berbahaya (IATA Dangerous Goods) dan kebijakan maskapai, misalnya power bank dan baterai cadangan hanya di kabin dengan batas kapasitas, aerosol dan cairan mudah terbakar dibatasi, serta pisau hanya di bagasi tercatat. Maskapai berhak menolak barang.

## 5. Pelanggaran

Menitipkan atau membawa barang terlarang, menyamarkan deskripsi barang, atau memberikan keterangan palsu kepada petugas adalah pelanggaran berat: transaksi dapat dibatalkan, dana ditahan untuk penyelesaian sengketa, akun ditangguhkan atau ditutup, dan pelanggaran dilaporkan kepada pihak berwenang bila diwajibkan hukum.

## 6. Pelaporan

Temukan barang terlarang di Platform? Laporkan melalui menu **Laporkan** di aplikasi atau [E-MAIL CS].
$jk_legal$,
        'Versi template awal dari docs/legal/prohibited-items-policy.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('REFUND_POLICY', '0.1-template', 'id', $jk_legal$Kebijakan Pembatalan & Refund$jk_legal$, $jk_legal$Kapan titipan bisa dibatalkan, berapa dana yang kembali di setiap tahap, dan bagaimana hasil dispute diselesaikan.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Matriks di bawah **mencerminkan persis** `cancellation.matrix` di `packages/core/src/config/business-config.defaults.json` (versi konfigurasi 1) dan status dispute di `docs/00-domain-model.md` §6. Bila konfigurasi diubah dari Admin, dokumen ini wajib diperbarui dengan versi baru.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Penyelenggara:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian]

## 1. Prinsip

1. Dana Penitip ditahan SafePay sampai transaksi selesai, sehingga pengembalian dana (refund) dihitung **per baris Rincian Biaya**.
2. Pihak yang tidak bersalah tidak menanggung biaya. Contoh: Penitip yang menolak kenaikan harga menerima refund penuh termasuk biaya pembayaran.
3. Pajak dan bea yang **belum** dibayarkan ke negara dikembalikan sesuai matriks. Bea & pajak yang **sudah** dibayar Traveler kepada Bea Cukai tidak dapat ditarik kembali dan diperhitungkan dalam penyelesaian.
4. Setelah barang dibeli, Penitip tidak dapat membatalkan sepihak; gunakan **Dispute Center**.

## 2. Matriks pembatalan

Persentase = bagian dari baris yang dikembalikan kepada Penitip. "Penalti" = pengurangan Trust Score pihak yang membatalkan.

| Tahap | Pembatal | Boleh? | Dana dikembalikan ke penitip | Kompensasi traveler | Penalti Trust Score | Catatan |
|---|---|---|---|---|---|---|
| Sebelum match | Siapa pun | Ya | Belum ada dana yang dibayar | — | — | — |
| Setelah match, belum bayar | Penitip | Ya | Belum ada dana yang dibayar | — | 1 | — |
| Setelah match, belum bayar | Traveler | Ya | Belum ada dana yang dibayar | — | 2 | — |
| Pembayaran aman (PAYMENT SECURED / konfirmasi harga) | Penitip (tolak kenaikan harga) | Ya | 100% semua baris | — | — | Penitip menolak kenaikan harga — bukan kesalahan penitip |
| Pembayaran aman (PAYMENT SECURED / konfirmasi harga) | Penitip | Ya | 100%: Barang, Fee traveler, Bea, Pajak impor, Protection, Platform fee, PPN layanan; tidak dikembalikan: Biaya pembayaran | — | 2 | — |
| Pembayaran aman (PAYMENT SECURED / konfirmasi harga) | Traveler | Ya | 100% semua baris | — | 5 | — |
| Pembayaran aman (PAYMENT SECURED / konfirmasi harga) | Sistem | Ya | 100% semua baris | — | — | Konfirmasi harga kedaluwarsa / pembatalan sistem |
| Pembayaran aman (PAYMENT SECURED / konfirmasi harga) | Admin JastipKita | Ya | 100% semua baris | — | — | Wajib persetujuan admin |
| Pembelian disetujui, barang belum dibeli | Penitip | Ya | 100%: Barang, Bea, Pajak impor, Protection; Fee traveler 90%, Platform fee 50%, PPN layanan 50%; tidak dikembalikan: Biaya pembayaran | 10% fee traveler (min. Rp10.000) | 3 | — |
| Pembelian disetujui, barang belum dibeli | Traveler | Ya | 100% semua baris | — | 8 | — |
| Pembelian disetujui, barang belum dibeli | Sistem | Ya | 100% semua baris | — | — | — |
| Pembelian disetujui, barang belum dibeli | Admin JastipKita | Ya | 100% semua baris | — | — | Wajib persetujuan admin |
| Barang sudah dibeli | Penitip | Tidak | — | — | — | Barang sudah dibeli; gunakan Dispute Center |
| Barang sudah dibeli | Traveler | Ya | 100% semua baris | — | 15 | Wajib persetujuan admin; barang tetap tanggung jawab Traveler |
| Barang sudah dibeli | Admin JastipKita | Ya | 100% semua baris | — | — | Wajib persetujuan admin |
| Dalam perjalanan | Penitip | Tidak | — | — | — | Barang dalam perjalanan; gunakan Dispute Center |
| Dalam perjalanan | Admin JastipKita | Ya | 100% semua baris | — | — | Wajib persetujuan admin |
| Sudah tiba / proses serah terima | Penitip | Tidak | — | — | — | Barang sudah tiba; gunakan Dispute Center |
| Sudah tiba / proses serah terima | Admin JastipKita | Ya | 100%: Barang, Protection, Platform fee, PPN layanan; tidak dikembalikan: Fee traveler, Bea, Pajak impor, Biaya pembayaran | 100% fee traveler | — | Wajib persetujuan admin |

Penjelasan tahap: *Setelah match, belum bayar* mencakup status MATCHED dan AWAITING_PAYMENT; *Pembayaran aman* mencakup PAYMENT_SECURED dan PRICE_CHANGE_PENDING; *Pembelian disetujui* = PURCHASE_APPROVED; *Sudah tiba* mencakup ARRIVED, CUSTOMS_PROCESS, READY_FOR_HANDOVER, OUT_FOR_DELIVERY, dan DELIVERED.

## 3. Promo dan JastipKita Credit saat refund

1. Nilai yang dikembalikan tidak melebihi uang yang benar-benar Anda bayarkan.
2. Bila sebagian biaya tidak dikembalikan, potongan promo/credit dipakai terlebih dahulu untuk menutup bagian yang ditahan; sisa JastipKita Credit dikembalikan ke saldo Credit Anda (dengan tanggal kedaluwarsa semula), dan sisa diskon promo dibatalkan.

## 4. Dispute

1. **Jenis**: barang tidak diterima, barang salah, barang rusak, barang palsu, sengketa harga, sengketa serah terima, lainnya.
2. **Tenggat**: dibuka paling lambat 72 jam setelah status DELIVERED; bukti dari kedua pihak dalam 72 jam; target keputusan 120 jam setelah bukti lengkap; banding satu kali dalam 72 jam setelah keputusan.
3. **Hasil yang mungkin**:

| Hasil | Arti |
|---|---|
| REFUND_FULL | Seluruh dana yang dibayar Penitip dikembalikan (dikurangi bea/pajak yang sudah dibayar ke negara bila barang tertahan karena kesalahan Penitip — **[LEGAL REVIEW]**). |
| REFUND_PARTIAL | Sebagian dana dikembalikan per baris; sisanya diteruskan kepada Traveler. |
| RETURN_AND_REFUND | Barang dikembalikan kepada Traveler sesuai instruksi, lalu refund diproses. |
| NO_REFUND | Klaim tidak terbukti; dana diteruskan kepada Traveler. |
| OTHER | Penyelesaian lain yang disepakati dan dicatat. |

4. Selama dispute terbuka, payout Traveler untuk transaksi tersebut ditahan.

## 5. Proses dan waktu refund

1. Refund dikirim ke metode pembayaran asal melalui mitra payment gateway, atau melalui transfer bank bila metode asal tidak mendukung refund.
2. Refund di atas batas persetujuan otomatis (saat ini Rp10.000.000) memerlukan persetujuan dua petugas keuangan (maker-checker).
3. Waktu dana diterima bergantung pada bank/penyedia metode pembayaran: **[FINANCE: SLA per kanal setelah kontrak mitra]**.
4. Refund yang gagal diproses ulang otomatis hingga 3 kali, lalu ditangani tim secara manual.

## 6. Kontak

[E-MAIL CS] · [NOMOR WHATSAPP CS] · Dispute Center di aplikasi.
$jk_legal$,
        'Versi template awal dari docs/legal/refund-policy.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('TOS', '0.1-template', 'id', $jk_legal$Syarat & Ketentuan Penggunaan$jk_legal$, $jk_legal$Ketentuan yang mengatur penggunaan platform JastipKita oleh Penitip dan Traveler.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Rancangan kerja yang disusun dari riset internal (`docs/research/05-legal-regulatory.md`), model domain (`docs/00-domain-model.md`), dan konfigurasi bisnis default. Semua teks dalam **[KURUNG SIKU]** wajib dilengkapi. Angka biaya, batas, dan tenggat mengikuti konfigurasi saat dokumen ditulis dan dapat berubah melalui versi dokumen baru.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Terakhir diperbarui:** 27 September 2026

**Penyelenggara:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian] ("**JastipKita**", "**kami**"), berkedudukan di [ALAMAT TERDAFTAR], Nomor Induk Berusaha [NIB], terdaftar sebagai Penyelenggara Sistem Elektronik Lingkup Privat dengan nomor [NOMOR TANDA DAFTAR PSE]. JastipKita adalah merek layanan yang merupakan bagian dari AntarKita Indonesia.

## 1. Definisi

- **Platform**: aplikasi seluler, situs web, dan API JastipKita.
- **Pengguna**: setiap orang yang membuat akun, yaitu Penitip dan/atau Traveler.
- **Penitip**: Pengguna yang meminta Traveler membelikan dan membawakan barang dari luar negeri.
- **Traveler**: Pengguna terverifikasi yang melakukan perjalanan dan menerima permintaan titipan.
- **Titipan**: permintaan pembelian barang oleh Penitip beserta transaksi yang menyertainya.
- **SafePay**: alur pembayaran JastipKita di mana dana Penitip diproses dan ditahan oleh mitra payment gateway berizin sampai syarat pelepasan terpenuhi (lihat [Ketentuan Pembayaran](payment-terms.md)).
- **Rincian Biaya**: tampilan 11 baris biaya yang wajib dilihat Penitip sebelum membayar.
- **Status Transaksi**: status resmi transaksi di Platform (antara lain PAYMENT SECURED, PURCHASE APPROVED, PURCHASED, DELIVERED, COMPLETED).

## 2. Penerimaan ketentuan

1. Dengan membuat akun atau memakai Platform, Anda menyatakan telah membaca, memahami, dan menyetujui Syarat & Ketentuan ini, [Kebijakan Privasi](privacy-policy.md), [Ketentuan Pembayaran](payment-terms.md), [Kebijakan Refund](refund-policy.md), [Kebijakan Barang Terlarang](prohibited-items-policy.md), dan [Pedoman Komunitas](community-guidelines.md).
2. Traveler juga terikat pada [Perjanjian Traveler](traveler-agreement.md).
3. Persetujuan atas pemrosesan data pribadi, data KYC/biometrik, dan pemasaran diberikan **terpisah** dari Syarat & Ketentuan ini.
4. Anda harus berusia minimal 18 tahun atau cakap hukum menurut peraturan perundang-undangan Indonesia. **[LEGAL REVIEW: batas usia & perlakuan pengguna di bawah umur.]**

## 3. Peran para pihak

1. JastipKita adalah **penyelenggara platform** yang mempertemukan Penitip dan Traveler, menyediakan alur pembayaran SafePay melalui mitra, verifikasi pengguna, dan penyelesaian sengketa.
2. **Traveler** adalah pihak yang membeli, membawa, mendeklarasikan, dan menyerahkan barang, serta bertanggung jawab atas kewajiban kepabeanan pada saat kedatangan.
3. JastipKita **bukan** penjual barang, bukan importir, bukan perusahaan jasa pengiriman, bukan bank, dan bukan penerbit uang elektronik.
4. **[LEGAL REVIEW: kualifikasi Traveler sebagai "Pedagang" menurut Permendag 19/2026 dan kewajiban NIB; posisi JastipKita sebagai PPMSE.]**

## 4. Akun, verifikasi, dan keamanan

1. Anda wajib memberikan data yang benar dan terkini, serta menjaga kerahasiaan kode OTP, PIN serah terima, dan perangkat Anda.
2. Tingkat verifikasi (KYC) menentukan fitur dan batas transaksi: Level 1 Terdaftar, Level 2 HP terverifikasi (syarat pembayaran), Level 3 Identitas terverifikasi, Level 4 Traveler terverifikasi, Level 5 Trusted Traveler. Rincian batas ditampilkan di aplikasi.
3. Kami dapat meminta verifikasi ulang, membatasi, menahan, atau menangguhkan akun apabila terdapat indikasi penipuan, pelanggaran hukum, atau risiko bagi pengguna lain. Keputusan tersebut dicatat dan dapat Anda ajukan keberatan melalui kanal bantuan.
4. Satu orang hanya boleh memiliki satu akun kecuali disetujui tertulis oleh kami.

## 5. Alur transaksi

1. Penitip membuat Titipan; Platform memeriksa barang terhadap daftar barang terlarang/terbatas dan menampilkan estimasi biaya.
2. Setelah Penitip dan Traveler sepakat (match), Penitip membayar melalui SafePay. Status menjadi **PAYMENT SECURED** setelah pembayaran terverifikasi.
3. **Traveler hanya boleh membeli barang setelah status PURCHASE APPROVED.** Pembelian sebelum status tersebut sepenuhnya menjadi risiko Traveler.
4. Traveler mengunggah bukti pembelian (struk, foto barang, nama toko, harga aktual, waktu pembelian; nomor seri dan/atau video untuk kategori tertentu).
5. Setelah tiba, Traveler menyelesaikan kewajiban kepabeanan dan menyerahkan barang melalui PIN/QR (bertemu langsung) atau kurir dengan nomor resi.
6. Penitip mengonfirmasi penerimaan. Bila tidak ada konfirmasi atau dispute dalam **48 jam** setelah status DELIVERED, transaksi dikonfirmasi otomatis.
7. Dana diteruskan ke Traveler setelah konfirmasi dan tidak ada dispute terbuka, sesuai [Ketentuan Pembayaran](payment-terms.md).

## 6. Harga, biaya, dan estimasi bea & pajak

1. Seluruh biaya ditampilkan dalam Rincian Biaya sebelum pembayaran: Harga Barang, Traveler Fee, Bea Masuk (estimasi), Pajak Impor (estimasi), JastipKita Protection, Platform Fee, PPN atas layanan (bila berlaku), Biaya Pembayaran, Diskon, JastipKita Credit, dan Total Landed Cost. **Tidak ada biaya yang dipungut di luar Rincian Biaya.**
2. Harga barang dalam mata uang asing dikonversi dengan kurs yang dikunci selama waktu yang ditampilkan (saat ini 30 menit), termasuk markup kurs yang diungkapkan.
3. Bea masuk dan pajak impor adalah **estimasi** berdasarkan aturan yang berlaku saat penawaran dibuat (versi aturan dicatat pada penawaran). Barang titipan diperlakukan sebagai **barang bukan pribadi** menurut PMK 34 Tahun 2025. Nilai final ditetapkan pejabat Bea dan Cukai.
4. Selisih antara estimasi dan tagihan resmi Bea dan Cukai diselesaikan berdasarkan bukti pembayaran resmi yang diunggah Traveler: **[LEGAL/FINANCE REVIEW: mekanisme penagihan kekurangan dan pengembalian kelebihan, batas nominal, dan tenggat.]**

## 7. Konfirmasi perubahan harga

1. Bila harga aktual berbeda dari harga yang telah diamankan melebihi toleransi (saat ini 2% atau maksimal Rp50.000), Traveler wajib mengajukan konfirmasi harga beserta bukti.
2. Penitip memiliki **15 menit** untuk menyetujui, menolak, atau meminta klarifikasi. Tanpa respons hingga batas waktu, konfirmasi dianggap **ditolak**.
3. Penolakan kenaikan harga **bukan kesalahan Penitip**: transaksi dibatalkan dan dana dikembalikan penuh termasuk biaya pembayaran, tanpa penalti Trust Score.
4. Bila disetujui dan dana yang diamankan tidak cukup, Penitip membayar selisihnya sebelum pembelian disetujui.

## 8. Pembatalan, refund, dan dispute

1. Hak membatalkan dan besaran pengembalian dana mengikuti matriks pada [Kebijakan Refund](refund-policy.md).
2. Setelah barang dibeli, Penitip tidak dapat membatalkan sepihak; keluhan diajukan melalui Dispute Center.
3. Dispute dapat dibuka paling lambat **72 jam** setelah status DELIVERED. Para pihak menyampaikan bukti dalam 72 jam; JastipKita menargetkan keputusan dalam 120 jam setelah bukti lengkap; banding dapat diajukan satu kali dalam 72 jam.
4. Keputusan dispute dapat berupa refund penuh, refund sebagian, tanpa refund, retur dan refund, atau penyelesaian lain yang dicatat. Keputusan ini tidak menghapus hak Anda untuk menempuh upaya hukum sesuai Pasal 17.

## 9. Barang terlarang dan terbatas

1. Barang berklasifikasi **PROHIBITED** tidak dapat dititipkan dan pembayaran diblokir.
2. Barang **RESTRICTED**, **DECLARATION_REQUIRED**, atau **PERMIT_REQUIRED** hanya dapat dititipkan setelah Penitip menyetujui peringatan yang ditampilkan; persetujuan tersebut dicatat.
3. Klasifikasi Platform adalah alat bantu. Keputusan akhir atas impor barang ada pada Bea dan Cukai dan instansi terkait. Barang yang ditahan, dimusnahkan, atau direekspor oleh otoritas diselesaikan melalui Dispute Center dengan memperhatikan kesalahan masing-masing pihak.

## 10. Kewajiban dan larangan Pengguna

Pengguna dilarang, antara lain:

1. melakukan atau meminta pembayaran di luar SafePay;
2. meminta atau membantu menyamarkan barang titipan sebagai barang pribadi, memecah barang (*splitting*) untuk memanfaatkan pembebasan, atau memberikan keterangan palsu kepada Bea dan Cukai;
3. menitipkan atau membawa barang terlarang, palsu, curian, atau hasil kejahatan;
4. memakai Platform untuk mengirim uang tunai atau sebagai sarana transfer dana;
5. memberikan ulasan palsu, memanipulasi Trust Score, atau membuat akun ganda;
6. mengakses sistem secara tidak sah atau mengganggu keamanan Platform.

## 11. Trust Score, batas transaksi, dan pengelolaan risiko

1. Trust Score (0–100) dihitung otomatis dari riwayat akun. Penyesuaian manual oleh tim wajib beralasan dan tercatat.
2. Kami menerapkan batas nilai transaksi berdasarkan tingkat verifikasi, Trust Score, dan risiko kategori/negara, serta pemeriksaan risiko otomatis yang dapat menghasilkan keputusan *izinkan*, *tinjau*, *tahan*, atau *blokir*. Anda berhak meminta peninjauan manusia atas keputusan otomatis yang berdampak signifikan (lihat [Kebijakan Privasi](privacy-policy.md)).

## 12. Kekayaan intelektual

Merek, logo, dan perangkat lunak JastipKita dilindungi hukum. Konten yang Anda unggah tetap milik Anda; Anda memberi kami lisensi terbatas untuk memprosesnya sepanjang diperlukan untuk menjalankan layanan, penyelesaian sengketa, dan kepatuhan hukum. **[LEGAL REVIEW: status pendaftaran merek "JastipKita" — lihat docs/research/04-market-and-naming.md.]**

## 13. Batasan tanggung jawab

1. JastipKita bertanggung jawab atas penyelenggaraan Platform sesuai peraturan perundang-undangan, termasuk UU Nomor 8 Tahun 1999 tentang Perlindungan Konsumen. Ketentuan ini **tidak** dimaksudkan untuk mengalihkan tanggung jawab yang menurut hukum tidak dapat dialihkan.
2. Sepanjang diizinkan hukum, JastipKita tidak bertanggung jawab atas: keputusan otoritas kepabeanan/karantina; keterlambatan atau pembatalan perjalanan Traveler; kerugian tidak langsung; atau kerugian akibat transaksi di luar SafePay.
3. **[LEGAL REVIEW: batas nilai tanggung jawab dan kesesuaiannya dengan Pasal 18 UU 8/1999 (klausula baku).]**

## 14. Keadaan kahar

Pihak yang terdampak keadaan kahar (bencana, gangguan penerbangan massal, kebijakan pemerintah, gangguan sistem pembayaran pihak ketiga) dibebaskan dari keterlambatan yang disebabkannya, dengan kewajiban memberi tahu dan memitigasi. Dana yang tertahan diselesaikan sesuai Kebijakan Refund.

## 15. Penangguhan dan pengakhiran

Anda dapat menutup akun kapan saja melalui aplikasi atau halaman [Hapus akun](/jastipkita/hapus-akun/). Kami dapat menangguhkan atau mengakhiri akun yang melanggar ketentuan ini dengan pemberitahuan, kecuali diwajibkan segera oleh hukum atau untuk mencegah kerugian. Kewajiban atas transaksi yang sedang berjalan tetap berlaku sampai selesai.

## 16. Perubahan ketentuan

Perubahan material diberitahukan paling lambat [JUMLAH] hari sebelum berlaku melalui aplikasi dan/atau e-mail. Versi dan tanggal berlaku setiap dokumen dicatat, dan persetujuan Anda disimpan per versi.

## 17. Hukum yang berlaku dan penyelesaian sengketa

1. Ketentuan ini tunduk pada hukum Republik Indonesia.
2. Sengketa diupayakan diselesaikan melalui Dispute Center dan musyawarah. Bila tidak tercapai, Pengguna dapat menempuh penyelesaian melalui Badan Penyelesaian Sengketa Konsumen atau Pengadilan Negeri [DOMISILI PENGADILAN] sesuai peraturan yang berlaku.
3. **[LEGAL REVIEW: klausul pilihan forum/arbitrase dan kanal pengaduan konsumen sesuai Permendag 19/2026.]**

## 18. Bahasa

Ketentuan ini dibuat dalam Bahasa Indonesia. Terjemahan (bila ada) hanya untuk kemudahan; bila terdapat perbedaan, versi Bahasa Indonesia yang berlaku.

## 19. Kontak

- Layanan pelanggan: [NOMOR WHATSAPP CS] · [E-MAIL CS]
- Pengaduan konsumen: [E-MAIL/KANAL PENGADUAN] (target tanggapan: [SLA])
- Alamat surat: [ALAMAT TERDAFTAR]
$jk_legal$,
        'Versi template awal dari docs/legal/terms-of-service.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)
VALUES ('TRAVELER_AGREEMENT', '0.1-template', 'id', $jk_legal$Perjanjian Traveler$jk_legal$, $jk_legal$Kewajiban dan hak Traveler JastipKita — kapan boleh membeli, bukti pembelian, deklarasi bea cukai yang jujur, serah terima, payout, dan pajak.$jk_legal$,
$jk_legal$> **TEMPLATE — wajib direview konsultan hukum sebelum production launch; bukan nasihat hukum.**
>
> Perjanjian tambahan atas [Syarat & Ketentuan](terms-of-service.md) yang berlaku bagi setiap Pengguna dalam mode Traveler. Bagian kepabeanan merujuk `docs/research/01-customs-tax-indonesia.md`; beberapa butir masih **NEEDS_VERIFICATION** dan ditandai. Lengkapi semua **[KURUNG SIKU]**.

**Versi:** 0.1 (draf) · **Berlaku sejak:** [TANGGAL BERLAKU] · **Para pihak:** [NAMA BADAN USAHA — PT/CV, menunggu pendirian] ("JastipKita") dan Anda sebagai Traveler.

## 1. Syarat menjadi Traveler

1. Menerima titipan memerlukan akun minimal **Level 3 — Identitas terverifikasi** (KTP/paspor + selfie & liveness).
2. Menerbitkan trip terverifikasi memerlukan **Level 4 — Traveler terverifikasi**: rekening payout atas nama Anda yang tervalidasi dan dokumen perjalanan (tiket/boarding pass) yang disetujui tim JastipKita.
3. Trip tanpa dokumen perjalanan tidak dapat diaktifkan. Anda wajib memperbarui trip bila jadwal berubah dan membatalkan trip yang tidak jadi dilakukan.
4. Anda menentukan sendiri kapasitas (kg/jumlah barang), kategori yang diterima atau ditolak, dan fee Anda, dalam batas yang berlaku (saat ini minimal Rp25.000 dan maksimal 30% dari harga barang per titipan).

## 2. Aturan emas: beli hanya setelah PURCHASE APPROVED

1. **Anda hanya boleh membeli barang setelah status transaksi PURCHASE APPROVED.** Status ini mensyaratkan dana Penitip sudah diamankan SafePay (PAYMENT SECURED) dan harga aktual telah dikonfirmasi.
2. Sebelum status tersebut, aplikasi menampilkan banner merah **"Jangan beli dulu / DO NOT PURCHASE"**. Pembelian sebelum waktunya sepenuhnya menjadi risiko Anda dan tidak dijamin penggantiannya.
3. Anda tidak boleh membeli di atas harga maksimum yang disetujui. Bila harga aktual berbeda di luar toleransi (2% atau maks. Rp50.000), ajukan **konfirmasi harga** dengan foto label/struk; Penitip punya 15 menit untuk merespons, dan tanpa respons dianggap menolak.
4. Anda tidak boleh mengganti barang, varian, ukuran, atau toko tanpa persetujuan Penitip melalui aplikasi.

## 3. Bukti pembelian

Segera setelah membeli, unggah bukti lengkap: foto struk/nota asli, foto barang, nama toko, harga aktual, dan waktu pembelian; untuk kategori tertentu (mis. ponsel, laptop, kamera, jam tangan, barang mewah) juga **nomor seri dan video pembelian**. Bukti palsu atau dimanipulasi adalah pelanggaran berat.

## 4. Kepabeanan — deklarasi yang jujur

1. **Barang titipan BUKAN barang pribadi Anda.** Menurut PMK 34 Tahun 2025 (Pasal 24 ayat (3)), barang bawaan penumpang yang bukan barang pribadi dikenai bea masuk 10% atas nilai penuh, PPN, dan PPh 22 impor, **tanpa** pembebasan FOB USD 500, dan **tidak** dikecualikan dari ketentuan larangan/pembatasan (lartas).
2. Anda wajib mendeklarasikan barang titipan dengan jujur melalui **All Indonesia** (kedatangan udara & laut) atau **e-CD** (kedatangan darat), dan menyerahkan dokumen yang diminta petugas.
3. Anda **dilarang**: menyatakan barang titipan sebagai barang pribadi; memecah barang (*splitting*) atau mengatur kedatangan untuk memanfaatkan pembebasan; menyembunyikan barang; atau menyampaikan nilai yang tidak sesuai struk.
4. Ponsel, komputer genggam, dan tablet wajib didaftarkan IMEI-nya atas paspor Anda (maks. **2 unit** per penumpang per kedatangan, termasuk perangkat pribadi Anda), di bandara atau paling lambat 60 hari setelah kedatangan.
5. Bea dan pajak dibayar atas nama Anda sebagai penumpang. Unggah bukti pembayaran resmi (billing/SSPCP) ke transaksi; penggantian dilakukan dari estimasi yang telah dibayar Penitip sesuai [Ketentuan Pembayaran](payment-terms.md). **[LEGAL/FINANCE REVIEW: mekanisme selisih estimasi vs tagihan resmi.]**
6. Tarif PPh 22 bagi penumpang **tanpa NPWP** atas barang bukan pribadi belum terverifikasi (5% menurut teks PMK 34/2025; 10% menurut UU PPh Pasal 22 ayat (3)) — **NEEDS_VERIFICATION**.
7. Barang yang ditahan, dimusnahkan, atau direekspor karena kesalahan deklarasi Anda menjadi tanggung jawab Anda.

## 5. Barang terlarang dan terbatas

1. Anda wajib menolak dan tidak membawa barang **PROHIBITED** (antara lain narkotika & produk CBD/THC, senjata, minuman beralkohol dan rokok/vape untuk orang lain, uang tunai, hewan hidup, pakaian bekas, barang palsu) — lihat [Kebijakan Barang Terlarang](prohibited-items-policy.md).
2. Untuk barang terbatas, patuhi batas jumlah per penumpang (mis. kosmetik 20 pcs, suplemen 5 pcs per jenis, obat 30 pcs per jenis) yang dihitung **atas seluruh titipan yang Anda bawa dalam satu kedatangan**, serta ketentuan barang berbahaya penerbangan (mis. power bank hanya di kabin dengan batas Wh).
3. Anda berhak menolak titipan yang menurut penilaian Anda melanggar hukum atau aturan maskapai.

## 6. Penyimpanan dan serah terima

1. Anda bertanggung jawab menjaga barang sejak dibeli sampai diserahkan, termasuk mengemas dengan wajar.
2. Serah terima langsung wajib memakai **PIN 6 digit atau QR** dari aplikasi Penitip (maks. 5 percobaan PIN; QR berlaku 30 menit). Jangan menerima PIN sebelum Penitip memeriksa barang.
3. Pengiriman lewat kurir wajib disertai nomor resi yang valid.
4. Anda wajib memberi kabar keterlambatan secepatnya melalui chat di aplikasi.

## 7. Payout

1. Penggantian harga barang dan fee Anda dijadwalkan untuk dibayarkan setelah Penitip mengonfirmasi penerimaan (atau konfirmasi otomatis 48 jam setelah DELIVERED tanpa dispute) dan tidak ada dispute terbuka.
2. Payout dikirim ke rekening payout terverifikasi atas nama Anda melalui mitra payment gateway. Payout dapat ditahan bila terdapat indikasi risiko, dispute, atau permintaan otoritas, dengan alasan yang dicatat.
3. Biaya transfer payout saat ini ditanggung JastipKita **[FINANCE REVIEW: final setelah kontrak mitra pembayaran]**.

## 8. Pajak atas penghasilan Anda

Fee yang Anda terima adalah penghasilan Anda. Anda bertanggung jawab atas pelaporan dan pembayaran pajaknya sesuai peraturan perpajakan. **[TAX REVIEW: apakah JastipKita wajib memotong/memungut pajak atas pembayaran ke Traveler (mis. PPh 21/PPh 22 PMSE) dan kewajiban NIB Traveler menurut Permendag 19/2026.]**

## 9. Perilaku yang dilarang

- meminta atau menerima pembayaran di luar SafePay, atau membagikan nomor rekening di chat;
- membeli sebelum PURCHASE APPROVED lalu menekan Penitip untuk menyetujui;
- menaikkan harga tanpa bukti, menukar barang, atau memakai barang titipan;
- menjual kembali barang titipan kepada pihak lain;
- membawa uang tunai atau barang milik pihak lain di luar transaksi Platform;
- memanipulasi ulasan, Trust Score, atau membuat akun ganda.

Pelanggaran dapat berakibat penalti Trust Score, penahanan payout, penangguhan, atau penutupan akun, serta pelaporan kepada pihak berwenang bila diwajibkan hukum.

## 10. Pembatalan oleh Traveler

Pembatalan oleh Traveler mengembalikan seluruh dana Penitip dan dikenai penalti Trust Score yang meningkat sesuai tahap (mis. 2 setelah match, 5 setelah pembayaran aman, 8 setelah pembelian disetujui, 15 setelah barang dibeli — yang terakhir memerlukan persetujuan admin dan barang tetap tanggung jawab Anda). Rincian di [Kebijakan Refund](refund-policy.md).

## 11. Lain-lain

Perjanjian ini tunduk pada hukum Republik Indonesia dan merupakan bagian tak terpisahkan dari [Syarat & Ketentuan](terms-of-service.md). Kontak: [E-MAIL CS] · [NOMOR WHATSAPP CS].
$jk_legal$,
        'Versi template awal dari docs/legal/traveler-agreement.md — wajib direview konsultan hukum sebelum production launch.', '2026-09-27T00:00:00Z')
ON CONFLICT (type, version, locale) DO NOTHING;

COMMIT;
