#!/usr/bin/env python3
"""Applies JastipKita's native settings to the folders generated by `flutter create`.

Run once after scaffolding (idempotent — safe to run again):

    flutter create --platforms=android,ios,web --org com.antarkitaindonesia --project-name jastipkita .
    python3 tool/configure_native.py

What it does
  Android (android/app/src/main/AndroidManifest.xml)
    * app label "JastipKita"
    * INTERNET permission in the main manifest (the template only adds it to debug/profile,
      so release builds would have no network) and CAMERA (QR handover scan, KYC capture)
    * deep links: jastipkita://…  and verified App Links for
      https://antarkitaindonesia.com/jastipkita/app/… and …/jastipkita/r/… (referrals),
      matching apps/web/well-known/assetlinks.json
    * flutter_deeplinking_enabled = true (go_router receives the links)
  iOS (ios/Runner/Info.plist)
    * display name "JastipKita"
    * camera / photo-library usage descriptions (Indonesian), URL scheme `jastipkita`
    * FlutterDeepLinkingEnabled = true
    Universal Links additionally need the Associated Domains capability
    (applinks:antarkitaindonesia.com) in Xcode — see README.

It only edits files that exist; it never creates android/ or ios/ (CI generates those only when
android/ is missing, so committing partial platform folders would break the build).
Plain Python 3.8+, no third-party modules.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / 'android' / 'app' / 'src' / 'main' / 'AndroidManifest.xml'
PLIST = ROOT / 'ios' / 'Runner' / 'Info.plist'

APP_NAME = 'JastipKita'
WEB_HOST = 'antarkitaindonesia.com'

ANDROID_PERMISSIONS = [
    'android.permission.INTERNET',
    'android.permission.CAMERA',
]

ANDROID_FILTERS = f'''
            <!-- JastipKita deep links (tool/configure_native.py) -->
            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/app" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/r" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="jastipkita" />
            </intent-filter>
'''

IOS_ENTRIES = {
    'NSCameraUsageDescription': '<string>Kamera dipakai untuk memindai QR serah terima, memotret barang, struk, dan dokumen verifikasi.</string>',
    'NSPhotoLibraryUsageDescription': '<string>Galeri dipakai untuk memilih foto produk, struk, dan bukti sengketa.</string>',
    'FlutterDeepLinkingEnabled': '<true/>',
    'CFBundleURLTypes': '''<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.antarkitaindonesia.jastipkita</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>jastipkita</string>
			</array>
		</dict>
	</array>''',
}


def configure_android() -> bool:
    if not MANIFEST.is_file():
        print(f'skip: {MANIFEST.relative_to(ROOT)} not found (run flutter create first)')
        return False
    xml = MANIFEST.read_text(encoding='utf-8')
    original = xml
    for permission in ANDROID_PERMISSIONS:
        if permission not in xml:
            xml = xml.replace('<application', f'<uses-permission android:name="{permission}" />\n    <application', 1)
    xml = re.sub(r'android:label="[^"]*"', f'android:label="{APP_NAME}"', xml, count=1)
    if 'android:scheme="jastipkita"' not in xml:
        activity = re.search(r'<activity\b[^>]*android:name="\.MainActivity".*?</activity>', xml, re.S)
        if not activity:
            print('warning: MainActivity not found in AndroidManifest.xml; deep links not added')
        else:
            block = activity.group(0)
            patched = re.sub(r'\n[ \t]*</activity>$', '\n' + ANDROID_FILTERS.strip('\n') + '\n        </activity>', block)
            xml = xml.replace(block, patched, 1)
    if xml != original:
        MANIFEST.write_text(xml, encoding='utf-8')
        print(f'updated: {MANIFEST.relative_to(ROOT)}')
    else:
        print(f'ok: {MANIFEST.relative_to(ROOT)} already configured')
    return True


def configure_ios() -> bool:
    if not PLIST.is_file():
        print(f'skip: {PLIST.relative_to(ROOT)} not found (run flutter create first)')
        return False
    plist = PLIST.read_text(encoding='utf-8')
    original = plist
    plist = re.sub(
        r'(<key>CFBundleDisplayName</key>\s*<string>)[^<]*(</string>)',
        lambda m: f'{m.group(1)}{APP_NAME}{m.group(2)}',
        plist,
        count=1,
    )
    additions = ''
    for key, value in IOS_ENTRIES.items():
        if f'<key>{key}</key>' not in plist:
            additions += f'\t<key>{key}</key>\n\t{value}\n'
    if additions:
        index = plist.rfind('</dict>')
        if index < 0:
            print('warning: Info.plist has no top-level </dict>; not modified')
            return False
        plist = plist[:index] + additions + plist[index:]
    if plist != original:
        PLIST.write_text(plist, encoding='utf-8')
        print(f'updated: {PLIST.relative_to(ROOT)}')
    else:
        print(f'ok: {PLIST.relative_to(ROOT)} already configured')
    return True


def main() -> int:
    android = configure_android()
    ios = configure_ios()
    return 0 if (android or ios) else 1


if __name__ == '__main__':
    sys.exit(main())
