#!/usr/bin/env python3
"""Applies JastipKita's native settings to the folders generated by `flutter create`.

Run after scaffolding (idempotent — CI runs it on every build, the iOS workflow runs it again
after `flutter pub get` so the CocoaPods Podfile is covered too):

    flutter create --platforms=android,ios,web --org com.antarkitaindonesia --project-name jastipkita .
    python3 tool/configure_native.py                       # apply (all platforms that exist)
    python3 tool/configure_native.py --check               # verify only (exit 1 when something is missing)
    python3 tool/configure_native.py --platforms=ios       # only one platform (e.g. the macOS iOS job)
    python3 tool/configure_native.py --ios-entitlements    # also write Runner.entitlements (see below)
    GOOGLE_IOS_CLIENT_ID=123-abc.apps.googleusercontent.com python3 tool/configure_native.py

What it does (checked against the Flutter stable templates: Kotlin DSL `build.gradle.kts`,
`SceneDelegate.swift` + `UIApplicationSceneManifest`, iOS deployment target 15.0, Swift Package
Manager on by default; Groovy `build.gradle` still handled)

  Android
    * AndroidManifest.xml: label "JastipKita"; INTERNET permission in the *main* manifest (the
      template only has it in debug/profile, so release builds would have no network) and CAMERA
      (QR handover scan, KYC capture); deep links `jastipkita://…` and verified App Links for
      https://antarkitaindonesia.com/jastipkita/app/… and …/jastipkita/r/… (referrals) —
      matching apps/web/well-known/assetlinks.json; `flutter_deeplinking_enabled` = true.
    * app/build.gradle(.kts): applicationId + namespace = com.antarkitaindonesia.jastipkita.
  iOS
    * Info.plist: CFBundleDisplayName / CFBundleName "JastipKita"; Indonesian purpose strings
      (managed — always reset to the values below): camera (QR handover, product/receipt photos,
      KYC ID + selfie), photo library (product, receipt, dispute evidence, documents) and
      microphone (image_picker records proof/dispute videos from the camera — iOS terminates the
      app without NSMicrophoneUsageDescription); URL scheme `jastipkita`;
      FlutterDeepLinkingEnabled = true. With GOOGLE_IOS_CLIENT_ID (or --google-ios-client-id)
      also GIDClientID + the reversed-client-id URL scheme google_sign_in needs on iOS (public
      values). Works with and without the UIScene manifest (keys go to the root dictionary).
      Deliberately NOT added: UIBackgroundModes (the file_picker wiki suggests fetch +
      remote-notification for FileType.custom; unused background modes risk App Review
      guideline 2.5.4), NSAppleMusicUsageDescription (no audio picking),
      ITSAppUsesNonExemptEncryption (export-compliance answer is the owner's decision).
    * Runner.xcodeproj: PRODUCT_BUNDLE_IDENTIFIER = com.antarkitaindonesia.jastipkita
      (RunnerTests → ….RunnerTests); IPHONEOS_DEPLOYMENT_TARGET raised to IOS_DEPLOYMENT_TARGET.
    * Podfile (only when it exists — `flutter pub get`/`flutter build ios` create it when a plugin
      still needs CocoaPods; with Swift Package Manager alone there may be none):
      `platform :ios, IOS_DEPLOYMENT_TARGET`.
    * --ios-entitlements (opt-in): ios/Runner/Runner.entitlements with Sign in with Apple and
      Associated Domains applinks:/webcredentials:antarkitaindonesia.com (matching
      apps/web/well-known/apple-app-site-association) + CODE_SIGN_ENTITLEMENTS on the Runner
      target. Opt-in because SIGNED builds fail unless the App ID / provisioning profile has
      both capabilities; unsigned CI builds (`--no-codesign`) are unaffected.
  Web
    * index.html <title> / apple-mobile-web-app-title and manifest.json name → "JastipKita".

It only edits files that exist (Runner.entitlements excepted, inside an existing ios/Runner); it
never creates android/ or ios/ (CI generates those only when they are missing, so committing
partial platform folders would break the build). Plain Python 3.8+, no third-party modules.
"""
from __future__ import annotations

import argparse
import json
import os
import plistlib
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
APP_NAME = 'JastipKita'
APP_ID = 'com.antarkitaindonesia.jastipkita'
WEB_HOST = 'antarkitaindonesia.com'
URL_SCHEME = 'jastipkita'
# Highest minimum among the iOS plugins: mobile_scanner 6.x bundles GoogleMLKit 7.0, which needs
# iOS 15.5 (mobile_scanner CHANGELOG 6.0.0). Flutter stable itself needs 15.0. Lower it to 15.0
# only after moving to mobile_scanner >= 7 (Apple Vision, iOS 13+) — that also brings back arm64
# simulator builds, which MLKit 7 does not support (CHANGELOG 6.0.2).
IOS_DEPLOYMENT_TARGET = '15.5'

MANIFEST = ROOT / 'android' / 'app' / 'src' / 'main' / 'AndroidManifest.xml'
GRADLE_FILES = [ROOT / 'android' / 'app' / 'build.gradle.kts', ROOT / 'android' / 'app' / 'build.gradle']
PLIST = ROOT / 'ios' / 'Runner' / 'Info.plist'
PBXPROJ = ROOT / 'ios' / 'Runner.xcodeproj' / 'project.pbxproj'
PODFILE = ROOT / 'ios' / 'Podfile'
SCENE_DELEGATE = ROOT / 'ios' / 'Runner' / 'SceneDelegate.swift'
ENTITLEMENTS = ROOT / 'ios' / 'Runner' / 'Runner.entitlements'
ENTITLEMENTS_SETTING = 'Runner/Runner.entitlements'  # relative to ios/, as Xcode stores it
WEB_INDEX = ROOT / 'web' / 'index.html'
WEB_MANIFEST = ROOT / 'web' / 'manifest.json'

ANDROID_PERMISSIONS = ['android.permission.INTERNET', 'android.permission.CAMERA']

DEEPLINK_META = '<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />'
ANDROID_FILTERS = f'''            <!-- JastipKita deep links (tool/configure_native.py) -->
            {DEEPLINK_META}
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/app" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/r" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="{URL_SCHEME}" />
            </intent-filter>'''

# Purpose strings shown by iOS in the permission prompt (App Review 5.1.1: say what and why).
IOS_USAGE_STRINGS = {
    'NSCameraUsageDescription': (
        'Kamera dipakai untuk memindai QR serah terima, memotret barang dan struk, '
        'serta foto KTP dan swafoto untuk verifikasi identitas.'
    ),
    'NSPhotoLibraryUsageDescription': (
        'Galeri dipakai untuk memilih foto produk, struk atau bukti pembelian, bukti sengketa, '
        'dan dokumen verifikasi.'
    ),
    'NSMicrophoneUsageDescription': (
        'Mikrofon dipakai saat Anda merekam video bukti pembelian atau bukti sengketa dengan kamera.'
    ),
}
ASSOCIATED_DOMAINS = [f'applinks:{WEB_HOST}', f'webcredentials:{WEB_HOST}']
GOOGLE_CLIENT_ID = re.compile(r'(\d+-[0-9a-z]+)\.apps\.googleusercontent\.com')


class Report:
    def __init__(self, check_only: bool) -> None:
        self.check_only = check_only
        self.changed: list[str] = []
        self.problems: list[str] = []
        self.ok: list[str] = []
        self.notes: list[str] = []

    def write(self, path: Path, old: str, new: str) -> None:
        name = str(path.relative_to(ROOT))
        if old == new:
            self.ok.append(name)
            return
        if self.check_only:
            self.problems.append(f'{name} is not configured')
            return
        path.write_text(new, encoding='utf-8')
        self.changed.append(name)


def _version(value: str) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r'\d+', value)) or (0,)


# ---------------------------------------------------------------- plist text helpers
# Text edits (not plistlib round-trips) keep the template layout, so diffs against a committed
# ios/ folder stay minimal; every result is still parsed with plistlib before it is written.

def _set_plist_string(plist: str, key: str, value: str) -> str:
    value = escape(value)
    pattern = re.compile(r'(<key>' + re.escape(key) + r'</key>\s*<string>)[^<]*(</string>)')
    if pattern.search(plist):
        return pattern.sub(lambda m: f'{m.group(1)}{value}{m.group(2)}', plist, count=1)
    index = plist.rfind('</dict>')
    return plist[:index] + f'\t<key>{key}</key>\n\t<string>{value}</string>\n' + plist[index:]


def _array_after_key(plist: str, key: str) -> tuple[int, int] | None:
    """(start, end) of the <array>…</array> that follows <key>key</key>, nested arrays included."""
    found = re.search(r'<key>' + re.escape(key) + r'</key>\s*<array>', plist)
    if not found:
        return None
    depth, position = 1, found.end()
    for tag in re.finditer(r'<(/?)array>', plist[position:]):
        depth += -1 if tag.group(1) else 1
        if depth == 0:
            return found.end() - len('<array>'), position + tag.end()
    return None


def _ensure_url_scheme(plist: str, name: str, scheme: str) -> str:
    entry = (
        '\t\t<dict>\n'
        '\t\t\t<key>CFBundleTypeRole</key>\n\t\t\t<string>Editor</string>\n'
        f'\t\t\t<key>CFBundleURLName</key>\n\t\t\t<string>{escape(name)}</string>\n'
        '\t\t\t<key>CFBundleURLSchemes</key>\n'
        f'\t\t\t<array>\n\t\t\t\t<string>{escape(scheme)}</string>\n\t\t\t</array>\n'
        '\t\t</dict>\n'
    )
    span = _array_after_key(plist, 'CFBundleURLTypes')
    if span is None:
        index = plist.rfind('</dict>')
        return plist[:index] + f'\t<key>CFBundleURLTypes</key>\n\t<array>\n{entry}\t</array>\n' + plist[index:]
    start, end = span
    if f'<string>{escape(scheme)}</string>' in plist[start:end]:
        return plist
    close = end - len('</array>')
    line_start = plist.rfind('\n', 0, close) + 1
    return plist[:line_start] + entry + plist[line_start:]


# ---------------------------------------------------------------- Android

def android_manifest(report: Report) -> None:
    if not MANIFEST.is_file():
        report.problems.append('android/app/src/main/AndroidManifest.xml not found (run flutter create first)')
        return
    original = MANIFEST.read_text(encoding='utf-8')
    xml = original
    for permission in ANDROID_PERMISSIONS:
        if f'android:name="{permission}"' not in xml:
            start = xml.find('<application')
            if start < 0:
                break
            line_start = xml.rfind('\n', 0, start) + 1
            indent = xml[line_start:start] if xml[line_start:start].strip() == '' else '    '
            xml = xml[:line_start] + f'{indent}<uses-permission android:name="{permission}" />\n' + xml[line_start:]
    application = re.search(r'<application\b[^>]*>', xml, re.S)
    if application:
        tag = application.group(0)
        if 'android:label=' in tag:
            new_tag = re.sub(r'android:label="[^"]*"', f'android:label="{APP_NAME}"', tag, count=1)
        else:
            new_tag = tag.replace('<application', f'<application\n        android:label="{APP_NAME}"', 1)
        xml = xml.replace(tag, new_tag, 1)
    else:
        report.problems.append('AndroidManifest.xml has no <application> element')
    activity = re.search(r'<activity\b(?:(?!</activity>).)*?android:name="(?:\.|[\w.]+\.)MainActivity"(?:(?!</activity>).)*?</activity>', xml, re.S)
    if not activity:
        report.problems.append('MainActivity not found in AndroidManifest.xml; deep links not added')
    else:
        block = activity.group(0)
        patched = block
        if 'flutter_deeplinking_enabled' in patched:
            patched = re.sub(
                r'(android:name="flutter_deeplinking_enabled"\s+android:value=")false(")',
                r'\1true\2',
                patched,
            )
        if f'android:scheme="{URL_SCHEME}"' not in patched:
            filters = ANDROID_FILTERS if 'flutter_deeplinking_enabled' not in patched else ANDROID_FILTERS.replace(f'            {DEEPLINK_META}\n', '')
            patched = re.sub(r'\n[ \t]*</activity>$', '\n' + filters + '\n        </activity>', patched)
        xml = xml.replace(block, patched, 1)
    report.write(MANIFEST, original, xml)


def android_gradle(report: Report) -> None:
    gradle = next((g for g in GRADLE_FILES if g.is_file()), None)
    if gradle is None:
        report.problems.append('android/app/build.gradle(.kts) not found')
        return
    original = gradle.read_text(encoding='utf-8')
    text = original
    if gradle.suffix == '.kts':
        text = re.sub(r'(applicationId\s*=\s*")[^"]*(")', rf'\g<1>{APP_ID}\g<2>', text)
        text = re.sub(r'(namespace\s*=\s*")[^"]*(")', rf'\g<1>{APP_ID}\g<2>', text)
    else:
        text = re.sub(r'(applicationId\s*[=\s]\s*["\'])[^"\']*(["\'])', rf'\g<1>{APP_ID}\g<2>', text)
        text = re.sub(r'(namespace\s*[=\s]\s*["\'])[^"\']*(["\'])', rf'\g<1>{APP_ID}\g<2>', text)
    if APP_ID not in text:
        report.problems.append(f'{gradle.relative_to(ROOT)}: applicationId not found')
    if text != original:
        activity = list((ROOT / 'android' / 'app' / 'src' / 'main').rglob('MainActivity.*'))
        if activity and f'package {APP_ID}' not in activity[0].read_text(encoding='utf-8'):
            report.problems.append(
                f'{activity[0].relative_to(ROOT)} is not in package {APP_ID}: re-run flutter create with --org com.antarkitaindonesia',
            )
    report.write(gradle, original, text)


# ---------------------------------------------------------------- iOS

def ios_plist(report: Report, google_ios_client_id: str) -> None:
    if not PLIST.is_file():
        report.problems.append('ios/Runner/Info.plist not found (run flutter create first)')
        return
    original = PLIST.read_text(encoding='utf-8')
    if original.rfind('</dict>') < 0:
        report.problems.append('Info.plist has no root </dict>')
        return
    plist = _set_plist_string(original, 'CFBundleDisplayName', APP_NAME)
    plist = _set_plist_string(plist, 'CFBundleName', APP_NAME)
    for key, value in IOS_USAGE_STRINGS.items():
        plist = _set_plist_string(plist, key, value)
    if '<key>FlutterDeepLinkingEnabled</key>' in plist:
        plist = re.sub(r'(<key>FlutterDeepLinkingEnabled</key>\s*)<false\s*/>', r'\1<true/>', plist)
    else:
        index = plist.rfind('</dict>')
        plist = plist[:index] + '\t<key>FlutterDeepLinkingEnabled</key>\n\t<true/>\n' + plist[index:]
    plist = _ensure_url_scheme(plist, APP_ID, URL_SCHEME)
    if google_ios_client_id:
        match = GOOGLE_CLIENT_ID.fullmatch(google_ios_client_id.strip())
        if match:
            plist = _set_plist_string(plist, 'GIDClientID', match.group(0))
            plist = _ensure_url_scheme(plist, 'GoogleSignIn', f'com.googleusercontent.apps.{match.group(1)}')
        else:
            report.problems.append('GOOGLE_IOS_CLIENT_ID is not an iOS OAuth client id (<number>-<id>.apps.googleusercontent.com)')
    else:
        report.notes.append('GOOGLE_IOS_CLIENT_ID not set: Google Sign-In URL scheme not added (the button reports "not configured")')
    try:
        plistlib.loads(plist.encode('utf-8'))
    except Exception as error:  # noqa: BLE001 — any parse failure means the edit is unsafe
        report.problems.append(f'ios/Runner/Info.plist would not be a valid plist after editing ({error}); left unchanged')
        return
    report.write(PLIST, original, plist)
    if SCENE_DELEGATE.is_file() and 'UIApplicationSceneManifest' not in plist:
        report.problems.append('SceneDelegate.swift exists but Info.plist has no UIApplicationSceneManifest')


def _add_entitlements_setting(block: re.Match[str]) -> str:
    body = block.group(1)
    if f'PRODUCT_BUNDLE_IDENTIFIER = {APP_ID};' not in body or 'CODE_SIGN_ENTITLEMENTS' in body:
        return block.group(0)
    lines = body.split('\n')
    first = next((line for line in lines if line.strip()), '')
    indent = first[: len(first) - len(first.lstrip())]
    setting = f'{indent}CODE_SIGN_ENTITLEMENTS = {ENTITLEMENTS_SETTING};'
    position = len(lines)
    for number, line in enumerate(lines):  # keep Xcode's alphabetical order of top-level keys
        key = re.match(re.escape(indent) + r'"?([A-Za-z_][^"=\s]*)', line)
        if key and line[len(indent):len(indent) + 1] not in (' ', '\t') and key.group(1) > 'CODE_SIGN_ENTITLEMENTS':
            position = number
            break
    if position == len(lines) and lines and not lines[-1].strip():
        position -= 1
    lines.insert(position, setting)
    return 'buildSettings = {' + '\n'.join(lines) + '};'


def ios_project(report: Report, entitlements: bool) -> None:
    if not PBXPROJ.is_file():
        report.problems.append('ios/Runner.xcodeproj/project.pbxproj not found')
        return
    original = PBXPROJ.read_text(encoding='utf-8')

    def bundle_id(match: re.Match[str]) -> str:
        value = match.group(2).strip('"')
        wanted = f'{APP_ID}.RunnerTests' if value.endswith('.RunnerTests') else APP_ID
        return f'{match.group(1)}{wanted};'

    def deployment_target(match: re.Match[str]) -> str:
        current = match.group(2)
        wanted = IOS_DEPLOYMENT_TARGET if _version(current) < _version(IOS_DEPLOYMENT_TARGET) else current
        return f'{match.group(1)}{wanted};'

    text = re.sub(r'(PRODUCT_BUNDLE_IDENTIFIER = )([^;]+);', bundle_id, original)
    text = re.sub(r'(IPHONEOS_DEPLOYMENT_TARGET = )"?([\d.]+)"?;', deployment_target, text)
    if 'IPHONEOS_DEPLOYMENT_TARGET' not in text:
        report.problems.append('project.pbxproj has no IPHONEOS_DEPLOYMENT_TARGET (unexpected Flutter template)')
    if entitlements:
        text = re.sub(r'buildSettings = \{([^{}]*)\};', _add_entitlements_setting, text)
        if f'CODE_SIGN_ENTITLEMENTS = {ENTITLEMENTS_SETTING};' not in text:
            report.problems.append(f'project.pbxproj: no Runner build configuration with PRODUCT_BUNDLE_IDENTIFIER = {APP_ID}')
    report.write(PBXPROJ, original, text)


def ios_podfile(report: Report) -> None:
    if not PODFILE.is_file():
        report.notes.append(
            'ios/Podfile not present (created by flutter pub get / flutter build ios when a plugin needs CocoaPods); '
            f'CocoaPods then inherits iOS {IOS_DEPLOYMENT_TARGET} from the Xcode project — re-run this script after pub get',
        )
        return
    original = PODFILE.read_text(encoding='utf-8')
    wanted = f"platform :ios, '{IOS_DEPLOYMENT_TARGET}'"
    line = re.search(r"^[ \t]*(#\s*)?platform\s+:ios\s*,\s*['\"]([\d.]+)['\"].*$", original, re.M)
    if line is None:
        text = f'{wanted}\n{original}'
    elif line.group(1) or _version(line.group(2)) < _version(IOS_DEPLOYMENT_TARGET):
        text = original[: line.start()] + wanted + original[line.end():]
    else:
        text = original
    report.write(PODFILE, original, text)


def ios_entitlements(report: Report) -> None:
    if not ENTITLEMENTS.parent.is_dir():
        report.problems.append('ios/Runner not found (run flutter create first)')
        return
    wanted = {
        'com.apple.developer.applesignin': ['Default'],
        'com.apple.developer.associated-domains': ASSOCIATED_DOMAINS,
    }
    original = ENTITLEMENTS.read_text(encoding='utf-8') if ENTITLEMENTS.is_file() else ''
    try:
        data = plistlib.loads(original.encode('utf-8')) if original else {}
    except Exception:  # noqa: BLE001
        report.problems.append('ios/Runner/Runner.entitlements is not a valid plist')
        return
    merged = dict(data)
    for key, values in wanted.items():
        current = list(merged.get(key) or [])
        merged[key] = current + [value for value in values if value not in current]
    text = original if merged == data else plistlib.dumps(merged, sort_keys=False).decode('utf-8')
    report.write(ENTITLEMENTS, original, text)


# ---------------------------------------------------------------- Web

def web(report: Report) -> None:
    if WEB_INDEX.is_file():
        original = WEB_INDEX.read_text(encoding='utf-8')
        html = re.sub(r'<title>[^<]*</title>', f'<title>{APP_NAME}</title>', original, count=1)
        html = re.sub(r'(<meta name="apple-mobile-web-app-title" content=")[^"]*(")', rf'\g<1>{APP_NAME}\g<2>', html, count=1)
        report.write(WEB_INDEX, original, html)
    if WEB_MANIFEST.is_file():
        original = WEB_MANIFEST.read_text(encoding='utf-8')
        try:
            data = json.loads(original)
        except json.JSONDecodeError:
            report.problems.append('web/manifest.json is not valid JSON')
            return
        data['name'] = APP_NAME
        data['short_name'] = APP_NAME
        updated = json.dumps(data, indent=4, ensure_ascii=False) + '\n'
        report.write(WEB_MANIFEST, original, original if json.loads(original) == data else updated)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n', 1)[0])
    parser.add_argument('--check', action='store_true', help='verify only; exit 1 when something is not configured')
    parser.add_argument('--platforms', default='android,ios,web', help='comma-separated subset of android,ios,web')
    parser.add_argument('--ios-entitlements', action='store_true',
                        help='write Runner.entitlements (Sign in with Apple, Associated Domains) and reference it')
    parser.add_argument('--google-ios-client-id', default=os.environ.get('GOOGLE_IOS_CLIENT_ID', ''),
                        help='public iOS OAuth client id (default: $GOOGLE_IOS_CLIENT_ID)')
    args = parser.parse_args(argv)
    platforms = {p.strip() for p in args.platforms.split(',') if p.strip()}
    unknown = platforms - {'android', 'ios', 'web'}
    if unknown:
        parser.error(f'unknown platform(s): {", ".join(sorted(unknown))}')

    report = Report(check_only=args.check)
    if 'android' in platforms:
        android_manifest(report)
        android_gradle(report)
    if 'ios' in platforms:
        ios_plist(report, args.google_ios_client_id)
        ios_project(report, args.ios_entitlements)
        ios_podfile(report)
        if args.ios_entitlements:
            ios_entitlements(report)
    if 'web' in platforms:
        web(report)
    for name in report.changed:
        print(f'updated: {name}')
    for name in report.ok:
        print(f'ok: {name}')
    for note in report.notes:
        print(f'note: {note}')
    for problem in report.problems:
        print(f'problem: {problem}')
    return 1 if report.problems else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
