#!/usr/bin/env python3
"""Applies JastipKita's native settings to the folders generated by `flutter create`.

Run after scaffolding (idempotent — CI runs it on every build):

    flutter create --platforms=android,ios,web --org com.antarkitaindonesia --project-name jastipkita .
    python3 tool/configure_native.py            # apply
    python3 tool/configure_native.py --check    # verify only (exit 1 when something is missing)

What it does (checked against the Flutter 3.47 templates: Kotlin DSL `build.gradle.kts`,
`SceneDelegate.swift` + `UIApplicationSceneManifest`; Groovy `build.gradle` still handled)

  Android
    * AndroidManifest.xml: label "JastipKita"; INTERNET permission in the *main* manifest (the
      template only has it in debug/profile, so release builds would have no network) and CAMERA
      (QR handover scan, KYC capture); deep links `jastipkita://…` and verified App Links for
      https://antarkitaindonesia.com/jastipkita/app/… and …/jastipkita/r/… (referrals) —
      matching apps/web/well-known/assetlinks.json; `flutter_deeplinking_enabled` = true.
    * app/build.gradle(.kts): applicationId + namespace = com.antarkitaindonesia.jastipkita.
  iOS
    * Info.plist: CFBundleDisplayName / CFBundleName "JastipKita", camera & photo-library usage
      strings (Indonesian), URL scheme `jastipkita`, FlutterDeepLinkingEnabled = true. Works with
      and without the UIScene manifest (keys are added to the root dictionary).
    * Runner.xcodeproj: PRODUCT_BUNDLE_IDENTIFIER = com.antarkitaindonesia.jastipkita
      (RunnerTests → ….RunnerTests).
    Universal Links also need the Associated Domains capability (applinks:antarkitaindonesia.com)
    on the App ID and in Xcode — not scripted because signing fails without the Apple account
    capability (see README).
  Web
    * index.html <title> / apple-mobile-web-app-title and manifest.json name → "JastipKita".

It only edits files that exist; it never creates android/ or ios/ (CI generates those only when
android/ is missing, so committing partial platform folders would break the build).
Plain Python 3.8+, no third-party modules.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_NAME = 'JastipKita'
APP_ID = 'com.antarkitaindonesia.jastipkita'
WEB_HOST = 'antarkitaindonesia.com'

MANIFEST = ROOT / 'android' / 'app' / 'src' / 'main' / 'AndroidManifest.xml'
GRADLE_FILES = [ROOT / 'android' / 'app' / 'build.gradle.kts', ROOT / 'android' / 'app' / 'build.gradle']
PLIST = ROOT / 'ios' / 'Runner' / 'Info.plist'
PBXPROJ = ROOT / 'ios' / 'Runner.xcodeproj' / 'project.pbxproj'
SCENE_DELEGATE = ROOT / 'ios' / 'Runner' / 'SceneDelegate.swift'
WEB_INDEX = ROOT / 'web' / 'index.html'
WEB_MANIFEST = ROOT / 'web' / 'manifest.json'

ANDROID_PERMISSIONS = ['android.permission.INTERNET', 'android.permission.CAMERA']

DEEPLINK_META = '<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />'
ANDROID_FILTERS = f'''            <!-- JastipKita deep links (tool/configure_native.py) -->
            {DEEPLINK_META}
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/app" />
                <data android:scheme="https" android:host="{WEB_HOST}" android:pathPrefix="/jastipkita/r" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="jastipkita" />
            </intent-filter>'''

IOS_ENTRIES = {
    'NSCameraUsageDescription': '<string>Kamera dipakai untuk memindai QR serah terima, memotret barang, struk, dan dokumen verifikasi.</string>',
    'NSPhotoLibraryUsageDescription': '<string>Galeri dipakai untuk memilih foto produk, struk, dan bukti sengketa.</string>',
    'FlutterDeepLinkingEnabled': '<true/>',
    'CFBundleURLTypes': f'''<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>{APP_ID}</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>jastipkita</string>
			</array>
		</dict>
	</array>''',
}


class Report:
    def __init__(self, check_only: bool) -> None:
        self.check_only = check_only
        self.changed: list[str] = []
        self.problems: list[str] = []
        self.ok: list[str] = []

    def write(self, path: Path, old: str, new: str) -> None:
        name = str(path.relative_to(ROOT))
        if old == new:
            self.ok.append(name)
            return
        if self.check_only:
            self.problems.append(f'{name} is not configured')
            return
        path.write_text(new, encoding='utf-8')
        self.changed.append(name)


def _set_plist_string(plist: str, key: str, value: str) -> str:
    pattern = re.compile(r'(<key>' + re.escape(key) + r'</key>\s*<string>)[^<]*(</string>)')
    if pattern.search(plist):
        return pattern.sub(lambda m: f'{m.group(1)}{value}{m.group(2)}', plist, count=1)
    index = plist.rfind('</dict>')
    return plist[:index] + f'\t<key>{key}</key>\n\t<string>{value}</string>\n' + plist[index:]


def android_manifest(report: Report) -> None:
    if not MANIFEST.is_file():
        report.problems.append('android/app/src/main/AndroidManifest.xml not found (run flutter create first)')
        return
    original = MANIFEST.read_text(encoding='utf-8')
    xml = original
    for permission in ANDROID_PERMISSIONS:
        if f'android:name="{permission}"' not in xml:
            start = xml.find('<application')
            if start < 0:
                break
            line_start = xml.rfind('\n', 0, start) + 1
            indent = xml[line_start:start] if xml[line_start:start].strip() == '' else '    '
            xml = xml[:line_start] + f'{indent}<uses-permission android:name="{permission}" />\n' + xml[line_start:]
    application = re.search(r'<application\b[^>]*>', xml, re.S)
    if application:
        tag = application.group(0)
        if 'android:label=' in tag:
            new_tag = re.sub(r'android:label="[^"]*"', f'android:label="{APP_NAME}"', tag, count=1)
        else:
            new_tag = tag.replace('<application', f'<application\n        android:label="{APP_NAME}"', 1)
        xml = xml.replace(tag, new_tag, 1)
    else:
        report.problems.append('AndroidManifest.xml has no <application> element')
    activity = re.search(r'<activity\b(?:(?!</activity>).)*?android:name="(?:\.|[\w.]+\.)MainActivity"(?:(?!</activity>).)*?</activity>', xml, re.S)
    if not activity:
        report.problems.append('MainActivity not found in AndroidManifest.xml; deep links not added')
    else:
        block = activity.group(0)
        patched = block
        if 'flutter_deeplinking_enabled' in patched:
            patched = re.sub(
                r'(android:name="flutter_deeplinking_enabled"\s+android:value=")false(")',
                r'\1true\2',
                patched,
            )
        if 'android:scheme="jastipkita"' not in patched:
            filters = ANDROID_FILTERS if 'flutter_deeplinking_enabled' not in patched else ANDROID_FILTERS.replace(f'            {DEEPLINK_META}\n', '')
            patched = re.sub(r'\n[ \t]*</activity>$', '\n' + filters + '\n        </activity>', patched)
        xml = xml.replace(block, patched, 1)
    report.write(MANIFEST, original, xml)


def android_gradle(report: Report) -> None:
    gradle = next((g for g in GRADLE_FILES if g.is_file()), None)
    if gradle is None:
        report.problems.append('android/app/build.gradle(.kts) not found')
        return
    original = gradle.read_text(encoding='utf-8')
    text = original
    if gradle.suffix == '.kts':
        text = re.sub(r'(applicationId\s*=\s*")[^"]*(")', rf'\g<1>{APP_ID}\g<2>', text)
        text = re.sub(r'(namespace\s*=\s*")[^"]*(")', rf'\g<1>{APP_ID}\g<2>', text)
    else:
        text = re.sub(r'(applicationId\s*[=\s]\s*["\'])[^"\']*(["\'])', rf'\g<1>{APP_ID}\g<2>', text)
        text = re.sub(r'(namespace\s*[=\s]\s*["\'])[^"\']*(["\'])', rf'\g<1>{APP_ID}\g<2>', text)
    if APP_ID not in text:
        report.problems.append(f'{gradle.relative_to(ROOT)}: applicationId not found')
    if text != original:
        activity = list((ROOT / 'android' / 'app' / 'src' / 'main').rglob('MainActivity.*'))
        if activity and f'package {APP_ID}' not in activity[0].read_text(encoding='utf-8'):
            report.problems.append(
                f'{activity[0].relative_to(ROOT)} is not in package {APP_ID}: re-run flutter create with --org com.antarkitaindonesia',
            )
    report.write(gradle, original, text)


def ios_plist(report: Report) -> None:
    if not PLIST.is_file():
        report.problems.append('ios/Runner/Info.plist not found (run flutter create first)')
        return
    original = PLIST.read_text(encoding='utf-8')
    if original.rfind('</dict>') < 0:
        report.problems.append('Info.plist has no root </dict>')
        return
    plist = _set_plist_string(original, 'CFBundleDisplayName', APP_NAME)
    plist = _set_plist_string(plist, 'CFBundleName', APP_NAME)
    additions = ''
    for key, value in IOS_ENTRIES.items():
        if f'<key>{key}</key>' not in plist:
            additions += f'\t<key>{key}</key>\n\t{value}\n'
    if additions:
        index = plist.rfind('</dict>')
        plist = plist[:index] + additions + plist[index:]
    report.write(PLIST, original, plist)
    if SCENE_DELEGATE.is_file() and 'UIApplicationSceneManifest' not in plist:
        report.problems.append('SceneDelegate.swift exists but Info.plist has no UIApplicationSceneManifest')


def ios_bundle_id(report: Report) -> None:
    if not PBXPROJ.is_file():
        report.problems.append('ios/Runner.xcodeproj/project.pbxproj not found')
        return
    original = PBXPROJ.read_text(encoding='utf-8')

    def fix(match: re.Match[str]) -> str:
        value = match.group(2).strip('"')
        wanted = f'{APP_ID}.RunnerTests' if value.endswith('.RunnerTests') else APP_ID
        return f'{match.group(1)}{wanted};'

    text = re.sub(r'(PRODUCT_BUNDLE_IDENTIFIER = )([^;]+);', fix, original)
    report.write(PBXPROJ, original, text)


def web(report: Report) -> None:
    if WEB_INDEX.is_file():
        original = WEB_INDEX.read_text(encoding='utf-8')
        html = re.sub(r'<title>[^<]*</title>', f'<title>{APP_NAME}</title>', original, count=1)
        html = re.sub(r'(<meta name="apple-mobile-web-app-title" content=")[^"]*(")', rf'\g<1>{APP_NAME}\g<2>', html, count=1)
        report.write(WEB_INDEX, original, html)
    if WEB_MANIFEST.is_file():
        original = WEB_MANIFEST.read_text(encoding='utf-8')
        try:
            data = json.loads(original)
        except json.JSONDecodeError:
            report.problems.append('web/manifest.json is not valid JSON')
            return
        data['name'] = APP_NAME
        data['short_name'] = APP_NAME
        updated = json.dumps(data, indent=4, ensure_ascii=False) + '\n'
        report.write(WEB_MANIFEST, original, original if json.loads(original) == data else updated)


def main(argv: list[str]) -> int:
    report = Report(check_only='--check' in argv)
    android_manifest(report)
    android_gradle(report)
    ios_plist(report)
    ios_bundle_id(report)
    web(report)
    for name in report.changed:
        print(f'updated: {name}')
    for name in report.ok:
        print(f'ok: {name}')
    for problem in report.problems:
        print(f'problem: {problem}')
    return 1 if report.problems else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
