import { z } from '@hono/zod-openapi';

export const ProfileSchema = z
  .object({
    id: z.string().uuid(),
    email: z.string().nullable().openapi({ description: 'Login e-mail (Google/Apple/e-mail OTP). Not necessarily the transaction e-mail.' }),
    emailVerified: z.boolean(),
    phone: z.string().nullable().openapi({ example: '+6281234567890' }),
    phoneVerified: z.boolean(),
    displayName: z.string().nullable(),
    avatarFileId: z.string().uuid().nullable(),
    locale: z.enum(['id', 'en']),
    countryCode: z.string().nullable(),
    status: z.enum(['ACTIVE', 'SUSPENDED', 'PENDING_DELETION', 'DELETED']),
    kycLevel: z.number().int().min(1).max(5),
    activeMode: z.enum(['BUYER', 'TRAVELER']),
    trustScore: z.number().int(),
    referralCode: z.string(),
    transactionEmail: z.string().nullable().openapi({ description: 'Verified e-mail for receipts/transaction mail (OTP-verified)' }),
    roles: z.array(z.string()),
    mfaEnabled: z.boolean(),
    deletionScheduledFor: z.string().nullable(),
    createdAt: z.string(),
  })
  .openapi('Profile');
export type Profile = z.infer<typeof ProfileSchema>;

export const PendingVerificationSchema = z
  .object({
    challengeId: z.string().uuid(),
    channel: z.literal('EMAIL'),
    purpose: z.literal('VERIFY_EMAIL'),
    expiresAt: z.string(),
    devCode: z.string().optional().openapi({ description: 'Only when OTP_DEV_ECHO=true (development/test)' }),
  })
  .openapi('PendingVerification');

export const PatchMeBody = z
  .object({
    displayName: z.string().trim().min(1).max(80).nullable().optional(),
    locale: z.enum(['id', 'en']).optional(),
    countryCode: z.string().regex(/^[A-Z]{2}$/).nullable().optional(),
    transactionEmail: z.string().email().max(254).nullable().optional().openapi({
      description: 'Changing it sends an e-mail OTP to the new address; it is applied after POST /v1/auth/otp/verify',
    }),
    avatarFileId: z.string().uuid().nullable().optional(),
  })
  .strict()
  .openapi('PatchMe');

export const PatchMeResponse = z
  .object({ user: ProfileSchema, pendingVerification: PendingVerificationSchema.nullable() })
  .openapi('PatchMeResponse');

export const ModeBody = z.object({ mode: z.enum(['BUYER', 'TRAVELER']) }).openapi('SwitchMode');

export const DeviceInputSchema = z
  .object({
    platform: z.enum(['IOS', 'ANDROID', 'WEB']),
    fingerprint: z
      .string()
      .min(16)
      .max(256)
      .openapi({ description: 'Stable per-install identifier generated by the app. Only its HMAC is stored.' }),
    pushToken: z.string().min(10).max(4096).nullable().optional(),
    appVersion: z.string().max(40).optional(),
    osVersion: z.string().max(40).optional(),
  })
  .openapi('DeviceInput');
export type DeviceInput = z.infer<typeof DeviceInputSchema>;

export const DeviceSchema = z
  .object({
    id: z.string().uuid(),
    platform: z.enum(['IOS', 'ANDROID', 'WEB']),
    appVersion: z.string().nullable(),
    osVersion: z.string().nullable(),
    pushEnabled: z.boolean(),
    firstSeenAt: z.string(),
    lastSeenAt: z.string(),
  })
  .openapi('Device');

export const CONSENT_TYPES = ['TOS', 'PRIVACY', 'KYC', 'MARKETING', 'COOKIES', 'TRAVELER_AGREEMENT', 'PAYMENT_TERMS'] as const;
export const ConsentInputSchema = z
  .object({
    type: z.enum(CONSENT_TYPES),
    version: z.string().regex(/^[0-9A-Za-z._-]{1,40}$/).openapi({ example: '2026-09' }),
    granted: z.boolean().default(true),
  })
  .openapi('ConsentInput');
export type ConsentInput = z.infer<typeof ConsentInputSchema>;

export const ConsentSchema = z
  .object({
    id: z.number().int(),
    type: z.enum(CONSENT_TYPES),
    version: z.string(),
    granted: z.boolean(),
    source: z.string(),
    createdAt: z.string(),
  })
  .openapi('Consent');

export const ConsentsResponse = z
  .object({
    current: z.array(z.object({ type: z.enum(CONSENT_TYPES), version: z.string(), granted: z.boolean(), decidedAt: z.string() })),
    history: z.array(ConsentSchema),
    requiredAtSignup: z.array(z.enum(CONSENT_TYPES)),
  })
  .openapi('Consents');

export const OkSchema = z.object({ ok: z.literal(true) }).openapi('Ok');
