#!/usr/bin/env node
// @jastipkita/design-tokens build — plain Node (≥ 18), zero dependencies.
//
//   node scripts/build.mjs            build + WCAG check (exit 1 if any declared pair fails AA)
//   node scripts/build.mjs --check    only run the contrast check
//
// Inputs : tokens.json
// Outputs: dist/tokens.css, dist/tokens.ts, dist/tokens.resolved.json, CONTRAST.md,
//          ../../apps/mobile/lib/core/design/tokens.g.dart
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.resolve(here, '..');
const REPO = path.resolve(PKG, '..', '..');
const DART_OUT = path.join(REPO, 'apps', 'mobile', 'lib', 'core', 'design', 'tokens.g.dart');
const args = new Set(process.argv.slice(2));
const T = JSON.parse(readFileSync(path.join(PKG, 'tokens.json'), 'utf8'));
const THEMES = ['light', 'dark'];
const HEADER = 'GENERATED by packages/design-tokens/scripts/build.mjs from tokens.json — DO NOT EDIT BY HAND.';

// ------------------------------------------------------------------------------------------
// Colour resolution
// ------------------------------------------------------------------------------------------
const P = T.color.primitive;
function primitiveHex(ref) {
  const [fam, step] = ref.split('.');
  const v = step === undefined ? P[fam] : P[fam]?.[step];
  if (typeof v !== 'string') throw new Error(`Unknown colour reference "${ref}"`);
  return v;
}
function hexToRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}
/** → { r, g, b, a, hex, ref } */
function resolveColor(v) {
  if (typeof v === 'string') {
    const m = v.match(/^\{(.+)\}$/);
    const hex = m ? primitiveHex(m[1]) : v;
    return { ...hexToRgb(hex), a: 1, hex: hex.toUpperCase(), ref: m ? m[1] : null };
  }
  if (v && v.$ref) {
    const hex = primitiveHex(v.$ref);
    return { ...hexToRgb(hex), a: v.alpha ?? 1, hex: hex.toUpperCase(), ref: v.$ref };
  }
  throw new Error(`Bad colour value ${JSON.stringify(v)}`);
}
const mapObj = (o, f) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, f(v, k)]));
const resolveTones = (group) => mapObj(group, (tones) => mapObj(tones, (tone) => mapObj(tone, resolveColor)));

const R = {
  semantic: mapObj(T.color.semantic, (theme) => mapObj(theme, resolveColor)),
  status: resolveTones(T.color.status),
  trust: resolveTones(T.color.trust),
  kyc: resolveTones(T.color.kyc),
  elevation: Object.fromEntries(
    THEMES.map((th) => [
      th,
      mapObj(
        Object.fromEntries(Object.entries(T.elevation[th])),
        (layers) => layers.map((l) => ({ ...l, color: resolveColor(l.color) })),
      ),
    ]),
  ),
};

// ------------------------------------------------------------------------------------------
// WCAG contrast
// ------------------------------------------------------------------------------------------
const lin = (c) => {
  const s = c / 255;
  return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
};
const lum = ({ r, g, b }) => 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
const over = (fg, bg) => ({
  r: Math.round(fg.a * fg.r + (1 - fg.a) * bg.r),
  g: Math.round(fg.a * fg.g + (1 - fg.a) * bg.g),
  b: Math.round(fg.a * fg.b + (1 - fg.a) * bg.b),
  a: 1,
});
const ratio = (fg, bg) => {
  const f = fg.a < 1 ? over(fg, bg) : fg;
  const a = lum(f);
  const b = lum(bg);
  return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
};
const hexOf = (c) => '#' + [c.r, c.g, c.b].map((x) => x.toString(16).padStart(2, '0')).join('').toUpperCase();
const REQUIRED = { text: 4.5, large: 3, ui: 3 };

function contrastPairs(theme) {
  const S = R.semantic[theme];
  const pairs = [];
  const add = (fgName, bgName, kind = 'text', fg = S[fgName], bg = S[bgName]) => pairs.push({ fgName, bgName, kind, fg, bg });
  // Text on neutral surfaces
  add('onBackground', 'background');
  add('onBackgroundMuted', 'background');
  for (const bg of ['surface', 'surfaceMuted', 'surfaceElevated']) add('onSurface', bg);
  for (const bg of ['surface', 'surfaceMuted', 'surfaceElevated']) add('onSurfaceMuted', bg);
  add('onSurfaceInverse', 'surfaceInverse');
  // Glass: text over the translucent layer, composited over the page background and over the
  // two extremes of whatever content may scroll beneath (white photo / near-black photo).
  for (const [label, under] of [
    ['background', S.background],
    ['white content', resolveColor('{white}')],
    ['black content', resolveColor('{black}')],
  ]) {
    const glass = over(S.surfaceGlass, under);
    for (const fgName of ['onGlass', 'onGlassMuted', 'onGlassActive']) {
      pairs.push({ fgName, bgName: `surfaceGlass over ${label}`, kind: 'text', fg: S[fgName], bg: { ...glass, hex: hexOf(glass) } });
    }

  }
  // Brand roles
  add('onPrimary', 'primary');
  add('onPrimaryContainer', 'primaryContainer');
  add('onSecondary', 'secondary');
  add('onSecondaryContainer', 'secondaryContainer');
  add('onCta', 'cta');
  add('onCta', 'ctaPressed');
  for (const bg of ['background', 'surface', 'surfaceMuted', 'surfaceElevated']) add('link', bg);
  // Feedback roles
  for (const x of ['success', 'warning', 'error', 'info']) {
    const X = x[0].toUpperCase() + x.slice(1);
    add(`on${X}`, x);
    add(`on${X}Container`, `${x}Container`);
    for (const bg of ['background', 'surface', 'surfaceElevated']) add(`${x}Text`, bg);
  }
  add('onSafepaySecured', 'safepaySecured');
  add('onSafepayBlocked', 'safepayBlocked');
  add('onSafepayPending', 'safepayPending');
  add('onEstimateBadge', 'estimateBadge');
  // Non-text (WCAG 1.4.11): focus ring, input outline, indicator icons
  for (const bg of ['background', 'surface', 'surfaceElevated']) add('focusRing', bg, 'ui');
  for (const bg of ['background', 'surface', 'surfaceElevated']) add('outline', bg, 'ui');
  for (const x of ['success', 'error', 'info']) for (const bg of ['background', 'surface']) add(x, bg, 'ui');
  add('cta', 'background', 'ui');
  add('cta', 'surface', 'ui');
  // Tonal badges
  for (const [family, groups] of [['status', R.status], ['trust', R.trust], ['kyc', R.kyc]]) {
    for (const [name, tone] of Object.entries(groups[theme])) {
      pairs.push({ fgName: `${family}.${name}.fg`, bgName: `${family}.${name}.bg`, kind: 'text', fg: tone.fg, bg: tone.bg });
      pairs.push({ fgName: `${family}.${name}.dot`, bgName: `${family}.${name}.bg`, kind: 'ui', fg: tone.dot, bg: tone.bg, advisory: true });
    }
  }
  return pairs.map((p) => {
    const r = ratio(p.fg, p.bg);
    const need = REQUIRED[p.kind];
    return { ...p, ratio: r, need, pass: r >= need };
  });
}

function contrastReport() {
  const lines = [
    `<!-- ${HEADER} -->`,
    '# JastipKita — WCAG 2.2 contrast report',
    '',
    'Generated by `node packages/design-tokens/scripts/build.mjs` from `tokens.json`. Thresholds: **text 4.5:1** (AA normal text), **ui 3:1** (AA non-text: focus rings, input outlines, indicator icons). Translucent colours are composited over their background before measuring. Rows marked *advisory* are decorative dots always paired with a text label (not a WCAG requirement) and never fail the build.',
    '',
  ];
  let failures = 0;
  const summary = {};
  for (const th of THEMES) {
    const rows = contrastPairs(th);
    const hard = rows.filter((r) => !r.advisory);
    const fails = hard.filter((r) => !r.pass);
    failures += fails.length;
    summary[th] = { total: hard.length, pass: hard.length - fails.length, min: Math.min(...hard.map((r) => r.ratio)) };
    lines.push(`## ${th === 'light' ? 'Light' : 'Dark'} theme — ${hard.length - fails.length}/${hard.length} required pairs pass`, '');
    lines.push('| Foreground | on Background | FG | BG | Ratio | Need | Result |', '|---|---|---|---|---:|---:|---|');
    for (const r of rows) {
      const fg = r.fg.a < 1 ? `${r.fg.hex} @${Math.round(r.fg.a * 100)}%` : r.fg.hex;
      const bgHex = r.bg.hex ?? hexOf(r.bg);
      const res = r.advisory ? (r.pass ? 'pass (advisory)' : 'advisory') : r.pass ? 'PASS' : '**FAIL**';
      lines.push(`| \`${r.fgName}\` | \`${r.bgName}\` | ${fg} | ${bgHex} | ${r.ratio.toFixed(2)}:1 | ${r.need}:1 ${r.kind} | ${res} |`);
    }
    lines.push('');
  }
  return { md: lines.join('\n'), failures, summary };
}

// ------------------------------------------------------------------------------------------
// Emitters
// ------------------------------------------------------------------------------------------
const kebab = (s) => s.replace(/_/g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const cssColor = (c) => (c.a >= 1 ? c.hex : `rgba(${c.r}, ${c.g}, ${c.b}, ${+c.a.toFixed(3)})`);
const shadowCss = (layers) =>
  layers.length ? layers.map((l) => `${l.x}px ${l.y}px ${l.blur}px ${l.spread}px ${cssColor(l.color)}`).join(', ') : 'none';

function emitCss() {
  const out = [`/* ${HEADER} */`, '/* Usage: import "@jastipkita/design-tokens/tokens.css"; set <html data-theme="light|dark"> or let prefers-color-scheme decide. */', ''];
  const root = [];
  for (const [fam, v] of Object.entries(P)) {
    if (typeof v === 'string') root.push(`  --jk-color-${fam}: ${v};`);
    else for (const [step, hex] of Object.entries(v)) root.push(`  --jk-color-${fam}-${step}: ${hex};`);
  }
  root.push('');
  for (const [k, v] of Object.entries(T.spacing)) root.push(`  --jk-space-${k.replace('_', '-')}: ${v}px;`);
  for (const [k, v] of Object.entries(T.radius)) root.push(`  --jk-radius-${k}: ${v}px;`);
  root.push('');
  root.push(`  --jk-font-family: ${T.typography.fontFamily.fallbackWeb};`);
  for (const [k, v] of Object.entries(T.typography.weight)) root.push(`  --jk-font-weight-${k}: ${v};`);
  for (const [k, s] of Object.entries(T.typography.scale)) {
    const n = kebab(k);
    root.push(`  --jk-type-${n}-size: ${s.size / 16}rem;`);
    root.push(`  --jk-type-${n}-line-height: ${+(s.lineHeight / s.size).toFixed(4)};`);
    root.push(`  --jk-type-${n}-weight: ${s.weight};`);
    root.push(`  --jk-type-${n}-tracking: ${s.letterSpacing}em;`);
  }
  root.push('');
  for (const [k, v] of Object.entries(T.motion.duration)) root.push(`  --jk-duration-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(T.motion.easing)) root.push(`  --jk-ease-${kebab(k)}: cubic-bezier(${v.join(', ')});`);
  root.push(`  --jk-glass-blur: ${T.glass.blurSigma}px;`);
  root.push(`  --jk-glass-saturation: ${T.glass.saturation};`);
  root.push(`  --jk-glass-border-width: ${T.glass.borderWidth}px;`);
  for (const [k, v] of Object.entries(T.opacity)) root.push(`  --jk-opacity-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(T.touchTarget)) root.push(`  --jk-touch-target-${kebab(k)}: ${v}px;`);
  for (const [k, v] of Object.entries(T.iconSize)) root.push(`  --jk-icon-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(T.zIndex)) root.push(`  --jk-z-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(T.breakpoint)) root.push(`  --jk-breakpoint-${kebab(k)}: ${v}px; /* media queries cannot read vars — use the literal */`);
  root.push(`  --jk-content-max-width: ${T.layout.contentMaxWidth}px;`);
  root.push(`  --jk-reading-max-width: ${T.layout.readingMaxWidth}px;`);
  out.push(':root {', ...root, '}', '');

  const themeBlock = (th) => {
    const l = [`  color-scheme: ${th};`];
    for (const [k, c] of Object.entries(R.semantic[th])) l.push(`  --jk-color-${kebab(k)}: ${cssColor(c)};`);
    for (const [fam, groups] of [['status', R.status], ['trust', R.trust], ['kyc', R.kyc]]) {
      for (const [name, tone] of Object.entries(groups[th])) {
        for (const [part, c] of Object.entries(tone)) l.push(`  --jk-${fam}-${kebab(name)}-${part}: ${cssColor(c)};`);
      }
    }
    for (const [lv, layers] of Object.entries(R.elevation[th])) l.push(`  --jk-elevation-${kebab(lv)}: ${shadowCss(layers)};`);
    l.push(`  --jk-glass-opacity: ${T.glass.opacity[th]};`);
    return l;
  };
  out.push(':root,', '[data-theme="light"] {', ...themeBlock('light'), '}', '');
  out.push('@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', ...themeBlock('dark').map((l) => '  ' + l), '  }', '}', '');
  out.push('[data-theme="dark"] {', ...themeBlock('dark'), '}', '');
  out.push(
    '/* Reduce motion: spatial motion off, cross-fades capped at the fast duration. */',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    `    --jk-duration-base: ${T.motion.reduceMotion.crossfadeMax}ms;`,
    `    --jk-duration-slow: ${T.motion.reduceMotion.crossfadeMax}ms;`,
    `    --jk-duration-emphasized: ${T.motion.reduceMotion.crossfadeMax}ms;`,
    '    --jk-motion-reduce: 1;',
    '  }',
    '}',
    '',
  );
  // Utilities
  out.push('/* Typography utilities */');
  for (const [k, s] of Object.entries(T.typography.scale)) {
    const n = kebab(k);
    out.push(
      `.jk-text-${n} { font-family: var(--jk-font-family); font-size: var(--jk-type-${n}-size); line-height: var(--jk-type-${n}-line-height); font-weight: var(--jk-type-${n}-weight); letter-spacing: var(--jk-type-${n}-tracking);${s.tabular ? ' font-feature-settings: "tnum" 1; font-variant-numeric: tabular-nums;' : ''} }`,
    );
  }
  out.push('.jk-tabular { font-feature-settings: "tnum" 1; font-variant-numeric: tabular-nums; }', '');
  out.push(
    '/* Glass — ONLY for navigation/control layers (tab bar, toolbar, floating controls). Never behind price breakdowns, payment status or receipts. */',
    '.jk-glass {',
    '  background: var(--jk-color-surface-glass);',
    '  -webkit-backdrop-filter: blur(var(--jk-glass-blur)) saturate(var(--jk-glass-saturation));',
    '  backdrop-filter: blur(var(--jk-glass-blur)) saturate(var(--jk-glass-saturation));',
    '  border: var(--jk-glass-border-width) solid var(--jk-color-glass-border);',
    '}',
    '@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) { .jk-glass { background: var(--jk-color-surface-elevated); } }',
    '@media (prefers-reduced-transparency: reduce), (prefers-contrast: more) { .jk-glass { background: var(--jk-color-surface-elevated); -webkit-backdrop-filter: none; backdrop-filter: none; } }',
    '',
    '/* Focus ring */',
    '.jk-focus-ring:focus-visible { outline: 2px solid var(--jk-color-focus-ring); outline-offset: 2px; }',
    '',
  );
  return out.join('\n');
}

function plainTones(group) {
  return mapObj(group, (tones) => mapObj(tones, (tone) => mapObj(tone, cssColor)));
}

function emitTs() {
  const resolved = {
    color: {
      primitive: P,
      light: mapObj(R.semantic.light, cssColor),
      dark: mapObj(R.semantic.dark, cssColor),
      status: plainTones(R.status),
      trust: plainTones(R.trust),
      kyc: plainTones(R.kyc),
    },
    transactionStatusGroup: T.transactionStatusGroup,
    trustTier: T.trustTier,
    typography: T.typography,
    spacing: T.spacing,
    radius: T.radius,
    elevation: { light: mapObj(R.elevation.light, shadowCss), dark: mapObj(R.elevation.dark, shadowCss) },
    motion: T.motion,
    glass: T.glass,
    opacity: T.opacity,
    breakpoint: T.breakpoint,
    layout: T.layout,
    touchTarget: T.touchTarget,
    iconSize: T.iconSize,
    zIndex: T.zIndex,
  };
  const semanticKeys = Object.keys(R.semantic.light);
  const cssVars = Object.fromEntries(semanticKeys.map((k) => [k, `var(--jk-color-${kebab(k)})`]));
  return `// ${HEADER}
/* eslint-disable */

export const tokens = ${JSON.stringify(resolved, null, 2)} as const;

export type Tokens = typeof tokens;
export type ThemeName = 'light' | 'dark';
export type SemanticColor = keyof typeof tokens.color.light;
export type StatusGroup = keyof typeof tokens.color.status.light;
export type TrustTier = keyof typeof tokens.trustTier;
export type KycLevelKey = keyof typeof tokens.color.kyc.light;
export type TransactionStatus = keyof typeof tokens.transactionStatusGroup;
export type TypeScaleName = keyof typeof tokens.typography.scale;

/** CSS custom-property references for semantic colours (theme-aware at runtime). */
export const colorVar: Record<SemanticColor, string> = ${JSON.stringify(cssVars, null, 2)};

export function statusGroupOf(status: TransactionStatus): StatusGroup {
  return tokens.transactionStatusGroup[status] as StatusGroup;
}

export function trustTierOf(score: number): TrustTier {
  const s = Math.max(0, Math.min(100, Math.round(score)));
  for (const [tier, r] of Object.entries(tokens.trustTier) as [TrustTier, { min: number; max: number }][]) {
    if (s >= r.min && s <= r.max) return tier;
  }
  return 'low';
}

export function statusTone(status: TransactionStatus, theme: ThemeName = 'light') {
  return tokens.color.status[theme][statusGroupOf(status)];
}

export default tokens;
`;
}

// ---- Dart --------------------------------------------------------------------------------
const dartColor = (c) => {
  const a = Math.round(c.a * 255);
  return `Color(0x${[a, c.r, c.g, c.b].map((x) => x.toString(16).padStart(2, '0')).join('').toUpperCase()})`;
};
const dartId = (s) => s.replace(/[^A-Za-z0-9]/g, '_');
const dartNum = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);

function emitDart() {
  const sem = Object.keys(R.semantic.light);
  const toneMap = (groups, th) =>
    `{\n${Object.entries(groups[th])
      .map(([k, t]) => `      '${k}': JkTone(fg: ${dartColor(t.fg)}, bg: ${dartColor(t.bg)}, dot: ${dartColor(t.dot)}),`)
      .join('\n')}\n    }`;
  const colorsInstance = (th) =>
    `  static const JkColors ${th} = JkColors(\n    brightness: Brightness.${th},\n${sem
      .map((k) => `    ${k}: ${dartColor(R.semantic[th][k])},`)
      .join('\n')}\n    status: ${toneMap(R.status, th)},\n    trust: ${toneMap(R.trust, th)},\n    kyc: ${toneMap(R.kyc, th)},\n  );`;

  const palette = [];
  for (const [fam, v] of Object.entries(P)) {
    if (typeof v === 'string') palette.push(`  static const Color ${fam} = ${dartColor(resolveColor(v))};`);
    else for (const [step, hex] of Object.entries(v)) palette.push(`  static const Color ${fam}${step} = ${dartColor(resolveColor(hex))};`);
  }

  const shadows = (th) =>
    Object.entries(R.elevation[th])
      .map(
        ([lv, layers]) =>
          `  static const List<BoxShadow> ${lv}${th === 'light' ? 'Light' : 'Dark'} = <BoxShadow>[${layers
            .map(
              (l) =>
                `BoxShadow(offset: Offset(${dartNum(l.x)}, ${dartNum(l.y)}), blurRadius: ${dartNum(l.blur)}, spreadRadius: ${dartNum(l.spread)}, color: ${dartColor(l.color)})`,
            )
            .join(', ')}];`,
      )
      .join('\n');

  const typeStyles = Object.entries(T.typography.scale)
    .map(([k, s]) => {
      const w = `FontWeight.w${s.weight}`;
      const ls = +(s.letterSpacing * s.size).toFixed(3);
      const feat = s.tabular ? `\n    fontFeatures: <ui.FontFeature>[ui.FontFeature.tabularFigures()],` : '';
      return `  static const TextStyle ${k} = TextStyle(\n    fontFamily: fontFamily,\n    fontSize: ${dartNum(s.size)},\n    height: ${+(s.lineHeight / s.size).toFixed(4)},\n    fontWeight: ${w},\n    letterSpacing: ${dartNum(ls)},\n    leadingDistribution: TextLeadingDistribution.even,${feat}\n  );`;
    })
    .join('\n\n');

  const spacing = Object.entries(T.spacing)
    .map(([k, v]) => `  static const double s${k} = ${dartNum(v)};`)
    .join('\n');
  const radii = Object.entries(T.radius)
    .map(([k, v]) => `  static const double ${k} = ${dartNum(v)};\n  static const BorderRadius ${k}All = BorderRadius.all(Radius.circular(${dartNum(v)}));`)
    .join('\n');
  const durations = Object.entries(T.motion.duration)
    .map(([k, v]) => `  static const Duration ${k} = Duration(milliseconds: ${v});`)
    .join('\n');
  const easings = Object.entries(T.motion.easing)
    .map(([k, v]) => `  static const Cubic ${k} = Cubic(${v.map(dartNum).join(', ')});`)
    .join('\n');
  const springs = Object.entries(T.motion.spring)
    .map(
      ([k, v]) =>
        `  static final SpringDescription ${k}Spring = SpringDescription.withDampingRatio(mass: 1.0, stiffness: ${dartNum(v.stiffness)}, ratio: ${dartNum(v.dampingRatio)});`,
    )
    .join('\n');
  const statusGroupMap = Object.entries(T.transactionStatusGroup)
    .map(([k, v]) => `    '${k}': '${v}',`)
    .join('\n');
  const tiers = Object.entries(T.trustTier)
    .map(([k, r]) => `    if (s >= ${r.min} && s <= ${r.max}) return '${k}';`)
    .join('\n');

  const copyWithParams = sem.map((k) => `    Color? ${k},`).join('\n');
  const copyWithBody = sem.map((k) => `      ${k}: ${k} ?? this.${k},`).join('\n');
  const lerpBody = sem.map((k) => `      ${k}: Color.lerp(${k}, other.${k}, t)!,`).join('\n');

  return `// ${HEADER}
// Source: packages/design-tokens/tokens.json
// ignore_for_file: constant_identifier_names, non_constant_identifier_names, lines_longer_than_80_chars, public_member_api_docs

import 'dart:ui' as ui show FontFeature;

import 'package:flutter/material.dart';

/// Raw brand palette. Prefer [JkColors] (semantic, theme-aware) in widgets.
abstract final class JkPalette {
${palette.join('\n')}
}

/// Foreground / background / indicator triple for tonal badges (status, trust, KYC).
@immutable
class JkTone {
  const JkTone({required this.fg, required this.bg, required this.dot});
  final Color fg;
  final Color bg;
  final Color dot;

  static JkTone lerp(JkTone a, JkTone b, double t) => JkTone(
        fg: Color.lerp(a.fg, b.fg, t)!,
        bg: Color.lerp(a.bg, b.bg, t)!,
        dot: Color.lerp(a.dot, b.dot, t)!,
      );
}

/// Semantic colours for light & dark. Register both in ThemeData.extensions and read with
/// \`Theme.of(context).extension<JkColors>()!\` (or the \`context.jk\` helper in theme code).
@immutable
class JkColors extends ThemeExtension<JkColors> {
  const JkColors({
    required this.brightness,
${sem.map((k) => `    required this.${k},`).join('\n')}
    required this.status,
    required this.trust,
    required this.kyc,
  });

  final Brightness brightness;
${sem.map((k) => `  final Color ${k};`).join('\n')}

  /// Transaction status group → tone. Keys: ${Object.keys(T.color.status.light).join(', ')}.
  final Map<String, JkTone> status;

  /// Trust score tier → tone. Keys: ${Object.keys(T.color.trust.light).join(', ')}.
  final Map<String, JkTone> trust;

  /// KYC level → tone. Keys: ${Object.keys(T.color.kyc.light).join(', ')}.
  final Map<String, JkTone> kyc;

${colorsInstance('light')}

${colorsInstance('dark')}

  JkTone statusTone(String transactionStatus) => status[JkStatus.groupOf(transactionStatus)] ?? status['closed']!;
  JkTone trustTone(int score) => trust[JkStatus.trustTierOf(score)]!;
  JkTone kycTone(int level) => kyc['level\${level.clamp(1, 5)}']!;

  @override
  JkColors copyWith({
    Brightness? brightness,
${copyWithParams}
    Map<String, JkTone>? status,
    Map<String, JkTone>? trust,
    Map<String, JkTone>? kyc,
  }) {
    return JkColors(
      brightness: brightness ?? this.brightness,
${copyWithBody}
      status: status ?? this.status,
      trust: trust ?? this.trust,
      kyc: kyc ?? this.kyc,
    );
  }

  static Map<String, JkTone> _lerpTones(Map<String, JkTone> a, Map<String, JkTone> b, double t) =>
      <String, JkTone>{for (final k in a.keys) k: JkTone.lerp(a[k]!, b[k] ?? a[k]!, t)};

  @override
  JkColors lerp(ThemeExtension<JkColors>? other, double t) {
    if (other is! JkColors) return this;
    return JkColors(
      brightness: t < 0.5 ? brightness : other.brightness,
${lerpBody}
      status: _lerpTones(status, other.status, t),
      trust: _lerpTones(trust, other.trust, t),
      kyc: _lerpTones(kyc, other.kyc, t),
    );
  }
}

/// Transaction status → colour group, trust score → tier (mirrors docs/00-domain-model.md).
abstract final class JkStatus {
  static const Map<String, String> transactionStatusGroup = <String, String>{
${statusGroupMap}
  };

  static String groupOf(String transactionStatus) => transactionStatusGroup[transactionStatus] ?? 'closed';

  static String trustTierOf(int score) {
    final s = score.clamp(0, 100);
${tiers}
    return 'low';
  }
}

/// 4-pt spacing grid. s1 = 4, s2 = 8, s4 = 16 …
abstract final class JkSpacing {
${spacing}
}

abstract final class JkRadii {
${radii}
}

abstract final class JkElevation {
${shadows('light')}
${shadows('dark')}
}

/// Durations & curves. Always check \`MediaQuery.disableAnimationsOf(context)\`: when true use
/// a cross-fade of at most [reducedCrossfade] instead of spatial motion.
abstract final class JkMotion {
${durations}
  static const Duration reducedCrossfade = Duration(milliseconds: ${T.motion.reduceMotion.crossfadeMax});
${easings}
${springs}
}

/// Glass is ONLY for navigation/control layers (tab bar, toolbar, floating controls).
/// Never behind price breakdowns, payment status, SafePay banners or receipts.
abstract final class JkGlass {
  static const double blurSigma = ${dartNum(T.glass.blurSigma)};
  static const double saturation = ${dartNum(T.glass.saturation)};
  static const double opacityLight = ${dartNum(T.glass.opacity.light)};
  static const double opacityDark = ${dartNum(T.glass.opacity.dark)};
  static const double borderWidth = ${dartNum(T.glass.borderWidth)};
}

abstract final class JkTouchTarget {
  static const double ios = ${dartNum(T.touchTarget.ios)};
  static const double android = ${dartNum(T.touchTarget.android)};
  static const double minSpacing = ${dartNum(T.touchTarget.minSpacing)};
}

abstract final class JkBreakpoints {
${Object.entries(T.breakpoint).map(([k, v]) => `  static const double ${k} = ${dartNum(v)};`).join('\n')}
}

abstract final class JkOpacity {
${Object.entries(T.opacity).map(([k, v]) => `  static const double ${k} = ${dartNum(v)};`).join('\n')}
}

/// Poppins type scale. Sizes are logical pixels; they scale with the user's text scaler
/// (support up to 2.0×). Money styles use tabular figures.
abstract final class JkTypeScale {
  static const String fontFamily = '${T.typography.fontFamily.brand}';

${typeStyles}
}
`;
}

// ------------------------------------------------------------------------------------------
function write(file, content) {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log('  wrote', path.relative(REPO, file));
}

const report = contrastReport();
if (!args.has('--check')) {
  write(path.join(PKG, 'dist', 'tokens.css'), emitCss());
  write(path.join(PKG, 'dist', 'tokens.ts'), emitTs());
  write(path.join(PKG, 'dist', 'tokens.resolved.json'), JSON.stringify(JSON.parse(emitTs().split('export const tokens = ')[1].split(' as const;')[0]), null, 2) + '\n');
  write(DART_OUT, emitDart());
}
write(path.join(PKG, 'CONTRAST.md'), report.md + '\n');
// Keep the UI design-system doc in sync (content between the CONTRAST-REPORT markers).
const DOC = path.join(REPO, 'docs', '05-ui-design-system.md');
try {
  const doc = readFileSync(DOC, 'utf8');
  const START = '<!-- CONTRAST-REPORT:START -->';
  const END = '<!-- CONTRAST-REPORT:END -->';
  if (doc.includes(START) && doc.includes(END)) {
    const body = report.md
      .split('\n')
      .filter((l) => !l.startsWith('<!--') && !l.startsWith('# '))
      .map((l) => (l.startsWith('## ') ? '#' + l : l))
      .join('\n')
      .trim();
    const next = doc.slice(0, doc.indexOf(START) + START.length) + '\n' + body + '\n' + doc.slice(doc.indexOf(END));
    if (next !== doc) write(DOC, next);
  }
} catch {
  /* doc optional */
}
for (const th of THEMES) {
  const s = report.summary[th];
  console.log(`  contrast ${th}: ${s.pass}/${s.total} pass (lowest ${s.min.toFixed(2)}:1)`);
}
if (report.failures > 0) {
  console.error(`✗ ${report.failures} contrast pair(s) below WCAG AA — see CONTRAST.md`);
  process.exit(1);
}
console.log('✓ all declared text/background pairs meet WCAG AA');
