// GENERATED by apps/api/scripts/gen-migration-manifest.ts — DO NOT EDIT BY HAND.
// SHA-256 of each db/migrations/*.sql (raw bytes), identical to schema_migrations.checksum written by db/scripts/migrate.sh.
// Regenerate after adding a migration: cd apps/api && npx tsx scripts/gen-migration-manifest.ts

export interface MigrationManifestEntry {
  version: string;
  name: string;
  file: string;
  checksum: string;
}

export const MIGRATION_MANIFEST: readonly MigrationManifestEntry[] = [
  { version: '0001', name: 'foundation', file: '0001_foundation.sql', checksum: '166bd7898c72612c278e8d771fbc16f789bf8e31afa453e584d96b244de3a6a7' },
  { version: '0002', name: 'reference', file: '0002_reference.sql', checksum: 'a1dfc2852d33ac654424b87505f2eae60e586e256f4474a2b2e315c6e0ba53bc' },
  { version: '0003', name: 'identity_access', file: '0003_identity_access.sql', checksum: 'f569580e436b5d53271333d421640cdeccc7851874c383b2afe40ddabaec0643' },
  { version: '0004', name: 'audit_outbox_jobs', file: '0004_audit_outbox_jobs.sql', checksum: 'aaacac803f1ca1b4e86e3399b2d1649174b894facdfd4c266f8a4d91f9e85c55' },
  { version: '0005', name: 'config_rules', file: '0005_config_rules.sql', checksum: '9cc306b984061369ef69606fc333dcacbdf5b129c3e3253854f4765db74889ad' },
  { version: '0006', name: 'kyc', file: '0006_kyc.sql', checksum: 'c5a114cce82353f348d9b330750d7d312d0d9d68df83d85a9ae13f39fe5167ea' },
  { version: '0007', name: 'trips_requests', file: '0007_trips_requests.sql', checksum: '17cd7a0a757204415e54013d6f55143621d6d63393247289ca47e828dc1f28c0' },
  { version: '0008', name: 'transactions', file: '0008_transactions.sql', checksum: '55a8f95875ba7e5fbf252f6ab8a90a8ef7d587471960bb4bc69d12a804638a51' },
  { version: '0009', name: 'payments_ledger', file: '0009_payments_ledger.sql', checksum: '1195f7a2501eb1d82a3306ee5c27d1345ac288ca83aa854bbba19809d3288520' },
  { version: '0010', name: 'growth', file: '0010_growth.sql', checksum: 'c0bbbbae03571a29651ee05aae34ee0da9f5063ae959f1a8d52b8f880931603d' },
  { version: '0011', name: 'trust_risk', file: '0011_trust_risk.sql', checksum: '3834a0c6554722278e55a026ef3d1a03876464669b159f4a56d046f79da0b946' },
  { version: '0012', name: 'communication', file: '0012_communication.sql', checksum: '9e338750796cbd61c182da4fbd6f3b826cb6d52da56502967f512ffd37582282' },
  { version: '0013', name: 'disputes_support', file: '0013_disputes_support.sql', checksum: 'e82b4f7ff26988a65818f60888d3543b7b03930c77a0bce6a503e195a46aa843' },
  { version: '0014', name: 'privacy_ops', file: '0014_privacy_ops.sql', checksum: 'b303f8055f1516759a2622e3c33d400d0da86341572090691900ccfd2dbf6e56' },
  { version: '0015', name: 'analytics_views', file: '0015_analytics_views.sql', checksum: 'c1643ac26eaba80e6a510d56f351d65cbbade62c6b4a8fe168f08e7b83cf2a7a' },
  { version: '0016', name: 'roles_grants', file: '0016_roles_grants.sql', checksum: 'ed1de053c61b742c21d69e8575561df7029180ebf500760119fee070c1c3dd76' },
  { version: '0017', name: 'spec_alignment', file: '0017_spec_alignment.sql', checksum: '2f0a6e8b256bca624577dbf581862e2b143cba8d871142c8c2af394362051097' },
  { version: '0018', name: 'outbox_handler_runs', file: '0018_outbox_handler_runs.sql', checksum: 'e1efd27faf8a99bdc337d9d30453ae584780923a72f095d28e397b8a0f5ac5b4' },
  { version: '0020', name: 'identity_runtime', file: '0020_identity_runtime.sql', checksum: '1935290c384396a468792468ec06b170ed87c22e1181f8e20bc1924faf89739c' },
  { version: '0030', name: 'marketplace_capacity', file: '0030_marketplace_capacity.sql', checksum: 'a7e542fcd20b4125624c6244e7c94b1b3f2e891bc56936baa5be647d96de448f' },
  { version: '0040', name: 'money', file: '0040_money.sql', checksum: '5c7c3234bfecfaac275b81f802243daf07624321a07d9fd676de486ebf7c5827' },
  { version: '0050', name: 'engagement', file: '0050_engagement.sql', checksum: '7e9e94d19f651f15b6b8e9066703a1a25fd10eb84cea78aad75f86be7a3b82b8' },
  { version: '0060', name: 'admin', file: '0060_admin.sql', checksum: '85b9ca778a381d3b9f55499d08ca819f9f75ad547050d384ae44109b6afed3fb' },
  { version: '0070', name: 'legal_public_documents', file: '0070_legal_public_documents.sql', checksum: 'c76428f49f7d550e0191aa6a03172842e0fdb0e0da99306bf4d874a07bbbe14f' },
  { version: '0080', name: 'security_hardening', file: '0080_security_hardening.sql', checksum: 'ba6bb0d907c33fbf53d3dc2a39d07ec5648171581c9ba294f1b7cd7a38f448cf' },
  { version: '0090', name: 'qa_security_followups', file: '0090_qa_security_followups.sql', checksum: 'a3eb2ceef378767e7d4948a2612f665206f54766a4f45272ba608076b52237df' },
];
