// GENERATED by packages/design-tokens/scripts/build.mjs from tokens.json — DO NOT EDIT BY HAND.
// Source: packages/design-tokens/tokens.json
// ignore_for_file: constant_identifier_names, non_constant_identifier_names, lines_longer_than_80_chars, public_member_api_docs

import 'dart:ui' as ui show FontFeature;

import 'package:flutter/material.dart';
import 'package:flutter/physics.dart' show SpringDescription;

/// Raw brand palette. Prefer [JkColors] (semantic, theme-aware) in widgets.
abstract final class JkPalette {
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color offwhite50 = Color(0xFFF7F8FB);
  static const Color ink900 = Color(0xFF0F172A);
  static const Color navy50 = Color(0xFFEEF2FA);
  static const Color navy100 = Color(0xFFDCE4F4);
  static const Color navy200 = Color(0xFFB9C8E8);
  static const Color navy300 = Color(0xFF8DA3D1);
  static const Color navy400 = Color(0xFF5E77B0);
  static const Color navy500 = Color(0xFF3D5690);
  static const Color navy600 = Color(0xFF294378);
  static const Color navy700 = Color(0xFF173068);
  static const Color navy800 = Color(0xFF12295F);
  static const Color navy900 = Color(0xFF0B1E4A);
  static const Color navy925 = Color(0xFF0D1631);
  static const Color navy950 = Color(0xFF070B19);
  static const Color cobalt50 = Color(0xFFEEF3FF);
  static const Color cobalt100 = Color(0xFFDCE6FF);
  static const Color cobalt200 = Color(0xFFBCCEFF);
  static const Color cobalt300 = Color(0xFF8CA9FF);
  static const Color cobalt400 = Color(0xFF4D7DFF);
  static const Color cobalt500 = Color(0xFF1E5BFF);
  static const Color cobalt600 = Color(0xFF0F47E6);
  static const Color cobalt700 = Color(0xFF0B38B8);
  static const Color cobalt800 = Color(0xFF0E308F);
  static const Color cobalt900 = Color(0xFF112B6F);
  static const Color cobalt950 = Color(0xFF0B1A42);
  static const Color slate50 = Color(0xFFF8FAFC);
  static const Color slate100 = Color(0xFFF1F5F9);
  static const Color slate200 = Color(0xFFE2E8F0);
  static const Color slate300 = Color(0xFFCBD5E1);
  static const Color slate400 = Color(0xFF94A3B8);
  static const Color slate450 = Color(0xFF8391A7);
  static const Color slate500 = Color(0xFF64748B);
  static const Color slate600 = Color(0xFF475569);
  static const Color slate700 = Color(0xFF334155);
  static const Color slate800 = Color(0xFF1E293B);
  static const Color slate900 = Color(0xFF0F172A);
  static const Color slate950 = Color(0xFF020617);
  static const Color emerald50 = Color(0xFFECFDF5);
  static const Color emerald100 = Color(0xFFD1FAE5);
  static const Color emerald200 = Color(0xFFA7F3D0);
  static const Color emerald300 = Color(0xFF6EE7B7);
  static const Color emerald400 = Color(0xFF34D399);
  static const Color emerald500 = Color(0xFF10B981);
  static const Color emerald600 = Color(0xFF059669);
  static const Color emerald700 = Color(0xFF047857);
  static const Color emerald800 = Color(0xFF065F46);
  static const Color emerald900 = Color(0xFF064E3B);
  static const Color emerald950 = Color(0xFF022C22);
  static const Color orange50 = Color(0xFFFFF7ED);
  static const Color orange100 = Color(0xFFFFEDD5);
  static const Color orange200 = Color(0xFFFED7AA);
  static const Color orange300 = Color(0xFFFDBA74);
  static const Color orange400 = Color(0xFFFB923C);
  static const Color orange500 = Color(0xFFF97316);
  static const Color orange600 = Color(0xFFEA580C);
  static const Color orange700 = Color(0xFFC2410C);
  static const Color orange800 = Color(0xFF9A3412);
  static const Color orange900 = Color(0xFF7C2D12);
  static const Color orange950 = Color(0xFF431407);
  static const Color red50 = Color(0xFFFEF2F2);
  static const Color red100 = Color(0xFFFEE2E2);
  static const Color red200 = Color(0xFFFECACA);
  static const Color red300 = Color(0xFFFCA5A5);
  static const Color red400 = Color(0xFFF87171);
  static const Color red500 = Color(0xFFEF4444);
  static const Color red600 = Color(0xFFDC2626);
  static const Color red700 = Color(0xFFB91C1C);
  static const Color red800 = Color(0xFF991B1B);
  static const Color red900 = Color(0xFF7F1D1D);
  static const Color red950 = Color(0xFF450A0A);
  static const Color violet50 = Color(0xFFF5F3FF);
  static const Color violet100 = Color(0xFFEDE9FE);
  static const Color violet200 = Color(0xFFDDD6FE);
  static const Color violet300 = Color(0xFFC4B5FD);
  static const Color violet400 = Color(0xFFA78BFA);
  static const Color violet500 = Color(0xFF8B5CF6);
  static const Color violet600 = Color(0xFF7C3AED);
  static const Color violet700 = Color(0xFF6D28D9);
  static const Color violet800 = Color(0xFF5B21B6);
  static const Color violet900 = Color(0xFF4C1D95);
  static const Color violet950 = Color(0xFF2E1065);
  static const Color teal50 = Color(0xFFF0FDFA);
  static const Color teal100 = Color(0xFFCCFBF1);
  static const Color teal200 = Color(0xFF99F6E4);
  static const Color teal300 = Color(0xFF5EEAD4);
  static const Color teal400 = Color(0xFF2DD4BF);
  static const Color teal500 = Color(0xFF14B8A6);
  static const Color teal600 = Color(0xFF0D9488);
  static const Color teal700 = Color(0xFF0F766E);
  static const Color teal800 = Color(0xFF115E59);
  static const Color teal900 = Color(0xFF134E4A);
  static const Color teal950 = Color(0xFF042F2E);
  static const Color sky50 = Color(0xFFF0F9FF);
  static const Color sky100 = Color(0xFFE0F2FE);
  static const Color sky200 = Color(0xFFBAE6FD);
  static const Color sky300 = Color(0xFF7DD3FC);
  static const Color sky400 = Color(0xFF38BDF8);
  static const Color sky500 = Color(0xFF0EA5E9);
  static const Color sky600 = Color(0xFF0284C7);
  static const Color sky700 = Color(0xFF0369A1);
  static const Color sky800 = Color(0xFF075985);
  static const Color sky900 = Color(0xFF0C4A6E);
  static const Color sky950 = Color(0xFF082F49);
  static const Color amber50 = Color(0xFFFFFBEB);
  static const Color amber100 = Color(0xFFFEF3C7);
  static const Color amber200 = Color(0xFFFDE68A);
  static const Color amber300 = Color(0xFFFCD34D);
  static const Color amber400 = Color(0xFFFBBF24);
  static const Color amber500 = Color(0xFFF59E0B);
  static const Color amber600 = Color(0xFFD97706);
  static const Color amber700 = Color(0xFFB45309);
  static const Color amber800 = Color(0xFF92400E);
  static const Color amber900 = Color(0xFF78350F);
  static const Color amber950 = Color(0xFF451A03);
}

/// Foreground / background / indicator triple for tonal badges (status, trust, KYC).
@immutable
class JkTone {
  const JkTone({required this.fg, required this.bg, required this.dot});
  final Color fg;
  final Color bg;
  final Color dot;

  static JkTone lerp(JkTone a, JkTone b, double t) => JkTone(
        fg: Color.lerp(a.fg, b.fg, t)!,
        bg: Color.lerp(a.bg, b.bg, t)!,
        dot: Color.lerp(a.dot, b.dot, t)!,
      );
}

/// Semantic colours for light & dark. Register both in ThemeData.extensions and read with
/// `Theme.of(context).extension<JkColors>()!` (or the `context.jk` helper in theme code).
@immutable
class JkColors extends ThemeExtension<JkColors> {
  const JkColors({
    required this.brightness,
    required this.background,
    required this.onBackground,
    required this.onBackgroundMuted,
    required this.surface,
    required this.surfaceMuted,
    required this.surfaceElevated,
    required this.surfaceGlass,
    required this.onGlass,
    required this.onGlassMuted,
    required this.onGlassActive,
    required this.surfaceInverse,
    required this.onSurface,
    required this.onSurfaceMuted,
    required this.onSurfaceInverse,
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.cta,
    required this.ctaPressed,
    required this.onCta,
    required this.link,
    required this.border,
    required this.outline,
    required this.divider,
    required this.focusRing,
    required this.scrim,
    required this.disabledContent,
    required this.disabledContainer,
    required this.glassBorder,
    required this.glassShadow,
    required this.success,
    required this.onSuccess,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.successText,
    required this.warning,
    required this.onWarning,
    required this.warningContainer,
    required this.onWarningContainer,
    required this.warningText,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.errorText,
    required this.info,
    required this.onInfo,
    required this.infoContainer,
    required this.onInfoContainer,
    required this.infoText,
    required this.safepaySecured,
    required this.onSafepaySecured,
    required this.safepayBlocked,
    required this.onSafepayBlocked,
    required this.safepayPending,
    required this.onSafepayPending,
    required this.estimateBadge,
    required this.onEstimateBadge,
    required this.status,
    required this.trust,
    required this.kyc,
  });

  final Brightness brightness;
  final Color background;
  final Color onBackground;
  final Color onBackgroundMuted;
  final Color surface;
  final Color surfaceMuted;
  final Color surfaceElevated;
  final Color surfaceGlass;
  final Color onGlass;
  final Color onGlassMuted;
  final Color onGlassActive;
  final Color surfaceInverse;
  final Color onSurface;
  final Color onSurfaceMuted;
  final Color onSurfaceInverse;
  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color cta;
  final Color ctaPressed;
  final Color onCta;
  final Color link;
  final Color border;
  final Color outline;
  final Color divider;
  final Color focusRing;
  final Color scrim;
  final Color disabledContent;
  final Color disabledContainer;
  final Color glassBorder;
  final Color glassShadow;
  final Color success;
  final Color onSuccess;
  final Color successContainer;
  final Color onSuccessContainer;
  final Color successText;
  final Color warning;
  final Color onWarning;
  final Color warningContainer;
  final Color onWarningContainer;
  final Color warningText;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color errorText;
  final Color info;
  final Color onInfo;
  final Color infoContainer;
  final Color onInfoContainer;
  final Color infoText;
  final Color safepaySecured;
  final Color onSafepaySecured;
  final Color safepayBlocked;
  final Color onSafepayBlocked;
  final Color safepayPending;
  final Color onSafepayPending;
  final Color estimateBadge;
  final Color onEstimateBadge;

  /// Transaction status group → tone. Keys: open, actionRequired, secured, inTransit, delivered, completed, disputed, refund, closed.
  final Map<String, JkTone> status;

  /// Trust score tier → tone. Keys: low, fair, good, excellent.
  final Map<String, JkTone> trust;

  /// KYC level → tone. Keys: level1, level2, level3, level4, level5.
  final Map<String, JkTone> kyc;

  static const JkColors light = JkColors(
    brightness: Brightness.light,
    background: Color(0xFFF7F8FB),
    onBackground: Color(0xFF0F172A),
    onBackgroundMuted: Color(0xFF475569),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF8FAFC),
    surfaceElevated: Color(0xFFFFFFFF),
    surfaceGlass: Color(0xCCFFFFFF),
    onGlass: Color(0xFF0F172A),
    onGlassMuted: Color(0xFF475569),
    onGlassActive: Color(0xFF0B38B8),
    surfaceInverse: Color(0xFF0B1E4A),
    onSurface: Color(0xFF0F172A),
    onSurfaceMuted: Color(0xFF64748B),
    onSurfaceInverse: Color(0xFFF7F8FB),
    primary: Color(0xFF0B1E4A),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEEF2FA),
    onPrimaryContainer: Color(0xFF0B1E4A),
    secondary: Color(0xFF1E5BFF),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEEF3FF),
    onSecondaryContainer: Color(0xFF0E308F),
    cta: Color(0xFF1E5BFF),
    ctaPressed: Color(0xFF0F47E6),
    onCta: Color(0xFFFFFFFF),
    link: Color(0xFF1E5BFF),
    border: Color(0xFFE2E8F0),
    outline: Color(0xFF8391A7),
    divider: Color(0xFFE2E8F0),
    focusRing: Color(0xFF1E5BFF),
    scrim: Color(0x7A070B19),
    disabledContent: Color(0xFF94A3B8),
    disabledContainer: Color(0xFFF1F5F9),
    glassBorder: Color(0x99FFFFFF),
    glassShadow: Color(0x140B1E4A),
    success: Color(0xFF059669),
    onSuccess: Color(0xFF0F172A),
    successContainer: Color(0xFFECFDF5),
    onSuccessContainer: Color(0xFF065F46),
    successText: Color(0xFF047857),
    warning: Color(0xFFF97316),
    onWarning: Color(0xFF0F172A),
    warningContainer: Color(0xFFFFF7ED),
    onWarningContainer: Color(0xFF9A3412),
    warningText: Color(0xFFC2410C),
    error: Color(0xFFDC2626),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFEF2F2),
    onErrorContainer: Color(0xFF991B1B),
    errorText: Color(0xFFB91C1C),
    info: Color(0xFF1E5BFF),
    onInfo: Color(0xFFFFFFFF),
    infoContainer: Color(0xFFEEF3FF),
    onInfoContainer: Color(0xFF0E308F),
    infoText: Color(0xFF0F47E6),
    safepaySecured: Color(0xFF047857),
    onSafepaySecured: Color(0xFFFFFFFF),
    safepayBlocked: Color(0xFFDC2626),
    onSafepayBlocked: Color(0xFFFFFFFF),
    safepayPending: Color(0xFFF97316),
    onSafepayPending: Color(0xFF0F172A),
    estimateBadge: Color(0xFFFFFBEB),
    onEstimateBadge: Color(0xFF92400E),
    status: {
      'open': JkTone(fg: Color(0xFF0E308F), bg: Color(0xFFEEF3FF), dot: Color(0xFF1E5BFF)),
      'actionRequired': JkTone(fg: Color(0xFF9A3412), bg: Color(0xFFFFF7ED), dot: Color(0xFFF97316)),
      'secured': JkTone(fg: Color(0xFF065F46), bg: Color(0xFFECFDF5), dot: Color(0xFF059669)),
      'inTransit': JkTone(fg: Color(0xFF5B21B6), bg: Color(0xFFF5F3FF), dot: Color(0xFF7C3AED)),
      'delivered': JkTone(fg: Color(0xFF115E59), bg: Color(0xFFF0FDFA), dot: Color(0xFF0D9488)),
      'completed': JkTone(fg: Color(0xFF064E3B), bg: Color(0xFFD1FAE5), dot: Color(0xFF047857)),
      'disputed': JkTone(fg: Color(0xFF991B1B), bg: Color(0xFFFEF2F2), dot: Color(0xFFDC2626)),
      'refund': JkTone(fg: Color(0xFF075985), bg: Color(0xFFF0F9FF), dot: Color(0xFF0284C7)),
      'closed': JkTone(fg: Color(0xFF334155), bg: Color(0xFFF1F5F9), dot: Color(0xFF64748B)),
    },
    trust: {
      'low': JkTone(fg: Color(0xFF991B1B), bg: Color(0xFFFEF2F2), dot: Color(0xFFDC2626)),
      'fair': JkTone(fg: Color(0xFF9A3412), bg: Color(0xFFFFF7ED), dot: Color(0xFFF97316)),
      'good': JkTone(fg: Color(0xFF0E308F), bg: Color(0xFFEEF3FF), dot: Color(0xFF1E5BFF)),
      'excellent': JkTone(fg: Color(0xFF065F46), bg: Color(0xFFECFDF5), dot: Color(0xFF059669)),
    },
    kyc: {
      'level1': JkTone(fg: Color(0xFF334155), bg: Color(0xFFF1F5F9), dot: Color(0xFF64748B)),
      'level2': JkTone(fg: Color(0xFF075985), bg: Color(0xFFF0F9FF), dot: Color(0xFF0284C7)),
      'level3': JkTone(fg: Color(0xFF0E308F), bg: Color(0xFFEEF3FF), dot: Color(0xFF1E5BFF)),
      'level4': JkTone(fg: Color(0xFF0B1E4A), bg: Color(0xFFEEF2FA), dot: Color(0xFF173068)),
      'level5': JkTone(fg: Color(0xFF92400E), bg: Color(0xFFFFFBEB), dot: Color(0xFFF59E0B)),
    },
  );

  static const JkColors dark = JkColors(
    brightness: Brightness.dark,
    background: Color(0xFF070B19),
    onBackground: Color(0xFFF7F8FB),
    onBackgroundMuted: Color(0xFF94A3B8),
    surface: Color(0xFF0D1631),
    surfaceMuted: Color(0xFF0B1E4A),
    surfaceElevated: Color(0xFF12295F),
    surfaceGlass: Color(0xCC12295F),
    onGlass: Color(0xFFF7F8FB),
    onGlassMuted: Color(0xFFCBD5E1),
    onGlassActive: Color(0xFFBCCEFF),
    surfaceInverse: Color(0xFFF7F8FB),
    onSurface: Color(0xFFF7F8FB),
    onSurfaceMuted: Color(0xFF94A3B8),
    onSurfaceInverse: Color(0xFF0B1E4A),
    primary: Color(0xFFDCE4F4),
    onPrimary: Color(0xFF0B1E4A),
    primaryContainer: Color(0xFF12295F),
    onPrimaryContainer: Color(0xFFDCE4F4),
    secondary: Color(0xFF4D7DFF),
    onSecondary: Color(0xFF070B19),
    secondaryContainer: Color(0xFF112B6F),
    onSecondaryContainer: Color(0xFFDCE6FF),
    cta: Color(0xFF4D7DFF),
    ctaPressed: Color(0xFF8CA9FF),
    onCta: Color(0xFF070B19),
    link: Color(0xFF8CA9FF),
    border: Color(0xFF12295F),
    outline: Color(0xFF5E77B0),
    divider: Color(0xFF12295F),
    focusRing: Color(0xFF4D7DFF),
    scrim: Color(0x99000000),
    disabledContent: Color(0xFF64748B),
    disabledContainer: Color(0xFF0B1E4A),
    glassBorder: Color(0x1FFFFFFF),
    glassShadow: Color(0x66000000),
    success: Color(0xFF34D399),
    onSuccess: Color(0xFF070B19),
    successContainer: Color(0xFF022C22),
    onSuccessContainer: Color(0xFFA7F3D0),
    successText: Color(0xFF6EE7B7),
    warning: Color(0xFFFB923C),
    onWarning: Color(0xFF070B19),
    warningContainer: Color(0xFF431407),
    onWarningContainer: Color(0xFFFED7AA),
    warningText: Color(0xFFFDBA74),
    error: Color(0xFFF87171),
    onError: Color(0xFF070B19),
    errorContainer: Color(0xFF450A0A),
    onErrorContainer: Color(0xFFFECACA),
    errorText: Color(0xFFFCA5A5),
    info: Color(0xFF4D7DFF),
    onInfo: Color(0xFF070B19),
    infoContainer: Color(0xFF0B1A42),
    onInfoContainer: Color(0xFFBCCEFF),
    infoText: Color(0xFF8CA9FF),
    safepaySecured: Color(0xFF047857),
    onSafepaySecured: Color(0xFFFFFFFF),
    safepayBlocked: Color(0xFFDC2626),
    onSafepayBlocked: Color(0xFFFFFFFF),
    safepayPending: Color(0xFFFB923C),
    onSafepayPending: Color(0xFF070B19),
    estimateBadge: Color(0xFF451A03),
    onEstimateBadge: Color(0xFFFDE68A),
    status: {
      'open': JkTone(fg: Color(0xFFBCCEFF), bg: Color(0xFF0B1A42), dot: Color(0xFF4D7DFF)),
      'actionRequired': JkTone(fg: Color(0xFFFED7AA), bg: Color(0xFF431407), dot: Color(0xFFFB923C)),
      'secured': JkTone(fg: Color(0xFFA7F3D0), bg: Color(0xFF022C22), dot: Color(0xFF34D399)),
      'inTransit': JkTone(fg: Color(0xFFDDD6FE), bg: Color(0xFF2E1065), dot: Color(0xFFA78BFA)),
      'delivered': JkTone(fg: Color(0xFF99F6E4), bg: Color(0xFF042F2E), dot: Color(0xFF2DD4BF)),
      'completed': JkTone(fg: Color(0xFFD1FAE5), bg: Color(0xFF064E3B), dot: Color(0xFF6EE7B7)),
      'disputed': JkTone(fg: Color(0xFFFECACA), bg: Color(0xFF450A0A), dot: Color(0xFFF87171)),
      'refund': JkTone(fg: Color(0xFFBAE6FD), bg: Color(0xFF082F49), dot: Color(0xFF38BDF8)),
      'closed': JkTone(fg: Color(0xFFCBD5E1), bg: Color(0xFF1E293B), dot: Color(0xFF94A3B8)),
    },
    trust: {
      'low': JkTone(fg: Color(0xFFFECACA), bg: Color(0xFF450A0A), dot: Color(0xFFF87171)),
      'fair': JkTone(fg: Color(0xFFFED7AA), bg: Color(0xFF431407), dot: Color(0xFFFB923C)),
      'good': JkTone(fg: Color(0xFFBCCEFF), bg: Color(0xFF0B1A42), dot: Color(0xFF4D7DFF)),
      'excellent': JkTone(fg: Color(0xFFA7F3D0), bg: Color(0xFF022C22), dot: Color(0xFF34D399)),
    },
    kyc: {
      'level1': JkTone(fg: Color(0xFFCBD5E1), bg: Color(0xFF1E293B), dot: Color(0xFF94A3B8)),
      'level2': JkTone(fg: Color(0xFFBAE6FD), bg: Color(0xFF082F49), dot: Color(0xFF38BDF8)),
      'level3': JkTone(fg: Color(0xFFBCCEFF), bg: Color(0xFF0B1A42), dot: Color(0xFF4D7DFF)),
      'level4': JkTone(fg: Color(0xFFDCE4F4), bg: Color(0xFF12295F), dot: Color(0xFF8DA3D1)),
      'level5': JkTone(fg: Color(0xFFFDE68A), bg: Color(0xFF451A03), dot: Color(0xFFFBBF24)),
    },
  );

  JkTone statusTone(String transactionStatus) => status[JkStatus.groupOf(transactionStatus)] ?? status['closed']!;
  JkTone trustTone(int score) => trust[JkStatus.trustTierOf(score)]!;
  JkTone kycTone(int level) => kyc['level${level.clamp(1, 5)}']!;

  @override
  JkColors copyWith({
    Brightness? brightness,
    Color? background,
    Color? onBackground,
    Color? onBackgroundMuted,
    Color? surface,
    Color? surfaceMuted,
    Color? surfaceElevated,
    Color? surfaceGlass,
    Color? onGlass,
    Color? onGlassMuted,
    Color? onGlassActive,
    Color? surfaceInverse,
    Color? onSurface,
    Color? onSurfaceMuted,
    Color? onSurfaceInverse,
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? cta,
    Color? ctaPressed,
    Color? onCta,
    Color? link,
    Color? border,
    Color? outline,
    Color? divider,
    Color? focusRing,
    Color? scrim,
    Color? disabledContent,
    Color? disabledContainer,
    Color? glassBorder,
    Color? glassShadow,
    Color? success,
    Color? onSuccess,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? successText,
    Color? warning,
    Color? onWarning,
    Color? warningContainer,
    Color? onWarningContainer,
    Color? warningText,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? errorText,
    Color? info,
    Color? onInfo,
    Color? infoContainer,
    Color? onInfoContainer,
    Color? infoText,
    Color? safepaySecured,
    Color? onSafepaySecured,
    Color? safepayBlocked,
    Color? onSafepayBlocked,
    Color? safepayPending,
    Color? onSafepayPending,
    Color? estimateBadge,
    Color? onEstimateBadge,
    Map<String, JkTone>? status,
    Map<String, JkTone>? trust,
    Map<String, JkTone>? kyc,
  }) {
    return JkColors(
      brightness: brightness ?? this.brightness,
      background: background ?? this.background,
      onBackground: onBackground ?? this.onBackground,
      onBackgroundMuted: onBackgroundMuted ?? this.onBackgroundMuted,
      surface: surface ?? this.surface,
      surfaceMuted: surfaceMuted ?? this.surfaceMuted,
      surfaceElevated: surfaceElevated ?? this.surfaceElevated,
      surfaceGlass: surfaceGlass ?? this.surfaceGlass,
      onGlass: onGlass ?? this.onGlass,
      onGlassMuted: onGlassMuted ?? this.onGlassMuted,
      onGlassActive: onGlassActive ?? this.onGlassActive,
      surfaceInverse: surfaceInverse ?? this.surfaceInverse,
      onSurface: onSurface ?? this.onSurface,
      onSurfaceMuted: onSurfaceMuted ?? this.onSurfaceMuted,
      onSurfaceInverse: onSurfaceInverse ?? this.onSurfaceInverse,
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      cta: cta ?? this.cta,
      ctaPressed: ctaPressed ?? this.ctaPressed,
      onCta: onCta ?? this.onCta,
      link: link ?? this.link,
      border: border ?? this.border,
      outline: outline ?? this.outline,
      divider: divider ?? this.divider,
      focusRing: focusRing ?? this.focusRing,
      scrim: scrim ?? this.scrim,
      disabledContent: disabledContent ?? this.disabledContent,
      disabledContainer: disabledContainer ?? this.disabledContainer,
      glassBorder: glassBorder ?? this.glassBorder,
      glassShadow: glassShadow ?? this.glassShadow,
      success: success ?? this.success,
      onSuccess: onSuccess ?? this.onSuccess,
      successContainer: successContainer ?? this.successContainer,
      onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
      successText: successText ?? this.successText,
      warning: warning ?? this.warning,
      onWarning: onWarning ?? this.onWarning,
      warningContainer: warningContainer ?? this.warningContainer,
      onWarningContainer: onWarningContainer ?? this.onWarningContainer,
      warningText: warningText ?? this.warningText,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      errorText: errorText ?? this.errorText,
      info: info ?? this.info,
      onInfo: onInfo ?? this.onInfo,
      infoContainer: infoContainer ?? this.infoContainer,
      onInfoContainer: onInfoContainer ?? this.onInfoContainer,
      infoText: infoText ?? this.infoText,
      safepaySecured: safepaySecured ?? this.safepaySecured,
      onSafepaySecured: onSafepaySecured ?? this.onSafepaySecured,
      safepayBlocked: safepayBlocked ?? this.safepayBlocked,
      onSafepayBlocked: onSafepayBlocked ?? this.onSafepayBlocked,
      safepayPending: safepayPending ?? this.safepayPending,
      onSafepayPending: onSafepayPending ?? this.onSafepayPending,
      estimateBadge: estimateBadge ?? this.estimateBadge,
      onEstimateBadge: onEstimateBadge ?? this.onEstimateBadge,
      status: status ?? this.status,
      trust: trust ?? this.trust,
      kyc: kyc ?? this.kyc,
    );
  }

  static Map<String, JkTone> _lerpTones(Map<String, JkTone> a, Map<String, JkTone> b, double t) =>
      <String, JkTone>{for (final k in a.keys) k: JkTone.lerp(a[k]!, b[k] ?? a[k]!, t)};

  @override
  JkColors lerp(ThemeExtension<JkColors>? other, double t) {
    if (other is! JkColors) return this;
    return JkColors(
      brightness: t < 0.5 ? brightness : other.brightness,
      background: Color.lerp(background, other.background, t)!,
      onBackground: Color.lerp(onBackground, other.onBackground, t)!,
      onBackgroundMuted: Color.lerp(onBackgroundMuted, other.onBackgroundMuted, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surfaceMuted: Color.lerp(surfaceMuted, other.surfaceMuted, t)!,
      surfaceElevated: Color.lerp(surfaceElevated, other.surfaceElevated, t)!,
      surfaceGlass: Color.lerp(surfaceGlass, other.surfaceGlass, t)!,
      onGlass: Color.lerp(onGlass, other.onGlass, t)!,
      onGlassMuted: Color.lerp(onGlassMuted, other.onGlassMuted, t)!,
      onGlassActive: Color.lerp(onGlassActive, other.onGlassActive, t)!,
      surfaceInverse: Color.lerp(surfaceInverse, other.surfaceInverse, t)!,
      onSurface: Color.lerp(onSurface, other.onSurface, t)!,
      onSurfaceMuted: Color.lerp(onSurfaceMuted, other.onSurfaceMuted, t)!,
      onSurfaceInverse: Color.lerp(onSurfaceInverse, other.onSurfaceInverse, t)!,
      primary: Color.lerp(primary, other.primary, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primaryContainer: Color.lerp(primaryContainer, other.primaryContainer, t)!,
      onPrimaryContainer: Color.lerp(onPrimaryContainer, other.onPrimaryContainer, t)!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      onSecondary: Color.lerp(onSecondary, other.onSecondary, t)!,
      secondaryContainer: Color.lerp(secondaryContainer, other.secondaryContainer, t)!,
      onSecondaryContainer: Color.lerp(onSecondaryContainer, other.onSecondaryContainer, t)!,
      cta: Color.lerp(cta, other.cta, t)!,
      ctaPressed: Color.lerp(ctaPressed, other.ctaPressed, t)!,
      onCta: Color.lerp(onCta, other.onCta, t)!,
      link: Color.lerp(link, other.link, t)!,
      border: Color.lerp(border, other.border, t)!,
      outline: Color.lerp(outline, other.outline, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      focusRing: Color.lerp(focusRing, other.focusRing, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
      disabledContent: Color.lerp(disabledContent, other.disabledContent, t)!,
      disabledContainer: Color.lerp(disabledContainer, other.disabledContainer, t)!,
      glassBorder: Color.lerp(glassBorder, other.glassBorder, t)!,
      glassShadow: Color.lerp(glassShadow, other.glassShadow, t)!,
      success: Color.lerp(success, other.success, t)!,
      onSuccess: Color.lerp(onSuccess, other.onSuccess, t)!,
      successContainer: Color.lerp(successContainer, other.successContainer, t)!,
      onSuccessContainer: Color.lerp(onSuccessContainer, other.onSuccessContainer, t)!,
      successText: Color.lerp(successText, other.successText, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      onWarning: Color.lerp(onWarning, other.onWarning, t)!,
      warningContainer: Color.lerp(warningContainer, other.warningContainer, t)!,
      onWarningContainer: Color.lerp(onWarningContainer, other.onWarningContainer, t)!,
      warningText: Color.lerp(warningText, other.warningText, t)!,
      error: Color.lerp(error, other.error, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
      onErrorContainer: Color.lerp(onErrorContainer, other.onErrorContainer, t)!,
      errorText: Color.lerp(errorText, other.errorText, t)!,
      info: Color.lerp(info, other.info, t)!,
      onInfo: Color.lerp(onInfo, other.onInfo, t)!,
      infoContainer: Color.lerp(infoContainer, other.infoContainer, t)!,
      onInfoContainer: Color.lerp(onInfoContainer, other.onInfoContainer, t)!,
      infoText: Color.lerp(infoText, other.infoText, t)!,
      safepaySecured: Color.lerp(safepaySecured, other.safepaySecured, t)!,
      onSafepaySecured: Color.lerp(onSafepaySecured, other.onSafepaySecured, t)!,
      safepayBlocked: Color.lerp(safepayBlocked, other.safepayBlocked, t)!,
      onSafepayBlocked: Color.lerp(onSafepayBlocked, other.onSafepayBlocked, t)!,
      safepayPending: Color.lerp(safepayPending, other.safepayPending, t)!,
      onSafepayPending: Color.lerp(onSafepayPending, other.onSafepayPending, t)!,
      estimateBadge: Color.lerp(estimateBadge, other.estimateBadge, t)!,
      onEstimateBadge: Color.lerp(onEstimateBadge, other.onEstimateBadge, t)!,
      status: _lerpTones(status, other.status, t),
      trust: _lerpTones(trust, other.trust, t),
      kyc: _lerpTones(kyc, other.kyc, t),
    );
  }
}

/// Transaction status → colour group, trust score → tier (mirrors docs/00-domain-model.md).
abstract final class JkStatus {
  static const Map<String, String> transactionStatusGroup = <String, String>{
    'REQUEST_CREATED': 'open',
    'MATCHED': 'open',
    'AWAITING_PAYMENT': 'actionRequired',
    'PRICE_CHANGE_PENDING': 'actionRequired',
    'PAYMENT_SECURED': 'secured',
    'PURCHASE_APPROVED': 'secured',
    'PURCHASED': 'inTransit',
    'TRAVELING': 'inTransit',
    'ARRIVED': 'inTransit',
    'CUSTOMS_PROCESS': 'inTransit',
    'READY_FOR_HANDOVER': 'inTransit',
    'OUT_FOR_DELIVERY': 'inTransit',
    'DELIVERED': 'delivered',
    'BUYER_CONFIRMED': 'delivered',
    'COMPLETED': 'completed',
    'DISPUTED': 'disputed',
    'REFUND_PENDING': 'refund',
    'REFUNDED': 'closed',
    'CANCELLED': 'closed',
  };

  static String groupOf(String transactionStatus) => transactionStatusGroup[transactionStatus] ?? 'closed';

  static String trustTierOf(int score) {
    final s = score.clamp(0, 100);
    if (s >= 0 && s <= 39) return 'low';
    if (s >= 40 && s <= 69) return 'fair';
    if (s >= 70 && s <= 84) return 'good';
    if (s >= 85 && s <= 100) return 'excellent';
    return 'low';
  }
}

/// 4-pt spacing grid. s1 = 4, s2 = 8, s4 = 16 …
abstract final class JkSpacing {
  static const double s0 = 0.0;
  static const double s1 = 4.0;
  static const double s2 = 8.0;
  static const double s3 = 12.0;
  static const double s4 = 16.0;
  static const double s5 = 20.0;
  static const double s6 = 24.0;
  static const double s8 = 32.0;
  static const double s10 = 40.0;
  static const double s12 = 48.0;
  static const double s16 = 64.0;
  static const double s20 = 80.0;
  static const double s0_5 = 2.0;
}

abstract final class JkRadii {
  static const double none = 0.0;
  static const BorderRadius noneAll = BorderRadius.all(Radius.circular(0.0));
  static const double xs = 6.0;
  static const BorderRadius xsAll = BorderRadius.all(Radius.circular(6.0));
  static const double sm = 10.0;
  static const BorderRadius smAll = BorderRadius.all(Radius.circular(10.0));
  static const double md = 14.0;
  static const BorderRadius mdAll = BorderRadius.all(Radius.circular(14.0));
  static const double lg = 20.0;
  static const BorderRadius lgAll = BorderRadius.all(Radius.circular(20.0));
  static const double xl = 28.0;
  static const BorderRadius xlAll = BorderRadius.all(Radius.circular(28.0));
  static const double pill = 999.0;
  static const BorderRadius pillAll = BorderRadius.all(Radius.circular(999.0));
}

abstract final class JkElevation {
  static const List<BoxShadow> level0Light = <BoxShadow>[];
  static const List<BoxShadow> level1Light = <BoxShadow>[BoxShadow(offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: 0.0, color: Color(0x0F0B1E4A)), BoxShadow(offset: Offset(0.0, 1.0), blurRadius: 3.0, spreadRadius: 0.0, color: Color(0x140B1E4A))];
  static const List<BoxShadow> level2Light = <BoxShadow>[BoxShadow(offset: Offset(0.0, 4.0), blurRadius: 12.0, spreadRadius: -2.0, color: Color(0x1A0B1E4A)), BoxShadow(offset: Offset(0.0, 2.0), blurRadius: 4.0, spreadRadius: 0.0, color: Color(0x0F0B1E4A))];
  static const List<BoxShadow> level3Light = <BoxShadow>[BoxShadow(offset: Offset(0.0, 12.0), blurRadius: 28.0, spreadRadius: -6.0, color: Color(0x290B1E4A)), BoxShadow(offset: Offset(0.0, 4.0), blurRadius: 8.0, spreadRadius: 0.0, color: Color(0x0F0B1E4A))];
  static const List<BoxShadow> level4Light = <BoxShadow>[BoxShadow(offset: Offset(0.0, 24.0), blurRadius: 48.0, spreadRadius: -12.0, color: Color(0x3D0B1E4A)), BoxShadow(offset: Offset(0.0, 8.0), blurRadius: 16.0, spreadRadius: 0.0, color: Color(0x140B1E4A))];
  static const List<BoxShadow> level0Dark = <BoxShadow>[];
  static const List<BoxShadow> level1Dark = <BoxShadow>[BoxShadow(offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: 0.0, color: Color(0x66000000))];
  static const List<BoxShadow> level2Dark = <BoxShadow>[BoxShadow(offset: Offset(0.0, 4.0), blurRadius: 12.0, spreadRadius: -2.0, color: Color(0x73000000))];
  static const List<BoxShadow> level3Dark = <BoxShadow>[BoxShadow(offset: Offset(0.0, 12.0), blurRadius: 28.0, spreadRadius: -6.0, color: Color(0x80000000))];
  static const List<BoxShadow> level4Dark = <BoxShadow>[BoxShadow(offset: Offset(0.0, 24.0), blurRadius: 48.0, spreadRadius: -12.0, color: Color(0x99000000))];
}

/// Durations & curves. Always check `MediaQuery.disableAnimationsOf(context)`: when true use
/// a cross-fade of at most [reducedCrossfade] instead of spatial motion.
abstract final class JkMotion {
  static const Duration instant = Duration(milliseconds: 0);
  static const Duration fast = Duration(milliseconds: 120);
  static const Duration base = Duration(milliseconds: 200);
  static const Duration slow = Duration(milliseconds: 300);
  static const Duration emphasized = Duration(milliseconds: 450);
  static const Duration reducedCrossfade = Duration(milliseconds: 120);
  static const Cubic standard = Cubic(0.2, 0.0, 0.0, 1.0);
  static const Cubic standardDecelerate = Cubic(0.0, 0.0, 0.0, 1.0);
  static const Cubic standardAccelerate = Cubic(0.3, 0.0, 1.0, 1.0);
  static const Cubic emphasizedDecelerate = Cubic(0.05, 0.7, 0.1, 1.0);
  static const Cubic emphasizedAccelerate = Cubic(0.3, 0.0, 0.8, 0.15);
  static final SpringDescription fastSpatialSpring = SpringDescription.withDampingRatio(mass: 1.0, stiffness: 1400.0, ratio: 0.9);
  static final SpringDescription defaultSpatialSpring = SpringDescription.withDampingRatio(mass: 1.0, stiffness: 700.0, ratio: 0.9);
  static final SpringDescription expressiveSpatialSpring = SpringDescription.withDampingRatio(mass: 1.0, stiffness: 380.0, ratio: 0.8);
  static final SpringDescription defaultEffectsSpring = SpringDescription.withDampingRatio(mass: 1.0, stiffness: 1600.0, ratio: 1.0);
}

/// Glass is ONLY for navigation/control layers (tab bar, toolbar, floating controls).
/// Never behind price breakdowns, payment status, SafePay banners or receipts.
abstract final class JkGlass {
  static const double blurSigma = 20.0;
  static const double saturation = 1.8;
  static const double opacityLight = 0.8;
  static const double opacityDark = 0.8;
  static const double borderWidth = 0.5;
}

abstract final class JkTouchTarget {
  static const double ios = 44.0;
  static const double android = 48.0;
  static const double minSpacing = 8.0;
}

abstract final class JkBreakpoints {
  static const double compact = 0.0;
  static const double medium = 600.0;
  static const double expanded = 840.0;
  static const double large = 1200.0;
  static const double extraLarge = 1600.0;
}

abstract final class JkOpacity {
  static const double hover = 0.08;
  static const double focus = 0.1;
  static const double pressed = 0.12;
  static const double dragged = 0.16;
  static const double disabledContent = 0.38;
  static const double disabledContainer = 0.12;
}

/// Poppins type scale. Sizes are logical pixels; they scale with the user's text scaler
/// (support up to 2.0×). Money styles use tabular figures.
abstract final class JkTypeScale {
  static const String fontFamily = 'Poppins';

  static const TextStyle display = TextStyle(
    fontFamily: fontFamily,
    fontSize: 40.0,
    height: 1.2,
    fontWeight: FontWeight.w700,
    letterSpacing: -0.8,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle headlineL = TextStyle(
    fontFamily: fontFamily,
    fontSize: 32.0,
    height: 1.25,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.48,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle headlineM = TextStyle(
    fontFamily: fontFamily,
    fontSize: 28.0,
    height: 1.2857,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.28,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle headlineS = TextStyle(
    fontFamily: fontFamily,
    fontSize: 24.0,
    height: 1.3333,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.12,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle titleL = TextStyle(
    fontFamily: fontFamily,
    fontSize: 20.0,
    height: 1.4,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle titleM = TextStyle(
    fontFamily: fontFamily,
    fontSize: 18.0,
    height: 1.4444,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle titleS = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16.0,
    height: 1.5,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle bodyL = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16.0,
    height: 1.5,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle bodyM = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14.0,
    height: 1.5714,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle bodyS = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12.0,
    height: 1.5,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.12,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle labelL = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14.0,
    height: 1.4286,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.07,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle labelM = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12.0,
    height: 1.3333,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.24,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle labelS = TextStyle(
    fontFamily: fontFamily,
    fontSize: 11.0,
    height: 1.4545,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.44,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const TextStyle moneyL = TextStyle(
    fontFamily: fontFamily,
    fontSize: 28.0,
    height: 1.2857,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.28,
    leadingDistribution: TextLeadingDistribution.even,
    fontFeatures: <ui.FontFeature>[ui.FontFeature.tabularFigures()],
  );

  static const TextStyle moneyM = TextStyle(
    fontFamily: fontFamily,
    fontSize: 18.0,
    height: 1.4444,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
    fontFeatures: <ui.FontFeature>[ui.FontFeature.tabularFigures()],
  );

  static const TextStyle moneyS = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14.0,
    height: 1.4286,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.0,
    leadingDistribution: TextLeadingDistribution.even,
    fontFeatures: <ui.FontFeature>[ui.FontFeature.tabularFigures()],
  );
}
