import { z } from '@hono/zod-openapi';
import { ConsentInputSchema, DeviceInputSchema, ProfileSchema } from '../me/schemas';

export const OtpChannel = z.enum(['SMS', 'WHATSAPP', 'EMAIL']);
export const OtpPurpose = z.enum(['LOGIN', 'VERIFY_PHONE', 'VERIFY_EMAIL', 'SENSITIVE_ACTION']);

/** SEC-12: money-routing changes that need a fresh step-up OTP bound to (action, target). */
export const SensitiveAction = z
  .enum(['REFUND_DESTINATION_SET', 'PAYOUT_ACCOUNT_ADD', 'PAYOUT_ACCOUNT_SET_DEFAULT'])
  .openapi('SensitiveAction', { description: 'targetId: refund id · own user id · payout account id' });

export const OtpRequestBody = z
  .object({
    channel: OtpChannel,
    destination: z.string().min(5).max(254).openapi({ example: '+6281234567890' }),
    purpose: OtpPurpose.default('LOGIN'),
    locale: z.enum(['id', 'en']).optional(),
    action: SensitiveAction.optional().openapi({ description: 'SENSITIVE_ACTION only (required)' }),
    targetId: z.string().min(1).max(128).optional().openapi({ description: 'SENSITIVE_ACTION only (required): refund id, own user id (PAYOUT_ACCOUNT_ADD) or payout account id' }),
  })
  .openapi('OtpRequest');

/** Proof of a SENSITIVE_ACTION step-up: the challenge from POST /auth/otp/request and the code the user received. */
export const StepUpProof = z
  .object({ challengeId: z.string().uuid(), code: z.string().regex(/^\d{6}$/) })
  .openapi('StepUpProof', { description: 'SENSITIVE_ACTION OTP (10 min, single use, bound to action + target)' });

export const OtpRequestResponse = z
  .object({
    challengeId: z.string().uuid(),
    expiresAt: z.string(),
    resendAvailableAt: z.string(),
    devCode: z.string().optional().openapi({ description: 'Only when OTP_DEV_ECHO=true (development/test); never in staging/production' }),
  })
  .openapi('OtpChallenge');

export const TokensSchema = z
  .object({
    tokenType: z.literal('Bearer'),
    accessToken: z.string(),
    accessTokenExpiresAt: z.string(),
    refreshToken: z
      .string()
      .optional()
      .openapi({
        description:
          'Opaque, single-use (rotated on every refresh). Always present with the default body transport (mobile, admin). ' +
          'OMITTED when the request sent `X-JK-Token-Transport: cookie` (web): the token is then only in the HttpOnly cookie `jk_rt` set by the API host.',
      }),
    refreshTokenExpiresAt: z.string(),
    sessionId: z.string().uuid(),
  })
  .openapi('Tokens');

const SignupExtras = {
  device: DeviceInputSchema.optional(),
  consents: z
    .array(ConsentInputSchema)
    .max(10)
    .optional()
    .openapi({ description: 'Required when a new account is created: TOS and PRIVACY granted (MARKETING optional)' }),
};

export const OtpVerifyBody = z
  .object({
    challengeId: z.string().uuid(),
    code: z.string().regex(/^\d{6}$/),
    ...SignupExtras,
  })
  .openapi('OtpVerify');

export const LoginResponse = z
  .object({
    tokens: TokensSchema,
    user: ProfileSchema,
    isNewUser: z.boolean(),
  })
  .openapi('LoginResult');

export const OtpVerifyResponse = z
  .object({
    purpose: OtpPurpose,
    verified: z.literal(true),
    user: ProfileSchema,
    tokens: TokensSchema.optional().openapi({ description: 'LOGIN only' }),
    isNewUser: z.boolean().optional().openapi({ description: 'LOGIN only' }),
  })
  .openapi('OtpVerifyResult');

export const GoogleBody = z
  .object({
    idToken: z.string().min(20).max(8192),
    nonce: z
      .string()
      .min(16)
      .max(256)
      .optional()
      .openapi({
        description:
          'Random value the client passed to Google (GIS `nonce`); the ID token `nonce` claim must equal it (constant-time) → 401 OAUTH_TOKEN_INVALID {reason: NONCE_MISMATCH}. ' +
          'A verified nonce makes the ID token single use (replay → {reason: NONCE_REUSED}). Required when GOOGLE ∈ OAUTH_REQUIRE_NONCE (401 OAUTH_NONCE_REQUIRED); optional by default (mobile does not send it yet).',
      }),
    ...SignupExtras,
  })
  .openapi('GoogleSignIn');

export const AppleBody = z
  .object({
    identityToken: z.string().min(20).max(8192),
    nonce: z.string().max(256).optional().openapi({ description: 'Expected `nonce` claim, compared verbatim (i.e. the SHA-256 hex the app passed to Apple). Prefer rawNonce.' }),
    rawNonce: z
      .string()
      .min(16)
      .max(256)
      .optional()
      .openapi({
        description:
          'Raw nonce generated by the app. The app passes SHA-256(rawNonce) (lowercase hex) to Apple; the API requires the identity token `nonce` claim to equal that hash (constant-time) → 401 OAUTH_TOKEN_INVALID {reason: NONCE_MISMATCH} otherwise. ' +
          'REQUIRED by default (APPLE ∈ OAUTH_REQUIRE_NONCE): a request with neither rawNonce nor nonce → 401 OAUTH_NONCE_REQUIRED. The verified nonce is single use (replay → {reason: NONCE_REUSED}).',
      }),
    fullName: z
      .object({ givenName: z.string().max(40).optional(), familyName: z.string().max(40).optional() })
      .optional()
      .openapi({ description: 'Apple sends the name only on the FIRST authorization; stored only when the account is created' }),
    ...SignupExtras,
  })
  .openapi('AppleSignIn');

const RefreshTokenField = z.string().min(20).max(200);
export const RefreshBody = z
  .object({
    refreshToken: RefreshTokenField.optional().openapi({
      description: 'Required with body transport. With `X-JK-Token-Transport: cookie` it may be omitted (the body may be empty): the `jk_rt` cookie is used.',
    }),
  })
  .openapi('Refresh');
export const LogoutBody = z
  .object({
    refreshToken: RefreshTokenField.optional().openapi({
      description: 'Optional: revokes the session this refresh token belongs to (lets a client without a valid access token log out). Cookie transport reads `jk_rt` instead.',
    }),
  })
  .openapi('Logout');
export const RefreshResponse = z.object({ tokens: TokensSchema }).openapi('RefreshResult');

export const SessionSchema = z
  .object({
    id: z.string().uuid(),
    current: z.boolean(),
    createdAt: z.string(),
    lastActiveAt: z.string(),
    expiresAt: z.string(),
    device: z.object({ id: z.string().uuid(), platform: z.string(), appVersion: z.string().nullable() }).nullable(),
    userAgent: z.string().nullable(),
  })
  .openapi('Session');

export const MfaEnrollResponse = z
  .object({
    factorId: z.string().uuid(),
    secret: z.string().openapi({ description: 'Base32 TOTP secret — shown ONCE, never returned again' }),
    otpauthUri: z.string(),
    issuer: z.string(),
  })
  .openapi('MfaEnrollment');

export const MfaCodeBody = z.object({ code: z.string().regex(/^\d{6}$/) }).openapi('MfaCode');
export const MfaVerifyBody = z
  .object({
    code: z.string().regex(/^\d{6}$/).optional(),
    recoveryCode: z.string().regex(/^[0-9A-Z]{4}-[0-9A-Z]{4}$/).optional(),
  })
  .refine((b) => !!b.code !== !!b.recoveryCode, { message: 'Isi salah satu: code atau recoveryCode' })
  .openapi('MfaVerify');

export const MfaConfirmResponse = z
  .object({
    confirmed: z.literal(true),
    recoveryCodes: z.array(z.string()).openapi({ description: 'Shown ONCE' }),
    accessToken: z.string(),
    accessTokenExpiresAt: z.string(),
    mfaAt: z.number().int(),
  })
  .openapi('MfaConfirmation');

export const MfaVerifyResponse = z
  .object({ accessToken: z.string(), accessTokenExpiresAt: z.string(), mfaAt: z.number().int(), method: z.enum(['TOTP', 'RECOVERY_CODE']) })
  .openapi('MfaStepUp');
