/**
 * TEST FIXTURES ONLY — illustrative rules shaped like the DB tables. Rates here are NOT legal
 * references; production rules live in `customs_rules` / `restricted_items` with sourceReference.
 */
import type { CustomsRule } from '../customs';
import type { RestrictedItemRule } from '../restricted';

const base = {
  destinationCountry: 'ID',
  originCountry: null,
  hsCodePrefix: null,
  categoryCode: null,
  treatment: 'ANY',
  exemptionUsd: null,
  luxuryTaxRate: '0',
  incomeTaxRateNoNpwp: null,
  rounding: 'CEIL_1000',
  priority: 0,
  effectiveFrom: '2025-01-01',
  effectiveUntil: null,
  sourceReference: 'FIXTURE — not a legal reference',
  sourceUrl: null,
  lastVerifiedAt: '2026-08-01',
  status: 'ACTIVE',
} as const;

export const CUSTOMS_RULES: readonly CustomsRule[] = [
  {
    ...base,
    id: 'r-generic',
    code: 'ID_PASSENGER_GENERIC',
    version: 3,
    formulaCode: 'ID_PASSENGER_V2025',
    exemptionUsd: '500',
    dutyRate: '0.10',
    vatRate: '0.12',
    vatDppFactor: '0.916667',
    incomeTaxRate: '0.10',
    incomeTaxRateNoNpwp: '0.20',
  },
  {
    ...base,
    id: 'r-footwear-hs',
    code: 'ID_FOOTWEAR_6403',
    version: 1,
    hsCodePrefix: '6403',
    formulaCode: 'ID_PASSENGER_V2025',
    exemptionUsd: '500',
    dutyRate: '0.25',
    vatRate: '0.12',
    vatDppFactor: '0.916667',
    incomeTaxRate: '0.10',
    incomeTaxRateNoNpwp: '0.20',
  },
  {
    ...base,
    id: 'r-cosmetics-cat',
    code: 'ID_COSMETICS_FLAT',
    version: 1,
    categoryCode: 'COSMETICS_SKINCARE',
    formulaCode: 'FLAT_RATES',
    dutyRate: '0.15',
    vatRate: '0.12',
    vatDppFactor: '0.916667',
    incomeTaxRate: '0.10',
    rounding: 'NONE',
  },
  {
    ...base,
    id: 'r-books-exempt',
    code: 'ID_BOOKS_EXEMPT',
    version: 1,
    categoryCode: 'BOOKS_MEDIA',
    formulaCode: 'EXEMPT',
    dutyRate: '0',
    vatRate: '0',
    vatDppFactor: '1',
    incomeTaxRate: '0',
  },
  {
    ...base,
    id: 'r-us-origin',
    code: 'ID_FROM_US',
    version: 1,
    originCountry: 'US',
    formulaCode: 'ID_PASSENGER_V2025',
    exemptionUsd: '500',
    dutyRate: '0.075',
    vatRate: '0.12',
    vatDppFactor: '0.916667',
    incomeTaxRate: '0.10',
    incomeTaxRateNoNpwp: '0.20',
  },
  {
    ...base,
    id: 'r-draft',
    code: 'ID_DRAFT',
    version: 9,
    hsCodePrefix: '851712',
    status: 'DRAFT',
    formulaCode: 'EXEMPT',
    dutyRate: '0',
    vatRate: '0',
    vatDppFactor: '1',
    incomeTaxRate: '0',
  },
  {
    ...base,
    id: 'r-old-footwear',
    code: 'ID_FOOTWEAR_6403_OLD',
    version: 0,
    hsCodePrefix: '6403',
    effectiveFrom: '2020-01-01',
    effectiveUntil: '2024-12-31',
    formulaCode: 'EXEMPT',
    dutyRate: '0',
    vatRate: '0',
    vatDppFactor: '1',
    incomeTaxRate: '0',
  },
];

const rbase = {
  version: 1,
  originCountry: null,
  destinationCountry: 'ID',
  categoryCode: null,
  hsCodePrefix: null,
  keywords: [],
  maxQuantity: null,
  maxValueUsd: null,
  permitAuthority: null,
  airlineDg: false,
  sourceReference: 'FIXTURE — not a legal reference',
  effectiveFrom: '2025-01-01',
  effectiveUntil: null,
  status: 'ACTIVE',
} as const;

export const RESTRICTED_RULES: readonly RestrictedItemRule[] = [
  {
    ...rbase,
    code: 'WEAPONS',
    categoryCode: 'WEAPONS_REPLICAS',
    classification: 'PROHIBITED',
    messageId: 'Senjata & replika dilarang.',
    messageEn: 'Weapons & replicas are prohibited.',
  },
  {
    ...rbase,
    code: 'VAPE_KEYWORD',
    keywords: ['vape', 'e-cigarette', 'rokok elektrik'],
    classification: 'PROHIBITED',
    messageId: 'Rokok elektrik tidak dapat dititipkan.',
    messageEn: 'E-cigarettes cannot be shipped.',
  },
  {
    ...rbase,
    code: 'MEDICINE_BPOM',
    categoryCode: 'MEDICINE',
    classification: 'PERMIT_REQUIRED',
    permitAuthority: 'BPOM',
    messageId: 'Obat memerlukan izin BPOM.',
    messageEn: 'Medicine requires a BPOM permit.',
  },
  {
    ...rbase,
    code: 'POWERBANK_DG',
    categoryCode: 'BATTERIES_POWERBANK',
    classification: 'RESTRICTED',
    airlineDg: true,
    dgNote: 'Kabin saja',
    maxQuantity: 2,
    messageId: 'Power bank hanya di kabin, maks. 2 unit.',
    messageEn: 'Power banks carry-on only, max 2 units.',
  },
  {
    ...rbase,
    code: 'PHONE_IMEI',
    hsCodePrefix: '8517',
    classification: 'DECLARATION_REQUIRED',
    maxQuantity: 2,
    messageId: 'Ponsel wajib didaftarkan IMEI.',
    messageEn: 'Phones require IMEI registration.',
  },
  {
    ...rbase,
    code: 'ALCOHOL_LIMIT',
    categoryCode: 'ALCOHOL',
    classification: 'RESTRICTED',
    maxQuantity: 1,
    maxValueUsd: '150',
    messageId: 'Minuman beralkohol maks. 1 liter.',
    messageEn: 'Alcohol max 1 litre.',
  },
  {
    ...rbase,
    code: 'CREME_BRULEE_TORCH',
    keywords: ['crème brûlée torch', 'butane'],
    classification: 'RESTRICTED',
    airlineDg: true,
    dgNote: 'Dilarang di pesawat',
    messageId: 'Gas butana dilarang di pesawat.',
    messageEn: 'Butane is forbidden on aircraft.',
  },
  {
    ...rbase,
    code: 'OLD_RULE',
    categoryCode: 'TOYS_HOBBIES',
    classification: 'PROHIBITED',
    effectiveUntil: '2025-05-31',
    messageId: 'Kedaluwarsa',
    messageEn: 'Expired',
  },
];
