/**
 * Generates src/modules/infra/migration-manifest.ts: SHA-256 (hex, over the raw file bytes — the same checksum
 * db/scripts/migrate.sh stores in schema_migrations) of every db/migrations/NNNN_name.sql, embedded at build time so the
 * DB & Infra Center can compare the running database with the code that is deployed (pending / applied / drift).
 *
 *   cd apps/api && npx tsx scripts/gen-migration-manifest.ts          # write
 *   cd apps/api && npx tsx scripts/gen-migration-manifest.ts --check  # exit 1 when stale (CI)
 *
 * src/modules/infra/migration-manifest.test.ts fails when the manifest is stale.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface ManifestEntry {
  version: string;
  name: string;
  file: string;
  checksum: string;
}

export const MIGRATIONS_DIR = join(import.meta.dirname, '../../../db/migrations');
export const MANIFEST_PATH = join(import.meta.dirname, '../src/modules/infra/migration-manifest.ts');

export function computeManifest(dir = MIGRATIONS_DIR): ManifestEntry[] {
  return readdirSync(dir)
    .filter((f) => /^[0-9]{4}_[a-z0-9_]+\.sql$/.test(f))
    .sort()
    .map((file) => {
      const base = file.replace(/\.sql$/, '');
      const version = base.slice(0, 4);
      return { version, name: base.slice(5), file, checksum: createHash('sha256').update(readFileSync(join(dir, file))).digest('hex') };
    });
}

export function renderManifest(entries: ManifestEntry[]): string {
  const lines = entries.map((e) => `  { version: '${e.version}', name: '${e.name}', file: '${e.file}', checksum: '${e.checksum}' },`);
  return [
    '// GENERATED by apps/api/scripts/gen-migration-manifest.ts — DO NOT EDIT BY HAND.',
    '// SHA-256 of each db/migrations/*.sql (raw bytes), identical to schema_migrations.checksum written by db/scripts/migrate.sh.',
    '// Regenerate after adding a migration: cd apps/api && npx tsx scripts/gen-migration-manifest.ts',
    '',
    'export interface MigrationManifestEntry {',
    '  version: string;',
    '  name: string;',
    '  file: string;',
    '  checksum: string;',
    '}',
    '',
    'export const MIGRATION_MANIFEST: readonly MigrationManifestEntry[] = [',
    ...lines,
    '];',
    '',
  ].join('\n');
}

const isMain = process.argv[1] && import.meta.filename === process.argv[1];
if (isMain) {
  const out = renderManifest(computeManifest());
  if (process.argv.includes('--check')) {
    let cur = '';
    try {
      cur = readFileSync(MANIFEST_PATH, 'utf8');
    } catch {
      /* missing */
    }
    if (cur !== out) {
      console.error('migration-manifest.ts is stale — run: npx tsx scripts/gen-migration-manifest.ts');
      process.exit(1);
    }
    console.log('migration manifest up to date');
  } else {
    writeFileSync(MANIFEST_PATH, out);
    console.log(`wrote ${MANIFEST_PATH} (${computeManifest().length} migrations)`);
  }
}
