/**
 * Generates db/seeds/0200_legal_documents.sql from the legal templates in docs/legal/*.md: one PUBLISHED row per
 * document (locale `id`, version `0.1-template`), body = the markdown without its frontmatter (the TEMPLATE banner is
 * kept verbatim), title/summary from the frontmatter. Idempotent: ON CONFLICT (type, version, locale) DO NOTHING —
 * published legal text is immutable evidence (jk_legal_document_guard), so a changed template needs a NEW version
 * (bump LEGAL_TEMPLATE_VERSION in src/modules/legal/catalog.ts) rather than an edit of the published row.
 *
 *   cd apps/api && npx tsx scripts/gen-legal-seed.ts          # write
 *   cd apps/api && npx tsx scripts/gen-legal-seed.ts --check  # exit 1 when the committed seed is stale (CI)
 *
 * src/modules/legal/legal.test.ts fails when the seed is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LEGAL_SLUGS, LEGAL_TEMPLATE_BANNER, LEGAL_TEMPLATE_VERSION, type LegalType } from '../src/modules/legal/catalog';

export const LEGAL_DOCS_DIR = join(import.meta.dirname, '../../../docs/legal');
export const LEGAL_SEED_PATH = join(import.meta.dirname, '../../../db/seeds/0200_legal_documents.sql');
/** Fixed publication instant of the template versions (deterministic seed output). */
export const LEGAL_TEMPLATE_PUBLISHED_AT = '2026-09-27T00:00:00Z';
const TAG = '$jk_legal$';

export interface LegalTemplate {
  type: LegalType;
  slug: string;
  title: string;
  summary: string;
  bodyMd: string;
}

function parseFrontmatter(raw: string, file: string): { meta: Record<string, string>; body: string } {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(raw);
  if (!m) throw new Error(`${file}: missing YAML frontmatter`);
  const meta: Record<string, string> = {};
  for (const line of m[1]!.split(/\r?\n/)) {
    const kv = /^([A-Za-z][A-Za-z0-9_]*):\s*(.*)$/.exec(line);
    if (!kv) continue;
    let v = kv[2]!.trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    meta[kv[1]!] = v;
  }
  return { meta, body: raw.slice(m[0].length).replace(/^\s+/, '').replace(/\s+$/, '') + '\n' };
}

export function readLegalTemplates(dir = LEGAL_DOCS_DIR): LegalTemplate[] {
  const bySlug = new Map((Object.entries(LEGAL_SLUGS) as [LegalType, string][]).map(([type, slug]) => [slug, type]));
  const files = readdirSync(dir).filter((f) => f.endsWith('.md')).sort();
  const out: LegalTemplate[] = [];
  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    const type = bySlug.get(slug);
    if (!type) throw new Error(`${file}: no legal document type mapped to slug "${slug}" (src/modules/legal/catalog.ts)`);
    const { meta, body } = parseFrontmatter(readFileSync(join(dir, file), 'utf8'), file);
    if (!meta.title) throw new Error(`${file}: frontmatter title missing`);
    if (!body.includes(LEGAL_TEMPLATE_BANNER)) throw new Error(`${file}: TEMPLATE banner missing — templates must keep it`);
    if (body.includes(TAG)) throw new Error(`${file}: body contains the dollar-quote tag ${TAG}`);
    out.push({ type, slug, title: meta.title, summary: meta.description ?? '', bodyMd: body });
  }
  const missing = Object.values(LEGAL_SLUGS).filter((s) => !out.some((t) => t.slug === s));
  if (missing.length) throw new Error(`docs/legal is missing: ${missing.join(', ')}`);
  return out;
}

const q = (v: string) => `${TAG}${v}${TAG}`;

export function renderLegalSeed(templates: LegalTemplate[]): string {
  const rows = templates.map(
    (t) =>
      `INSERT INTO legal_documents (type, version, locale, title, summary, body_md, summary_of_changes, published_at)\n` +
      `VALUES ('${t.type}', '${LEGAL_TEMPLATE_VERSION}', 'id', ${q(t.title)}, ${q(t.summary)},\n${q(t.bodyMd)},\n` +
      `        'Versi template awal dari docs/legal/${t.slug}.md — wajib direview konsultan hukum sebelum production launch.', '${LEGAL_TEMPLATE_PUBLISHED_AT}')\n` +
      `ON CONFLICT (type, version, locale) DO NOTHING;`,
  );
  return [
    '-- GENERATED by apps/api/scripts/gen-legal-seed.ts from docs/legal/*.md — DO NOT EDIT BY HAND.',
    `-- ${templates.length} legal templates, version ${LEGAL_TEMPLATE_VERSION}, locale id, published (visible via GET /v1/legal/documents).`,
    '-- TEMPLATE text: must be reviewed by legal counsel before production launch (banner kept in every body).',
    '-- Idempotent: published rows are immutable, re-running never changes them.',
    'BEGIN;',
    '',
    rows.join('\n\n'),
    '',
    'COMMIT;',
    '',
  ].join('\n');
}

const isMain = process.argv[1] && import.meta.filename === process.argv[1];
if (isMain) {
  const out = renderLegalSeed(readLegalTemplates());
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(LEGAL_SEED_PATH, 'utf8');
    } catch {
      /* missing */
    }
    if (current !== out) {
      console.error('db/seeds/0200_legal_documents.sql is stale — run: cd apps/api && npx tsx scripts/gen-legal-seed.ts');
      process.exit(1);
    }
    console.log('legal seed up to date');
  } else {
    writeFileSync(LEGAL_SEED_PATH, out);
    console.log(`wrote db/seeds/0200_legal_documents.sql (${out.length} bytes)`);
  }
}
